# Mercari(일본 중고거래 플랫폼) 가격 예측 프로젝트

## 프로젝트 흐름  
1. 환경 설정 및 데이터 로드
2. 데이터 전처리 (카테고리 분리, 결측치 처리)
3. 텍스트 특징 추출 (NLP_자연어 처리)
4. 새로운 피처 생성
5. 모델 학습
6. 가격 예측 & 제출

### 1. 환경설정 및 데이터 로드

In [1]:
pip install pandas numpy scikit-learn lightgbm nltk scipy

Requirement already satisfied: pandas in c:\users\berga\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\berga\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: scikit-learn in c:\users\berga\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: lightgbm in c:\users\berga\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: nltk in c:\users\berga\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: scipy in c:\users\berga\anaconda3\lib\site-packages (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\berga\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\berga\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\berga\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\berga\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\berga\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: click in c:\users\berga\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\berga\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\berga\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\berga\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\berga\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\berga\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\berga\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\berga\anaconda3\Lib\site-packages)

In [2]:
# 1. 환경설정
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

# 1. 데이터 로드
train = pd.read_csv('train.tsv', sep='\t')
test  = pd.read_csv('test.tsv',  sep='\t')

print(train.shape)
print(train.head())

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\berga\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\berga\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\berga\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

(1482535, 8)
   train_id                                 name  item_condition_id  \
0         0  MLB Cincinnati Reds T Shirt Size XL                  3
1         1     Razer BlackWidow Chroma Keyboard                  3
2         2                       AVA-VIV Blouse                  1
3         3                Leather Horse Statues                  1
4         4                 24K GOLD plated rose                  1

                                       category_name brand_name  price  \
0                                  Men/Tops/T-shirts        NaN   10.0
1  Electronics/Computers & Tablets/Components & P...      Razer   52.0
2                        Women/Tops & Blouses/Blouse     Target   10.0
3                 Home/Home Décor/Home Décor Accents        NaN   35.0
4                            Women/Jewelry/Necklaces        NaN   44.0

   shipping                                   item_description
0         1                                 No description yet
1         0  This keyboard is in great condition and works ...
2         1  Adorable top with a hint of lace and a key hol...
3         1  New with tags. Leather horses. Retail for [rm]...
4         0          Complete with certificate of authenticity

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482535 entries, 0 to 1482534
Data columns (total 8 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   train_id           1482535 non-null  int64
 1   name               1482535 non-null  object
 2   item_condition_id  1482535 non-null  int64
 3   category_name      1476208 non-null  object
 4   brand_name         849853 non-null   object
 5   price              1482535 non-null  float64
 6   shipping           1482535 non-null  int64
 7   item_description   1482529 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 90.5+ MB

In [4]:
train.describe()

           train_id  item_condition_id         price      shipping
count  1.482535e+06       1.482535e+06  1.482535e+06  1.482535e+06
mean   7.412670e+05       1.907380e+00  2.673752e+01  4.472744e-01
std    4.279711e+05       9.031586e-01  3.858607e+01  4.972124e-01
min    0.000000e+00       1.000000e+00  0.000000e+00  0.000000e+00
25%    3.706335e+05       1.000000e+00  1.000000e+01  0.000000e+00
50%    7.412670e+05       2.000000e+00  1.700000e+01  0.000000e+00
75%    1.111900e+06       3.000000e+00  2.900000e+01  1.000000e+00
max    1.482534e+06       5.000000e+00  2.009000e+03  1.000000e+00

In [5]:
# 결측치 확인
train.isna().sum()

train_id                  0
name                      0
item_condition_id         0
category_name          6327
brand_name           632682
price                     0
shipping                  0
item_description          6
dtype: int64

In [7]:
# 결측치 비율 확인
train.isna().mean()

train_id             0.000000
name                 0.000000
item_condition_id    0.000000
category_name        0.004268
brand_name           0.426757
price                0.000000
shipping             0.000000
item_description     0.000004
dtype: float64

In [8]:
train['item_condition_id'].unique() # 수치형 컬럼이지만 상태의 등급을 수치로 표현

array([3, 1, 2, 4, 5])

In [9]:
train['shipping'].unique() # 수치형 컬럼이지만 배송 유무에 대한 것을 수치로 표현

array([1, 0])

### 2. category_name 분리 ('/' 구분) 및 데이터 전처리 (결측치, 이상치)

In [9]:
train['category_name'].nunique()

1287

In [10]:
train['category_name'].unique()

array(['Men/Tops/T-shirts',
       'Electronics/Computers & Tablets/Components & Parts',
       'Women/Tops & Blouses/Blouse', ..., 'Handmade/Jewelry/Clothing',
       'Vintage & Collectibles/Supplies/Ephemera',
       'Handmade/Pets/Blanket'], shape=(1288,), dtype=object)

#### 2-1.category_name 분리 : 3단계 분리

In [23]:
def split_category(category):
    """카테고리를 최대 3단계로 분리"""
    if pd.isnull(category):
        return pd.Series(['Unknown', 'Unknown', 'Unknown'])
    parts = category.split('/', 2)  # 최대 3개로 분리
    while len(parts) < 3:
        parts.append('Unknown')
    return pd.Series(parts[:3])

# 카테고리 분리 적용
train[['cat_1', 'cat_2', 'cat_3']] = train['category_name'].apply(split_category)
test[['cat_1',  'cat_2', 'cat_3']] = test['category_name'].apply(split_category)

print(train['cat_1'].value_counts().head(10))  # 상위 카테고리 확인

cat_1
Women                     664385
Beauty                    207828
Kids                      171689
Electronics               122690
Men                        93680
Home                       67871
Vintage & Collectibles     46530
Other                      45351
Handmade                   30842
Sports & Outdoors          25342
Name: count, dtype: int64

In [24]:
train.head(5)

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description,cat_1,cat_2,cat_3
0,0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,NaN,10.0,1,No description yet,Men,Tops,T-shirts
1,1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Razer,52.0,0,This keyboard is in great condition and works ...,Electronics,Computers & Tablets,Components & Parts
2,2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Target,10.0,1,Adorable top with a hint of lace and a key hol...,Women,Tops & Blouses,Blouse
3,3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,NaN,35.0,1,New with tags. Leather horses. Retail for [rm]...,Home,Home Décor,Home Décor Accents
4,4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,NaN,44.0,0,Complete with certificate of authenticity,Women,Jewelry,Necklaces

In [25]:
# 중분류 카테고리 확인
train['cat_2'].unique()

array(['Tops', 'Computers & Tablets', 'Tops & Blouses', 'Home Décor',
       'Jewelry', 'Other', 'Swimwear', 'Apparel', 'Collectibles',
       'Makeup', 'Fragrance', 'Dresses', 'Office supplies', 'Shoes',
       'Gear', 'Athletic Apparel', 'Cell Phones & Accessories', 'Jeans',
       'Underwear', 'Skin Care', 'Toys', "Women's Handbags",
       'Video Games & Consoles', 'Coats & Jackets', 'Pants', 'Girls (4+)',
       'Antique', 'Kitchen & Dining', 'Sweaters', 'Boys 0-24 Mos',
       'Girls 0-24 Mos', 'Maternity', 'Bedding', 'Exercise',
       'Trading Cards', 'Boys (4+)', 'Storage & Organization', 'Fan Shop',
       'Girls 2T-5T', "Men's Accessories", 'Boys 2T-5T',
       "Women's Accessories", 'Daily & Travel items', 'Unknown', 'Skirts',
       'Hair Care', 'Pet Supplies', 'Book', 'Tools & Accessories',
       'Team Sports', 'Home Appliances', 'Accessories', 'Bags and Purses',
       'Sweats & Hoodies', 'Shorts', 'TV, Audio & Surveillance',
       'Outdoors', 'Bath & Body', 'Car Seats & Accessories', 'Toy', 'Art',
       'Seasonal Décor', 'Footwear', 'Housewares', 'Media',
       'Cameras & Photography', 'Glass', 'Paper Goods',
       'Cleaning Supplies', 'Books', "Kids' Home Store", 'Electronics',
       'Diapering', 'Bath', 'Children', 'Magazines', 'Artwork',
       'Automotive', 'Serving', 'Clothing', 'Supplies', 'Feeding',
       'Suits & Blazers', 'Golf', 'Music', 'Pets', 'Health & Baby Care',
       'Nursery', 'Furniture', 'Geekery', 'Musical instruments',
       'Books and Zines', 'Safety', 'Crochet', 'Home Decor', 'Holidays',
       'Strollers', 'Pregnancy & Maternity', 'Needlecraft',
       'Paper Ephemera', 'Car Audio, Video & GPS', 'Bathing & Skin Care',
       'Dolls and Miniatures', 'Suits', 'Weddings', 'Others', 'Knitting',
       'Patterns', 'Blazers & Sport Coats', 'Woodworking',
       'Potty Training', 'Candles', 'Ceramics and Pottery', 'Quilts'],
      dtype=object)

In [26]:
train['cat_2'].nunique()

114

In [27]:
train['cat_3'].unique()

array(['T-shirts', 'Components & Parts', 'Blouse', 'Home Décor Accents',
       'Necklaces', 'Other', 'Two-Piece', 'Girls', 'Doll', 'Face',
       'Women', 'Above Knee, Mini', 'School Supplies', 'Boots',
       'Makeup Sets', 'Eyes', 'Backpacks & Carriers', 'Makeup Palettes',
       'Tank, Cami', 'Sports Bras', 'Cell Phones & Smartphones',
       'Chargers & Cradles', 'T-Shirts', 'Athletic',
       'Cases, Covers & Skins', 'Pants, Tights, Leggings', 'One-Piece',
       'Boot Cut', 'Bras', 'Stuffed Animals & Plush', 'Totes & Shoppers',
       'Shirts & Tops', 'Consoles', 'Glass', 'Vest', 'Arts & Crafts',
       'Capris, Cropped', 'Messenger & Crossbody', 'Shoes',
       'Collectibles', 'Coffee & Tea Accessories', 'Brooch', 'Headsets',
       'Rings', 'Shorts', 'Fleece Jacket', 'Dolls & Accessories',
       'Crewneck', 'Jackets', 'Home Fragrance', 'Accessories',
       'Tops & Blouses', 'Sheets & Pillowcases', 'Fitness technology',
       'Dress Up & Pretend Play', 'Animation',
       'Jewelry Boxes & Organizers', 'Games', 'NCAA',
       'Electronics for Kids', 'Watches', 'Knee-Length', 'Wallets',
       'Tracksuits & Sweats', 'Loafers & Slip-Ons', 'Pumps', 'Full Zip',
       'Medical Supplies & Equipment', 'Unknown', 'Slim, Skinny', 'Belts',
       'Tapestries', 'Figurine', 'Lips', 'Mini', 'Fashion Sneakers',
       'Dresses', 'Shampoo & Conditioner Sets',
       'Video Gaming Merchandise', 'Top & T-shirts', 'Dogs',
       'Shoulder Bag', 'Hobo', 'Nails', 'Comics', 'Household Supplies',
       'Halter', 'Learning & Education', 'Makeup Brushes & Tools',
       'Earrings', 'Baby Gyms & Playmats', 'Cardigan',
       'Shipping Supplies', 'Collared', 'Panties', 'Jewelry', 'Sandals',
       'Baseball & Softball', 'Casual Pants', 'Candles & Home Scents',
       'Kitchen Appliances', 'Hooded', 'Cables & Adapters',
       'Coats & Jackets', 'Keychain', 'Asymmetrical Hem', 'Wristlet',
       'Clutch', 'Full-Length', 'Sweatshirt, Pullover', 'Casual Shorts',
       'Gadgets', 'Fishing', 'Leggings', 'Jeans',
       'iPad/Tablet/eBook Readers', 'Sports', 'Bath', 'Bracelets', 'Body',
       'Socks', 'Sports Nutrition', 'Action Figure', 'Hats',
       'Portable Audio & Accessories', 'Photo Albums & Frames',
       'Party Supplies', 'Action Figures & Statues',
       'Fitness accessories', 'Sunglasses', 'Photography', 'Eyewear',
       'Jean Jacket', 'Halloween', 'Dining & Entertaining',
       'Kitchen Utensils & Gadgets', 'Button-Front', 'Tops & T-Shirts',
       'Backpack Style', 'Cleats', 'Health Care', 'Tunic', 'Ceramic',
       'DVD', 'Cell Phone Accessories', 'Ink & Toner', 'Necklace',
       'Personal Care', 'Digital Cameras', 'Bottles', 'Sticker',
       'Jerseys', 'CD', 'Camera & Photo Accessories', 'Tote', 'Flats',
       'Polo, Rugby', 'Styling Products', 'Household Cleaners',
       'Blankets & Throws', 'Purse', 'Literature & Fiction', 'Bottoms',
       'Peacoat', 'One-Pieces', 'V-Neck', "Children's Books",
       'Small Appliances', 'Football', 'Hair Accessories',
       'Education & Teaching', 'Slippers', 'Swimwear', "Kids' Room Décor",
       'Duvet Covers & Sets', 'Track & Sweat Pants', 'Cosmetic Bags',
       'Hair Color', 'All Other Sports', 'Maxi', 'Lamps& Accessories',
       'Radio', 'Conditioners', 'NFL', 'Disposable Diapers',
       'Beach Accessories', 'Straight, Pencil', 'Bathroom Accessories',
       'Baby & Toddler Toys', 'Asymmetrical', 'Baby', 'Towels',
       'Lifestyle & Cultures', 'Military', 'Turtleneck, Mock',
       'Paintings', 'Building Toys', 'Button Down Shirt',
       'Scarves & Wraps', 'Feet', 'Khakis, Chinos', 'Straight Leg',
       'Book', 'MLB', 'Cowl Neck', 'Valentine', 'Hair Styling Tools',
       'Poncho', 'Video Game', 'Desktops & All-In-Ones', 'Thanksgiving',
       'Mid-Calf', 'Cloth Diapers', 'Mules & Clogs', 'Hobbies',
       'Car Electronics & Accessories', "Kids' Bedding", 'Tank',
       'Electronics', 'Backpacks, Bags & Briefcases', 'Dress Pants',
       'Cover-Ups', 'Painting', 'Screen Protectors', 'Boys', 'Cleansers',
       'Comforters & Sets', 'Hair', 'Blu-Ray', 'Drives, Storage & Media',
       'Kids', 'Bakeware', 'Mug', 'G-Strings & Thongs', 'Cape', 'Sweater',
       'Headphones', 'Polo Shirt', 'Charm', 'Clothing & Closet Storage',
       'Wall Decor', 'Scrapbooking', 'NBA', 'Handbag',
       'Pacifiers & Accessories', 'Capri, Cropped', 'Ties',
       '100 Years or Older', 'Pouch', 'Playards', 'Costume',
       'Vacuums & Floor Care', 'Makeup Remover', 'Blazer',
       'Brushes & Applicators', "Men's Golf Clubs", 'Film Photography',
       'Medical Books', 'Bottle-Feeding', 'Toy', 'Laptops & Netbooks',
       'Vinyl', 'Collar', 'Garment Steamers', 'Clocks',
       'Tools & Equipment', 'Cookbook', 'Pleated', 'Cards', 'Windbreaker',
       'Bedding', 'Pants', 'Diaper Pails & Refills', 'Cup',
       'Arts & Photography', 'Storage & Containers', 'VHS', 'Souvenir',
       'Sets & Kits', 'Exterior Accessories', 'Home Office Furniture',
       'Scrubs & Body Treatments', 'Classic, Straight Leg',
       'Wine Accessories', 'Wrap', 'Food', 'Boxing & MMA', 'Luggage',
       'Ring', 'Car Seats', 'Diaper Bags', 'Motorcycle', 'Shampoos',
       'Hoodie', 'Knit Top', 'Henley', 'Drawings', 'Cookware',
       'Electronic', 'Formal', 'Yoga & Pilates',
       'Networking & Connectivity', 'Humidifiers', 'Sets', 'Dress Shirts',
       'Writing', 'Volleyball', 'Styling Tools',
       "Kids' Furniture, Décor & Storage", 'Puffer', 'Science',
       'Bracelet', 'Christmas', '50 To 75 Years', 'Game', 'Calendars',
       'Batteries', 'Swings, Jumpers & Bouncers', 'Others',
       'DVD & Blu-ray Players', 'Raincoat', 'Athletic Training',
       'Hiking & Camping', 'Scoop Neck', 'Cargo', 'Breastfeeding',
       'Pant Suit', 'Bowl', 'A-Line', 'Wind & Woodwind Instruments',
       'Overalls', 'Dance/Ballet', 'Bookmark', 'Kitchen & Table Linens',
       'Waxing', 'Water Coolers & Filters', 'Sun', 'Work & Safety',
       'Monitors', 'Air Fresheners', 'Lingerie', 'Wipes & Holders', 'Men',
       'Pinback Button', 'Candles & Holders', 'Leg Warmers',
       'Highchairs & Booster Seats', 'Camcorders', 'Puzzles', 'Tumbler',
       'Vintage', 'Supplies', 'Business & Money', 'Bike & Skate',
       'Turtleneck', 'Candle Holder', 'Satchel', 'Organization',
       'iPad/Tablet/eBook Access', 'Skirt',
       'Bathroom Storage & Organization', 'Baskets', 'Stationery',
       'Hair & Scalp Treatments', 'Relaxed', 'Lanyard', 'Coaster',
       'Books and Zines', 'Indoor/Outdoor Games', 'NHL', 'Soccer',
       'Reference', 'Posters & Prints', 'Nail Tools', 'Leash',
       'Boyfriend', 'Baby Seats', 'Car', 'Televisions', 'Vases',
       'Area Rugs & Pads', 'Tray', 'Wine, Beer & Beverage Coolers',
       'Flare', 'Dress - Flat Front', 'Trench',
       'Prenatal Monitoring Devices', 'Easter',
       'Performance Parts & Accessories',
       'Toy Remote Control & Play Vehicles', 'Varsity/Baseball',
       'Travel Beds', 'Tennis & Racquets', 'Board Shorts', 'Dress',
       'Hands & Nails', '75 To 100 Years', 'Action, Adventure', 'Pendant',
       'Cabinet Locks & Straps', 'Golf Balls',
       'Lights & Lighting Accessories', 'Tweezers', 'Animal',
       'Bags & Cases', 'Sweatercoat', 'Needlepoint', 'Skateboard',
       'Storage & Organization', 'Teething Relief', 'Stamps',
       'Sports & Outdoor Play', 'Gloves', 'Mirrors', 'Basketball',
       'Apron', 'Walkers', 'Skirts, Skorts & Dresses', 'Snowboard',
       'GPS Units & Equipment', 'Linens', 'Soaps & Cleansers',
       'Sculptures', 'Hockey', 'Oxfords', 'Instrument Accessories',
       'Fabric', 'Home Decor', 'Parka', 'Bead', 'Vest, Sleeveless',
       'Laundry Storage & Organization', 'Guitars', 'Patch',
       'Interior Accessories', "St Patrick's", 'Window Treatments',
       'Corset', 'Golf Apparel', 'Scale Dollhouse Miniature', 'Skin Care',
       'Clothing', 'Pin', 'Biographies & Memoirs', 'Outdoor', 'Kitchen',
       'Swim Trunks', 'Bathing Accessories',
       'Food Service Equipment & Supplies', 'Christian Books & Bibles',
       'Decorative Pillows', 'Shampoo', 'Two Button', 'Bed Pillows',
       'Home Speakers & Subwoofers', 'Cake Toppers', 'Baskets & Bins',
       'Sci-Fi, Fantasy', 'Magic', 'Stationery & Party Supplies',
       'Quilts', 'Tricycles, Scooters & Wagons', 'Teacup', 'Clock',
       'Changing Pads & Covers', 'Health', 'Microphones & Accessories',
       'Basic Supplies', 'Tripods & Supports', 'Wool', 'Embroidery',
       'Bath Rugs', 'Home Surveillance', 'Space Heaters', 'Box',
       'Glassware', 'Rainwear', 'Sweeping', 'Family Planning Tests',
       'Baby & Child Care', 'Other Accessories',
       'GPS Accessories & Mounts', 'Leather', 'Knitting Supplies',
       'Corduroys', 'Board, Surf', 'History',
       'Studio Recording Equipment', 'Athletic Apparel',
       'Shampoo Plus Conditioner', 'Jacket', 'Baggy, Loose', 'Fans',
       'Washcloths & Towels', 'Art', 'Biography', 'Shopping Cart Covers',
       'Standard', 'Scarf', 'Linen', 'Flight/Bomber', 'Sun Protection',
       'Skirt Suit', 'One Button', 'Pet Lover', 'Track & Sweat Suits',
       'Keyboards', 'Sewing', 'Electrical Safety', 'Cuff Links',
       'Binoculars & Telescopes', 'Belt', 'Papermaking', 'Vests',
       'Stringed Instruments', 'Bowls', 'Snowsuits & Bibs', 'Hat',
       'Postcard', 'Breastfeeding Pillows & Stools', 'Home Audio',
       'Bathing Tubs & Seats', 'Travel Systems',
       'Printers, Scanners & Supplies', 'Full Skirt', 'Change Purse',
       'Politics & Social Sciences', 'Children', 'Washers & Dryers',
       'Air Purifiers', 'Teethers',
       'Decorative Pillows, Inserts & Covers', 'Pillows & Stools',
       'Kitchen Knives & Cutlery Accessories', 'Thermal Underwear',
       'Poster', 'Shrug', 'Dress Suit', 'Religion & Spirituality',
       'Nursery Décor', 'Novelty & Gag Toys', 'Racks, Shelves & Drawers',
       'Porcelain', 'Cage', 'Fiction', 'Maternity', 'Print', 'Yarn',
       'Gift Wrap', 'Bed', 'Wallet', 'Water Sports', 'Lenses & Filters',
       'Bedroom Furniture', 'Crafting', 'Nasal Aspirators', 'Car Care',
       'Toothbrushes', 'Mattress Pads', 'Decorations', 'Patriotic',
       'Humidifiers & Vaporizers', 'Housewares', 'Birthday',
       'Track & Field', 'Journal', 'Strength training', 'Puzzle',
       'Microwaves', 'Hair Loss Products', 'Dress - Pleat',
       'Illustration', 'Strategy Guides', 'Poetry',
       'Historical, Military', 'DJ, Electronic Music & Karaoke',
       'Backpack', 'Car Speakers & Systems', 'Feeding',
       'Salt and Pepper Shakers', 'Paper Towels', 'Air Conditioners',
       'Car Stereos & Components', 'Irons & Ironing Boards',
       'Science & Math', 'Hair Relaxers', 'Camera',
       'Replacement Parts & Tools', 'Mopping', 'Baguette', 'Signs',
       'Cabochon', 'Calendar', 'Sweaters', 'Epilators', 'Watch',
       'Cross Stitch', 'Swim Briefs', 'Vase', 'Bass Guitars',
       'Harnesses & Leashes', 'Wall Hanging', 'Lighting', 'Carving',
       'Case', 'Engineering & Transportation', 'How to', 'Peasant',
       'Lighting & Studio', 'Shirt', 'Motorcycle & Powersports',
       'Bags and Purses', 'Notebook', 'Equipment', 'Dress Shorts',
       'Amplifiers & Effects', 'Hip Bag', 'Drums & Percussion',
       'Travel Bathing Kits', 'Collages', 'Favors', 'Dehumidifiers',
       'Three Button', 'Polo', 'Grooming & Healthcare Kits',
       'Training Pants', 'Magnet', 'Telephone', 'Lacrosse', 'Hawaiian',
       'Religious', 'Outdoor Safety', 'Wide Leg', 'Personalized',
       'Joggers', 'Tshirt', 'Toiletry Kits', 'Ornaments', 'Golf Shoes',
       "Kids' Furniture", 'Trash Bags', 'Nursery Bedding', 'Diaper Bag',
       'Videogame', 'Planter', 'Potties & Seats',
       'Automotive Enthusiast Merchandise', 'Buckle', 'Printmaking',
       'Photographs', 'Casserole',
       'Shams, Bed Skirts & Bed Frame Draperies', 'Plate',
       'Garage Storage & Organization', 'Tires & Wheels', 'Instrument',
       'Paper', 'Bowling', 'Refrigerators', 'Inflatable Beds',
       'Kitchen Storage & Organization', 'Tiered', 'Other Furniture',
       'Frame', 'Teapot', "New Year's", 'Thermometers', 'Bathroom',
       'Television', 'Laptop', 'Living Room Furniture', "Kids' Bath",
       'Sleep Positioners', 'Accessory', 'Magnets', 'Humor', 'Slipcovers',
       'Bathroom Safety', 'Small Animal', 'Flatware',
       'Diaper Stackers & Caddies', 'Bubble Bath', 'Gift Sets',
       'Hair Perms & Texturizers', 'Skirts', 'Track Jacket',
       'Paperweights', 'Outerwear', 'Custom', 'Finding',
       'Maternity Pillows', 'Invitations', 'Live Sound & Stage',
       'Graphic Design', 'Cream and Sugar Set', 'Dinnerware Set',
       'Draft Stoppers', 'Comic', 'Nonfiction', 'Tuxedo',
       'Lithographs, Etchings & Woodcuts', 'Car Subwoofers',
       'Activity Centers & Entertainers', 'Pitcher', 'Button', 'Shawl',
       'Bedspreads & Coverlets', 'Gadget', 'Paint, Body & Trim',
       'Carpenter', 'Guest Books', 'Toys', 'Stained Glass', 'Block',
       'Bouquets', 'Replacement Parts', 'Denim', 'Golf Bags', 'Tape',
       'Storage Cabinets', 'Furniture', 'Art Doll', 'Bubble', 'Brushes',
       'Child Friendly', 'Car Video', 'Brass Instruments', 'Safety Caps',
       'Fireplaces & Accessories', 'Presentation', 'Doll Clothes',
       'Human Figure Doll', 'Suits & Blazers', 'Beads',
       'Home Entertainment Furniture', 'Fantasy', 'Bath Linen Sets',
       'Pillow', 'Day of the Dead', 'Badminton', 'Kitchen Safety',
       'Knitting', 'Lightweight', 'Decorating',
       'Flashes & Flash Accessories', 'Garbage Disposals', 'Plush',
       'Planters', 'Office', 'Gates & Doorways', 'Boxes',
       'Carpenter, Utility', 'Afghan', 'Trash & Recycling', 'Pillows',
       'Playard Bedding', 'Instructional', 'Changing Kits', 'Crochet',
       'RV Parts & Accessories', 'Educational', 'Origami',
       'Band & Orchestra', 'Chain', 'Pattern',
       'Home Brewing & Wine Making', 'Doll Clothing', 'Figurines',
       'Double Breasted', 'Table', 'Hair Coloring Tools', 'Music',
       'Illustrated', 'Prams', 'Car Security & Convenience',
       "Women's Golf Clubs", 'Dusting', 'Freezers & Ice Makers', 'Basket',
       'Trim', 'Oils & Fluids', 'Religion', 'Bed in a Bag', 'Storage',
       'Blanket', 'Powders & Lotions', 'Non-Slip Bath Mats',
       'Something Blue', 'House', 'Cleaning', 'Handkerchief', 'Animals',
       'Scifi', 'Tiles', 'Mixed Media', 'Sponges', 'Felted', 'Aceo',
       'Frames', 'Fixture', 'Serving', 'Beading', 'Grooming',
       'Seat Covers', 'Advertisement', 'Pad', 'Nail Care',
       'Holiday Décor Storage', 'Dishes', 'Coasters', 'Fabric Postcard',
       'Toddler', 'Chair', 'Candles', 'Bathroom Furniture Sets',
       'Price Guides & Publications', 'Paper Ephemera', 'Horror',
       'Nursery Furniture', 'Light', 'Patchwork', 'Tag', 'Handmade',
       'Primitive', 'Necktie', 'Bicycle Child Seats & Trailers', 'Sport',
       'Home Bar Furniture', 'Storage Solutions', 'Novelty', 'Pot Holder',
       'Boating', 'Map', 'Shelf', 'Entertaining/Serving', 'Scale Models',
       'Competitive Swimwear', 'International Publications', 'Cozy',
       'Miniature', 'St Patricks', 'Fashion Dolls Apparel', 'Butter Dish',
       'Mirror', 'Just Married', 'Cotton & Swabs', 'Pet Food',
       'Bathroom Furniture', 'Cuff', 'Hanukkah', 'Feather Beds',
       'Burning', 'Compact', 'Quilt', 'New Years', 'Edge & Corner Guards',
       'Doorstops', 'Seasonal', 'Bathroom Shelves', "Kids' Flatware",
       'Towel', 'Crib Netting', 'Four Button', 'Entertainment', 'Platter',
       'Zipper', 'Step Stools', 'Dishwashers', 'Bear', 'Artist Bears',
       'Doormats', 'Ephemera'], dtype=object)

In [28]:
train['cat_3'].nunique()

872

#### 2-2. category_name 결측치 확인 및 처리  

##### 2-2-1. category_name 결측치 확인

In [29]:
# 전체 결측치 현황 한눈에 보기
print("=== 결측치 현황 ===")
print(train.isna().sum())
print(f"\ncategory_name 결측치 수: {train['category_name'].isna().sum()}")
print(f"전체 대비 비율: {train['category_name'].isna().mean()*100:.2f}%")

# 결측치 샘플 확인 - 어떤 상품들인지 보기
null_category = train[train['category_name'].isna()][
    ['name', 'brand_name', 'item_description', 'price']
].sample(20, random_state=42)

print("\n=== category_name 결측 샘플 ===")
print(null_category.to_string())

=== 결측치 현황 ===
train_id                  0
name                      0
item_condition_id         0
category_name          6327
brand_name           632682
price                     0
shipping                  0
item_description          6
cat_1                     0
cat_2                     0
cat_3                     0
dtype: int64

category_name 결측치 수: 6327
전체 대비 비율: 0.43%

=== category_name 결측 샘플 ===
                                             name      brand_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         item_description  price
245817                             Mini deep dome         Zoo Med                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Zoo Med mini deep Dome brand new in box   10.0
1375593                          Lularoe Jaxon Xl             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                           This SOLID BLACK Lularoe jean jacket will go with everything in your wardrobe. It also has spandex in it and hidden pockets inside the jacket!  100.0
745172    Dog Leash & Collar Set By Juicy Couture             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Item is new in an unopened package   22.0
823760                            North Face Coat  The North Face                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       No description yet   35.0
1012577                           For Dear Monica             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                   Bundle includes a quality Dolman Top, a baby blue v-neck shirt, a Wrapped Maxi Skirt, a flare sleeves Top and a pair of Polka Dots palazzo. A gift will be sent alone.  171.0
991076           9 assorted Disney Star Wars Pins          Disney                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 You get all 9 pins featured in the photo   20.0
621070                               Doggie Steps             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Brought off Groupon and my nephew got more use out the stairs then my dog   21.0
1468508         Disney Showcase Collection Minnie          Disney                                                                                                                                                                                                                                                  FOR JASPI.... both Mickey and Minnie!! Perfect condition! From Jim Shore and Disney Traditions collections. Classic Minnie Mouse "Good-hearted Gal" #4056758 *FREE SHIPPING* •PLEASE SEE MY OTHER LISTING THAT HAS MATCHING MICKEY MOUSE ~BUY BOTH TOGETHER FOR REDUCED PRICE• Tags: WDW, Mickey Mouse, Collector, collectible, figure, figurine, decor   50.0
849383     Sterling Silver Choker 《Free Shipping》             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Retail: [rm] Brand new, never used Guiliana adjustable choker. Smoke & pet free home. Let's talk about bundling :)   12.0
671487   Star Wars Funko Smuggler's Bounty Bundle       Star Wars  Includes Han Solo and Greedo salt and pepper shakers, Wampa MyMoji, wristbands, Droids patch and 40th Anniversary patch. Price is firm and includes USPS first class shipping and packing materials. If you would like to insure your package against damage done in transit, additional costs will be added for priority shipping. I will not be held responsible for packages damaged by USPS if insurance is not purchased. Sold as is. Please note that Funko pops and boxes will NOT be described as mint. Every item is subject to imperfections. Additional photos can be provided upon request.   11.0
326448                                 Army Pants            Army                                                                                                                                                                                                                                                                                                                                                                                                                                                  Brand new in great condition men's Army pants. Waist size is 31 to 35in. Message for more info about this product below. Price is firm! HAPPY SHOPPING!    8.0
680520                         Zantrex-3 60 count             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Weight loss pills 60 count bottle still sealed. Normally [rm] in stores.   19.0
436670                               Roxy Sweater            Roxy                                                                                                                                                                                                                                                                                                                                                                                                                                                                Wool-like warm sweater from Roxy! Well worn but has a lot of life left! I only have 2 weeks to sell it before it ends up in my yard sale.    9.0
1096846     Carter's 2 Piece Christmas Pajamas 5T        Carter's                                                                                                                                                                                                                                                                                                                                                                                                                                                           Size: 5T Carter's 100% Cotton Excellent Used Condition No tears, stains, holes, or other signs of wear. Any questions please feel free to ask!    8.0
412735            Chance The rapper on teen vogue             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             New magazine    6.0
275704                                    Wedding             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Wedding Sign    9.0
123973                         10 Random Stickers             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       No description yet    3.0
1437739                      Dog Hoodie BRAND NEW             NaN                                                                                                                                                                                                                                                                                                                                                                                                                          Got this thinking it would fit my small boxer since it's an XL. No such luck. More for a shihtzu or smaller Bichon. Small Boston terrier. Would fit a dog between 12 and 20 lbs    8.0
909703                              Panama Bundle             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Panama purse and change holder. MADE IN PANAMA!   14.0
724412                                   Emily630             NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       No description yet   34.0

##### 2-2-2. category_name 결측치 처리 : 대분류 카테고리 키워드 매핑

In [30]:
print(sorted(train[train['cat_1'] == 'Women']['cat_2'].unique()))

['Athletic Apparel', 'Coats & Jackets', 'Dresses', 'Jeans', 'Jewelry', 'Maternity', 'Other', 'Pants', 'Shoes', 'Skirts', 'Suits & Blazers', 'Sweaters', 'Swimwear', 'Tops & Blouses', 'Underwear', "Women's Accessories", "Women's Handbags"]

In [32]:
print(sorted(train[train['cat_1'] == 'Beauty']['cat_2'].unique()))

['Bath & Body', 'Fragrance', 'Hair Care', 'Makeup', 'Other', 'Skin Care', 'Tools & Accessories']

In [33]:
print(sorted(train[train['cat_1'] == 'Kids']['cat_2'].unique()))

['Bathing & Skin Care', 'Boys (4+)', 'Boys 0-24 Mos', 'Boys 2T-5T', 'Car Seats & Accessories', 'Diapering', 'Feeding', 'Gear', 'Girls (4+)', 'Girls 0-24 Mos', 'Girls 2T-5T', 'Health & Baby Care', 'Nursery', 'Other', 'Potty Training', 'Pregnancy & Maternity', 'Safety', 'Strollers', 'Toys']

In [34]:
print(sorted(train[train['cat_1'] == 'Electronics']['cat_2'].unique()))

['Cameras & Photography', 'Car Audio, Video & GPS', 'Cell Phones & Accessories', 'Computers & Tablets', 'Media', 'Other', 'TV, Audio & Surveillance', 'Video Games & Consoles']

In [35]:
print(sorted(train[train['cat_1'] == 'Men']['cat_2'].unique()))

['Athletic Apparel', 'Blazers & Sport Coats', 'Coats & Jackets', 'Jeans', "Men's Accessories", 'Other', 'Pants', 'Shoes', 'Shorts', 'Suits', 'Sweaters', 'Sweats & Hoodies', 'Swimwear', 'Tops']

In [36]:
print(sorted(train[train['cat_1'] == 'Home']['cat_2'].unique()))

['Artwork', 'Bath', 'Bedding', 'Cleaning Supplies', 'Furniture', 'Home Appliances', 'Home Décor', "Kids' Home Store", 'Kitchen & Dining', 'Other', 'Seasonal Décor', 'Storage & Organization']

In [ ]:
print(sorted(train[train['cat_1'] == 'Vintage & Collectibles']['cat_2'].unique()))

['Accessories', 'Antique', 'Bags and Purses', 'Book', 'Clothing', 'Collectibles', 'Electronics', 'Furniture', 'Home Decor', 'Housewares', 'Jewelry', 'Other', 'Paper Ephemera', 'Serving', 'Supplies', 'Toy', 'Trading Cards']

In [38]:
print(sorted(train[train['cat_1'] == 'Handmade']['cat_2'].unique()))

['Accessories', 'Art', 'Bags and Purses', 'Books and Zines', 'Candles', 'Ceramics and Pottery', 'Children', 'Clothing', 'Crochet', 'Dolls and Miniatures', 'Furniture', 'Geekery', 'Glass', 'Holidays', 'Housewares', 'Jewelry', 'Knitting', 'Music', 'Needlecraft', 'Other', 'Others', 'Paper Goods', 'Patterns', 'Pets', 'Quilts', 'Toys', 'Weddings', 'Woodworking']

In [39]:
print(sorted(train[train['cat_1'] == 'Sports & Outdoors']['cat_2'].unique()))

['Apparel', 'Exercise', 'Fan Shop', 'Footwear', 'Golf', 'Other', 'Outdoors', 'Team Sports']

In [40]:
# 대분류 카테고리 키워드 매핑
CATEGORY_KEYWORDS = {
    'Women': [
        'Athletic Apparel', 'Coats & Jackets', 'Dresses', 'Jeans', 'Jewelry',
        'Maternity', 'Other', 'Pants', 'Shoes', 'Skirts', 'Suits & Blazers',
        'Sweaters', 'Swimwear', 'Tops & Blouses', 'Underwear', "Women's Accessories", "Women's Handbags"
    ],
    'Beauty': [
        'Bath & Body', 'Fragrance', 'Hair Care', 'Makeup', 'Other', 'Skin Care', 'Tools & Accessories'
    ],
    'Kids': [
        'Bathing & Skin Care', 'Boys (4+)', 'Boys 0-24 Mos', 'Boys 2T-5T', 'Car Seats & Accessories',
        'Diapering', 'Feeding', 'Gear', 'Girls (4+)', 'Girls 0-24 Mos', 'Girls 2T-5T',
        'Health & Baby Care', 'Nursery', 'Other', 'Potty Training', 'Pregnancy & Maternity', 'Safety', 'Strollers', 'Toys'
    ],
    'Electronics': [
        'Cameras & Photography', 'Car Audio, Video & GPS', 'Cell Phones & Accessories', 'Computers & Tablets',
        'Media', 'Other', 'TV, Audio & Surveillance', 'Video Games & Consoles'
    ],
    'Men': [
        'Athletic Apparel', 'Blazers & Sport Coats', 'Coats & Jackets', 'Jeans', "Men's Accessories",
        'Other', 'Pants', 'Shoes', 'Shorts', 'Suits', 'Sweaters', 'Sweats & Hoodies', 'Swimwear', 'Tops'
    ],
    'Home': [
        'Artwork', 'Bath', 'Bedding', 'Cleaning Supplies', 'Furniture', 'Home Appliances', 'Home Décor',
        "Kids' Home Store", 'Kitchen & Dining', 'Other', 'Seasonal Décor', 'Storage & Organization'
    ],
    'Vintage & Collectibles': [
        'Accessories', 'Antique', 'Bags and Purses', 'Book', 'Clothing', 'Collectibles', 'Electronics',
        'Furniture', 'Home Decor', 'Housewares', 'Jewelry', 'Other', 'Paper Ephemera', 'Serving', 'Supplies', 'Toy', 'Trading Cards'
    ],
    'Handmade': [
        'Accessories', 'Art', 'Bags and Purses', 'Books and Zines', 'Candles', 'Ceramics and Pottery', 'Children', 'Clothing',
        'Crochet', 'Dolls and Miniatures', 'Furniture', 'Geekery', 'Glass', 'Holidays', 'Housewares',
        'Jewelry', 'Knitting', 'Music', 'Needlecraft', 'Other', 'Others', 'Paper Goods', 'Patterns', 'Pets',
        'Quilts', 'Toys', 'Weddings', 'Woodworking'
    ],
    'Sports & Outdoors': [
        'Apparel', 'Exercise', 'Fan Shop', 'Footwear', 'Golf', 'Other', 'Outdoors', 'Team Sports'
    ],
    'Other': []  # 위 어디에도 해당 안되면 Other
}

def infer_category(row):
    """name + item_description으로 카테고리 추론"""
    
    # category_name이 있으면 그대로 사용
    if pd.notnull(row['category_name']):
        return row['category_name']
    
    text = ' '.join([
        str(row['name']),
        str(row['item_description'])
    ]).lower()
    
    # 키워드 매칭으로 카테고리 추론
    for category, keywords in CATEGORY_KEYWORDS.items():
        if any(kw in text for kw in keywords):
            return category  # 대분류만 반환 (세부분류 없음)
    
    return 'Other'

print("category_name 결측치 처리 중...")
train['category_name'] = train.apply(infer_category, axis=1)
test['category_name'] = test.apply(infer_category, axis=1)

# 결과 확인
print(f"처리 후 결측치 수: {train['category_name'].isna().sum()}")
print(f"\n추론된 카테고리 분포:")
print(train['category_name'].value_counts().head(15))

category_name 결측치 처리 중...
처리 후 결측치 수: 0

추론된 카테고리 분포:
category_name
Women/Athletic Apparel/Pants, Tights, Leggings                 60177
Women/Tops & Blouses/T-Shirts                                  46380
Beauty/Makeup/Face                                             34335
Beauty/Makeup/Lips                                             29910
Electronics/Video Games & Consoles/Games                       26557
Beauty/Makeup/Eyes                                             25215
Electronics/Cell Phones & Accessories/Cases, Covers & Skins    24676
Women/Underwear/Bras                                           21274
Women/Tops & Blouses/Tank, Cami                                20284
Women/Tops & Blouses/Blouse                                    20284
Women/Dresses/Above Knee, Mini                                 20082
Women/Jewelry/Necklaces                                        19758
Women/Athletic Apparel/Shorts                                  19528
Beauty/Makeup/Makeup Palettes                                  19103
Women/Shoes/Boots                                              18864
Name: count, dtype: int64

In [42]:
# category_name이 채워졌으니 다시 분리
def split_category(category):
    if pd.isna(category):
        return pd.Series(['Other', 'Unknown', 'Unknown'])
    parts = category.split('/', 2)
    while len(parts) < 3:
        parts.append('Unknown')
    return pd.Series(parts[:3])

print("카테고리 재분리 중...")
train[['cat_1','cat_2','cat_3']] = train['category_name'].apply(split_category)
test[['cat_1','cat_2','cat_3']] = test['category_name'].apply(split_category)

# 최종 확인
print("\n=== 최종 cat_1 분포 ===")
print(train['cat_1'].value_counts().head(10))
print(f"\n결측치 완전 제거 확인:")
print(train[['category_name','cat_1','cat_2','cat_3']].isna().sum())

카테고리 재분리 중...

=== 최종 cat_1 분포 ===
cat_1
Women                     664385
Beauty                    207828
Kids                      171689
Electronics               122690
Men                        93680
Home                       67871
Other                      51678
Vintage & Collectibles     46530
Handmade                   30842
Sports & Outdoors          25342
Name: count, dtype: int64

결측치 완전 제거 확인:
category_name    0
cat_1            0
cat_2            0
cat_3            0
dtype: int64

#### 2-3. brand_name 결측치 확인 및 처리

In [57]:
# 전체 결측치 현황 한눈에 보기
print("=== 결측치 현황 ===")
print(train.isna().sum())
print(f"\nbrand_name 결측치 수: {train['brand_name'].isna().sum()}")
print(f"전체 대비 비율: {train['brand_name'].isna().mean()*100:.2f}%")

# 결측치 샘플 확인 - 어떤 상품들인지 보기
null_category = train[train['brand_name'].isna()][
    ['name', 'cat_1', 'cat_2', 'item_description', 'price']
].sample(20, random_state=42)

print("\n=== brand_name 결측 샘플 ===")
print(null_category.to_string())

=== 결측치 현황 ===
train_id                  0
name                      0
item_condition_id         0
category_name             0
brand_name           632682
price                     0
shipping                  0
item_description          6
cat_1                     0
cat_2                     0
cat_3                     0
dtype: int64

brand_name 결측치 수: 632682
전체 대비 비율: 42.68%

=== brand_name 결측 샘플 ===
                                             name        cat_1             cat_2                                                                                                                                                                                                                                                                                                                                                                                                                                                                    item_description  price
519130                  Perfume & necklace Bundle       Beauty         Fragrance                                                                                                                                                                                                                                                                                                                                                                                                                                                                  No description yet   24.0
332821                TOMS Gray & Blue Classics 9         Kids        Boys 2T-5T  Well, I forgot that I bought these adorable TOMS for my daughter and her cousins and now they are too small. Oops! My loss is your gain - get these beauties, brand new with tags, at a great price!! Originally [rm] + shipping, these come with original box, NO shoe bag, sorry :( Size 9 classic TOMS slip ons in fun gray camo with blue soles. Size 9 best fits children around age 3-6 (depending on child's size, but please check before purchasing this is only a guide)   26.0
393861                      50 Thank you stickers     Handmade       Paper Goods                                                                                                                                                                                                                                                                                                             1" Inch Round Thank You Stickers gold with Red Heart Labels. These are the size of a quarter. The stickers are not on a roll, you will receive 8 sheets with 5 on each.    4.0
1411304                                 Eyelashes       Beauty            Makeup                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2 packages   15.0
303073                  Vera Bradley stocking (1)        Other             Other                                                                                                                                                                                                                                                                                                                                                                                                                                           Brand new full size Vera Bradley stocking   12.0
1265329                    Red & Gold Jewelry Set        Women           Jewelry                                                                                                                                                                                                                                                                                                                                                                                                            Gold plated, red beads and gems. Necklace, earrings, Tika/necklace piece    8.0
840136   The Big bang theory season 9 blu ray new  Electronics             Media                                                                                                                                                                                                                                                                                                                                                                                           The big bang theory season 9 blu ray combo brand new sealed. Check out my other listings.   20.0
1338384    Size 6.5 Women's Clark's Artisan Shoes        Women             Shoes                                                                                                                                                                                                                                                                          Not from a smoke free residence. Nice pair of shoes. I usually ship before the 4-7 day period. You can make an offer, just don't low ball. I just want to get rid of this stuff. ASK ABOUT BUNDLING STUFF!   16.0
1297417               FreeShip 1 Hookah Pen Mango        Other             Other                                                                                                                                                                                                                                This is a listing for 1 mango hookah pen. Each pen is up to 500 puffs and contains no nicotine or tobacco and is completely disposable. I have 35 other flavors and many other listings! Feel free to ask if you don't see what you are looking for.    8.0
355069                  Black Fleece Line Legging        Women  Athletic Apparel                                                                                                                                                                                                                                                         Womens Plus Size Fleece Lined Leggings Warm Thick Winter Stretch Basic SizE: L,XL,2X,3X MATERIAL 90% NYLON, 10% SPANDEX CONDITION NEW WITH TAGS LENGTH FULL Length AVAILABLE ️Color: ️Navy blue , grey, dark brown , black.   12.0
100735   TWO 2 lush bath bombs supernova pink new       Beauty       Bath & Body                                                                                                                                                                                                                                                                                                                                                                          Listing is for 2 brand new lush supernova bath bombs from the lush kitchen uk will be packed very securely   20.0
53724                             Women Hooey Hat        Women             Other                                                                                                                                                                                                                                                                                                                                                                                         Never used, perfect conditons. Colors-Grey,light blue,and pink Messege me for any question!   16.0
74435                            Forgiveness Book        Other             Books                                                                                                                                                                                                                                                                                                                                                                                                                                            Forgiveness book a memoir Chiquis Rivera    9.0
372542                              Black booties        Women             Shoes                                                                                                                                                                                                                                                                                                                                                                                                                                                  NEVER USED!!! In great condition!!   25.0
268190    LuLaRoe TC Peacock Feather Leggings NWT        Women  Athletic Apparel                                                                                                                                                                                                                                                                                                           New and never worn. Beautiful print! Message me to upgrade to Priority Shipping for an additional [rm]. I am not a consultant. Negative pricing comments will be deleted.   40.0
11540                           Chala Purse Charm        Women  Women's Handbags                                                                                                                                                                                                                                                                                                                                                                                 Chala purse charm with dragonfly, butterfly and flower. Can also be used as a key ring. New/sealed.   10.0
674405       Turtle Opal Necklace Sterling silver        Women           Jewelry                                                                                                                                                                                                                                                                                                                                                           Turtle Opal Necklace .Chain is 17" long. The pendant is 1 3/4" X 3 16" wide .Great stocking stuffer for Turtle lovers!!!!   12.0
651610       NWT Toms classic canvas shoe size 12        Women             Shoes                                                                                                                                                                                                                                                                                                                                                                                                                                                           New in box. Women size 12   36.0
739524                    XL Halter Zip up dress!        Women           Dresses                                                                                                                                                                                                                                 NWT and lightweight! Color: black with gold zipper. Size: XL Tags: Charlotte Russe Forever 21 Forever 21 plus Faith 21 Torrid H&M Vanity Urban outfitters Victoria secret Pink Papaya Agaci Hollister Abercrombie & Fitch American Eagle Outfitters   12.0
759059          One Wheel 3D Nail Art Acrylic And       Beauty            Makeup                                                                                                                                                                                                                      One small Wheel 3D Nail Art Acrylic rhinestone style Nail jewelry and 1 feather water Decals for nails. Free Shipping in USA. Feel free to touch our picture to review other items we have in our profile or virtual store. All of our items ship free in USA.    4.0

##### 2-3-2. 카테고리별 서브데이터 분리

In [56]:
# 상위 카테고리 분포 확인 : 대분류('cat_1')의 경우, 총 10개의 카테고리와 결측치(6,327건)으로 구성
top10_categories = train['cat_1'].value_counts().head(10)
print(top10_categories)

cat_1
Women                     664385
Beauty                    207828
Kids                      171689
Electronics               122690
Men                        93680
Home                       67871
Other                      51678
Vintage & Collectibles     46530
Handmade                   30842
Sports & Outdoors          25342
Name: count, dtype: int64

In [48]:
# 상위 10개 카테고리 이름 추출
top10_cat_names = train['cat_1'].value_counts().head(10).index.tolist()
print("상위 10개 카테고리:", top10_cat_names)

# 딕셔너리로 서브데이터 생성
sub_dfs = {}

for cat in top10_cat_names:
    sub_dfs[cat] = train[train['cat_1'] == cat].copy()
    print(f"{cat}: {len(sub_dfs[cat])}행")

# 상위 10개에 포함되지 않는 나머지도 보존
sub_dfs['Others'] = train[~train['cat_1'].isin(top10_cat_names)].copy()
print(f"Others: {len(sub_dfs['Others'])}행")

상위 10개 카테고리: ['Women', 'Beauty', 'Kids', 'Electronics', 'Men', 'Home', 'Other', 'Vintage & Collectibles', 'Handmade', 'Sports & Outdoors']
Women: 664385행
Beauty: 207828행
Kids: 171689행
Electronics: 122690행
Men: 93680행
Home: 67871행
Other: 51678행
Vintage & Collectibles: 46530행
Handmade: 30842행
Sports & Outdoors: 25342행
Others: 0행

In [58]:
print(train['category_name'].value_counts().head(25))

category_name
Women/Athletic Apparel/Pants, Tights, Leggings                 60177
Women/Tops & Blouses/T-Shirts                                  46380
Beauty/Makeup/Face                                             34335
Beauty/Makeup/Lips                                             29910
Electronics/Video Games & Consoles/Games                       26557
Beauty/Makeup/Eyes                                             25215
Electronics/Cell Phones & Accessories/Cases, Covers & Skins    24676
Women/Underwear/Bras                                           21274
Women/Tops & Blouses/Tank, Cami                                20284
Women/Tops & Blouses/Blouse                                    20284
Women/Dresses/Above Knee, Mini                                 20082
Women/Jewelry/Necklaces                                        19758
Women/Athletic Apparel/Shorts                                  19528
Beauty/Makeup/Makeup Palettes                                  19103
Women/Shoes/Boots                                              18864
Beauty/Fragrance/Women                                         18628
Beauty/Skin Care/Face                                          15836
Women/Women's Handbags/Shoulder Bag                            15328
Men/Tops/T-shirts                                              15108
Women/Dresses/Knee-Length                                      14770
Women/Athletic Apparel/Shirts & Tops                           14738
Women/Shoes/Sandals                                            14662
Women/Jewelry/Bracelets                                        14497
Men/Shoes/Athletic                                             14257
Kids/Toys/Dolls & Accessories                                  13957
Name: count, dtype: int64

##### 2-3-3. 대분류(cat_1) 각각 속한 브랜드 출력

In [99]:
print(train['brand_name'].value_counts().head(27))

brand_name
Unknown              119156
M                     91460
PINK                  64480
Nike                  55786
LuLaRoe               50781
Victoria's Secret     48637
All                   37460
DL                    26125
Apple                 24023
GH                    16670
Op                    15956
FOREVER 21            15555
GE                    15463
Nintendo              15132
Michael Kors          14867
Lululemon             14613
American Eagle        14059
Disney                13714
Adidas                13073
Rae Dunn              12991
Ash                   12951
Coach                 12425
Sephora               12216
Com                   11660
SO                    10998
Ice                   10870
Funko                 10821
Name: count, dtype: int64

In [67]:
print(sorted(sub_dfs['Women']['brand_name'].unique()))

['!iT Jeans', '191 Unlimited', '21men', '24/7 Comfort Apparel', '2XU', '3.1 Phillip Lim', '47 Brand', '5.11 Tactical', '525 America', '5th & Ocean', '7 For All Mankind®', '90 Degree By Reflex', 'A Bathing Ape', 'A Pea In The Pod', 'A Plus Child Supply', 'A Wish Come True', 'A&A Optical', 'A&E', 'A&R Sports', 'A+D', 'A. Byer', 'A.B.S. by Allen Schwartz', 'A.K.A', 'A.L.C.', 'A.P.C.', 'A/X Armani Exchange', 'AB Studio', 'ABS by Allen Schwartz', 'ADAM', 'AG Adriano Goldschmied', 'AGB', 'AGUADECOCO', 'AKIRA', 'ALDO', 'ALEX AND ANI', 'ALLOY', 'ALO Yoga', 'ANAMA', 'ANDREA FENZI', 'ANGL', 'ARCONA', 'ASICS', 'ASOS', 'ASSETS by Sara Blakely', 'ASTR', 'AX Paris', 'Abercrombie & Fitch', 'Acacia Swimwear', 'Acne Jeans', 'Acorn', 'Acrobat', 'Active', 'Add Down', 'Adee Kaye', 'Adidas', 'Adonna', 'Adrianna Papell', 'Adrienne Landau', 'Adrienne Vittadini', 'Aerie', 'Aero', 'Aeropostale', 'Aerosoles', 'Affliction', 'Agent Provocateur', 'Agnes & Dora', 'Agua Bendita', 'Aidan Mattox', 'Air Force', 'Air Jordan', 'Airwalk', 'Akribos XXIV', 'Akris', 'Akris punto', 'Alba', 'Albert Nipon', 'Alberto Makali', 'Alegro', 'Alex & Ava', 'Alex Evenings', 'Alex Marie', 'Alexander McQueen', 'Alexander Wang', 'Alexis Brittar', 'Alfani', 'Alfred Angelo', 'Alfred Dunner', 'Ali & Kris', 'Alia', 'Alice & Trixie', 'Alice & You', 'Alice + Olivia', 'All Saints', 'AllSaints', 'Allegra K', 'Allegri', 'Allen Allen', 'Allen B. by Allen Schwartz', 'Allison Brittney', 'Allison Daley', 'Allison Taylor', 'Allure', 'Almost Famous', 'Alo', "Altar'd State", 'Alternative', 'Alternative Apparel', 'Altra', 'Alyce Paris', 'Alyn Paige', 'Alythea', 'Amanda Smith', 'Amazon', 'Amazon Essentials', 'Ambiance Apparel', 'Ambrielle', 'American Apparel', 'American Eagle', 'American Fighter', 'American Living', 'American Needle', 'American Rag', 'American Rebel Boot Company', 'American Vintage', 'American apparel', 'Amoena', 'Anchor Blue', 'Anderson Bean', 'Andrew Marc', 'Angelina', 'Angels', 'Angie', 'Ann Marino', 'Ann Taylor', 'Ann Taylor LOFT', 'Anna Kostrova', 'Anna Sui', 'Annabelle', 'Anne Cole', 'Anne Fontaine', 'Anne Klein', 'Anne Michelle', 'Anthony', 'Anthropologie', 'Antigua', 'Antik Batik', 'Antik Denim', 'Antilia Femme', 'Antonio Melani', 'Anvil', 'Anxiety', 'Apostrophe', 'Apple', 'Apple Bottoms', 'Apt.', 'Apt. 9', 'Aqua', "Arc'teryx", 'Archaic', 'Arden B', 'Aria', 'Ariana Grande', 'Ariat', 'Aritzia', 'Ariya', 'Arizona', 'Arizona Jean Company', 'Ark & Co', 'Armani', 'Armani Collezioni', 'Armani Exchange', 'Arturo Chiang', 'As U Wish', 'Ash', 'Ashley B', 'Ashley Graham', 'Ashley Stewart', 'Aspeed', 'Assets', 'Athena', 'Athleta', 'Athletic Works', 'Atmosphere', 'Attention', 'Audrey Brooke', 'August Silk', 'Augusta Sportswear', 'Austin Reed', 'Authentic Original Vintage Style', 'Avanti', 'Avenue', 'Avia', 'Avon', 'Axcess', 'Azules', 'A|X Armani Exchange', 'Aéropostale', 'B Darlin', 'B-Low the Belt', 'B. Darlin', 'B. Moss', 'B. Smart', 'B.swim', 'BB Dakota', 'BC Footwear', 'BCBG', 'BCBG Max Azria', 'BCBGMAXAZRIA', 'BCBGeneration', 'BCBGirls', 'BCX', 'BDG', 'BEACH RIOT', 'BEARPAW', 'BISOU BISOU', 'BKE', 'BLANKNYC', 'BLANQI', 'BLOCH', 'BOGS', 'BOSS HUGO BOSS', 'BOYS + ARROWS', 'Baby Phat', 'Bacco Bucci', 'Badgley Mischka', 'Baffin', 'Bagatelle', 'Baggallini', 'Bailey', 'Bailey 44', 'Baker by Ted Baker', 'Bakers', 'Baleaf', 'Balenciaga', 'Bally', 'Balmain', 'Baltex', 'Bamboo', 'Bamboo Cay', 'Banana Republic', 'Band of Gypsies', 'Bandolino', 'Barbie', 'Barbour', 'Bare Minerals', 'Barefoot Dreams', 'Bari Jay', 'Barneys New York', 'Basic Editions', 'Bass', 'Bates', 'Bath & Body Works', 'Batman', 'BaubleBar', 'Bay Island', 'Bay Studio', 'Be Wicked!', 'BeBop', 'BeMaternity', 'Beach Bunny', 'Beach Joy', 'Beautees', 'Beautifly', 'Bebe', 'Bebe Stores', 'Becca', 'Bechamel', 'Bed Stu', 'BedHead', 'Bejeweled', 'Believe', 'Bella', 'Bella Dahl', 'Bellatrix', 'Belldini', 'Belle Du Jour', 'Belle by Sigerson Morrison', 'Belly Bandit®', 'Ben Sherman', 'Bench', 'Benefit Cosmetics', 'Benetton', 'Berek', 'Berkshire', 'Bernardo', 'Bershka', 'Bethesda Softworks', 'Betsey Johnson', 'Betsey Johnson Label', 'Betsy & Adam', 'Bettie Page', 'Betty Boop', 'Beverly Drive', 'Beverly Hills MD', 'Beyond Yoga', 'Bh', 'Bic', 'Big Buddha', 'Big Star', 'Bill Blass', 'Billabong', 'Billy Reid', 'Birkenstock', 'Bitten', 'Bjorn Borg', 'Black Halo', 'Black Poppy', 'Black Rivet', 'Blackmilk', 'Blair', 'Blanc Noir', 'Blank', 'Blank NYC', 'Blizzard', 'Blondie Nites', "Bloomingdale's", 'Blowfish', 'Blu Pepper', 'Blue Asphalt', 'Blue Cult', 'Blue Life', 'Blue Nile', 'Blush', 'Bob Mackie', 'Bobbie Brooks', 'Bobeau', 'Boden', 'Body & Hair', 'Body Central', 'Body Glove', 'Bogner', 'Boho Chic', 'Bolle', 'BonWorth', 'Bondi Band', 'Bongo', 'Bonnie Jean', 'Boohoo', 'Boohoo Petite', 'Boohoo Plus', 'Boom Boom', 'Boots', 'Boppy', 'Born', 'Boston Proper', 'Botkier', 'Bottega Veneta', 'Boulevard Boutique', 'Bourbon and Bowties', 'Boutique 9', 'Boxercraft', 'Braetan', 'Brahmin', 'Brandon Thomas', 'Brandy Melville', 'Bravado', 'BrazilRoxx', 'Breckelles', 'Breckenridge', 'Breezies', 'Briggs New York', 'Brighton', 'Brighton Collectibles', 'Brittany Black', 'Brooks', 'Brooks Brothers', 'Browning', 'Bruno Magli', 'Bubblegum', 'Bucket Feet', 'Buckle', 'Buff', 'Buffalo', 'Buffalo David Bitton', 'Buffalo Jeans', 'Bugle Boy', 'Bullhead', 'Bulova', 'Bumble and bumble', 'BumpStart', 'Burberry', 'Burberry Brit', 'Burberry London', 'Burton', 'Butterfly', 'Buxom', 'Buxton Leather Goods', 'Bvlgari', 'Byer Too', 'C by Champion', 'C&C California', 'CA by vitamin A', 'CALIA by Carrie Underwood', 'CAMPER', 'CAbi', 'CB Sports', 'CC Skye', 'CCB Collection', 'CCM', 'CJ Banks', 'CK Jeans', 'CLEAN', 'CM Style Fashion', 'COLLECTIVE CONCEPTS', 'COOGI', 'CW-X', 'Cabales', "Cabela's", 'Cabernet', 'Cabin Creek', 'Cable & Gauge', 'Cache', 'Cachet', 'Cacique', 'Cactus', 'Cali', 'California Waves', 'Call It Spring', 'Callaway', 'Calvin Klein', 'Calypso St. Barth', 'Cambio', 'Cambridge Satchel', 'Camilia', 'Camilla', 'Canada Goose', "Candie's", 'Canon', 'Canvas', 'Canyon River Blues', 'Capelli', 'Capelli of New York', 'Capezio', 'Carefree', 'Carhartt', 'Caribbean Joe', 'Carlos Santana', 'Carmen Marc Valvo', 'Carnival', 'Carol Anderson', 'Carole Hochman', 'Carole Little', 'Carolina Blues', 'Carolina Colours', 'Carolina Herrera', 'Carolyn Taylor', 'Carrera', 'Cartier', 'Carven', 'Casetify', 'Casio', 'Caslon', 'Cassandra Stone', 'Casual Corner', 'Casual Corner Annex', 'Catalina', 'Catherine Catherine Malandrino', 'Catherine Malandrino', 'Catherine Popesco', 'Catherines', 'Cathy Daniels', 'Cathy Jean', 'Cato', 'Cdc Clothing', 'Cecico', 'Celebrity Pink', 'Celine', 'Cello', 'Cello Jeans', 'Central Park West', 'Cha Cha Vente', 'Chaco', 'Chadwicks', 'Chamilia', 'Champion', 'Champion Sports', 'Chan Luu', 'Chanel', 'Changes', 'Chann Luu', 'Channel', 'Chantelle', 'Chaps', 'Charles David', 'Charles Klein', 'Charles River Apparel', 'Charlie by Mattew Zink', 'Charlotte Olympia', 'Charlotte Russe', 'CharmLeaks', 'Charming Charlie', 'Charter Club', 'Chaser', 'Chaus', 'Cheap Monday', 'Cheetah', 'Chelsea & Violet', 'Chemistry', 'Chequer', 'Cherokee', 'Chesley', 'Chic', "Chico's", "Children's Place", 'Chinese Laundry', 'Chip & Pepper', 'Chloe', 'Chloe + Isabel', 'Chloe K', 'Chloé', 'Chocolove', 'Chopard', 'Christian Audigier', 'Christian Dior', 'Christian Lacroix', 'Christian Louboutin', 'Christian Siriano', 'Christina', 'Christine Alexander', 'Christopher & Banks', 'Christopher Blue', 'Chrome Hearts', 'Circus by Sam Edelman', 'Citizen', 'Citizens of Humanity', 'Citizens of Humanity Jeans', 'Citron Santa Monica', 'City Chic', 'City Streets', 'City Studio', 'City Triangles', "Claire's", 'Clarisonic', 'Clarisse', "Clark's Botanicals", 'Clarks', 'Classic Elements', 'Classiques Entier', 'Claudia Richard', 'Cleobella', 'Clinique', 'Clinique Du Rond', 'Clio', 'Clover Canyon', 'Club Monaco', 'Coach', 'Coast', 'Coca-Cola', 'Coco Rave', 'Coco Reef', 'Cocomo', 'Code Bleu', 'Coed Sportwear', 'Coldwater Creek', 'Cole Haan', 'Colebrook', 'Colin Stuart', 'College Edition', 'Colorado Clothing', 'Columbia', 'Comfort Choice', 'Comfort Colors', 'Comme des Garcons', 'Connected', 'Context', 'Converse', 'Converse Shoes', 'Coobie', 'Cookie Lee', 'Cooperative', 'Copper Key', 'Coral Bay', 'Cordani Shoes', 'Corral', 'Corso Como', 'Cosabella', 'Costa Del Mar', 'Cotton Express', 'Cotton On', 'Coulbourne', 'Counterparts', 'Courtenay', 'Covington', 'Cowgirl Tuff', 'Crazy Horse', 'Creed', 'Crocs', 'Croft & Barrow', 'Cruel Girl', 'Crystal Doll', 'Crystal Rock', 'Cuddl Duds', 'Current/Elliott', 'Curvation', 'Curves', 'Curvy Couture', 'Custo Barcelona', 'Custom Accessories', 'Customized & Personalized', 'Cutter & Buck', 'Cynthia Howie', 'Cynthia Rowley', 'Cyrus', 'Céline', 'D&G', 'DAKS', 'DC Comics', 'DC Shoes', 'DCC', 'DIESEL', 'DKNY', 'DKNYC', 'DL', 'DV by Dolce Vita', 'Da-Nang', 'Daisy Fuentes', 'Dakine', 'Dale Of Norway', 'Dalia', 'Dan Post', 'Dana Buchman', 'Daniel Rainn', 'Daniel Wellington', 'Danielle Nicole', 'Danier', 'Danner Inc', 'Danny & Nicole', 'Danskin', 'Danskin Now', 'Dansko', 'Dave & Johnny', 'David & Goliath', 'David Brooks', 'David Kahn', 'David Yurman', "David's Bridal", 'Dawgs', 'Daytrip', 'Dazzle', 'De La Mer', 'Deb', 'Debbie Morgan', 'Decree', 'Deena & Ozzy', 'Deletta', "Delia's", 'Dell', 'Delta Burke', 'Denali', 'Denim & Co.', 'Denim & Supply Ralph Lauren', 'Denim Riders', 'Dennis Basso', 'Derek Heart', 'Derek Lam', 'Dereon', 'Design History', 'Desigual', 'Dessy Collection', 'Destination Maternity', 'Deux Lux', 'DevaCurl', 'Dex', 'Diadora', 'Diamond Plate', 'Diamond Supply Co.', 'Diane Gilman', 'Diane von Furstenberg', 'Diba', 'Dickies', 'Dior', 'Disney', 'Disney Collection', 'District', 'District Threads', 'Dittos', 'Divided', 'Dockers', 'Doe', 'Dogeared', 'Dolce & Gabana', 'Dolce & Gabbana', 'Dolce Vita', 'Dollhouse', 'Donald J. Pliner', 'Doncaster', 'Donna Bella', 'Donna Karen', 'Donna Morgan', 'Donna Ricco', 'Donnybrook', 'Dooney & Bourke', 'Dooney Bourke', 'Doris', 'Dots', 'Double Zero', 'Dr. Martens', "Dr. Scholl's", 'Dreamgirl', 'Dress Barn', 'Dsquared', 'Duck Head', 'Duluth Trading Company', 'Duo Maternity', 'Durango', 'EACH X OTHER', 'ECI', 'ECKO', 'ELF', 'ELLE', 'ENERGIE', 'EVISU', 'Earl Jean', 'Earl Jeans', 'Earnest Sewn', 'Earth’s Nectar', 'Easel', 'East 5th', 'Eastern Mountain Sports', 'Eastessence', 'Eastland', 'Easy Spirit', 'Ecco Bella', 'Ecko Red', 'Ecko Unltd.', 'Eclectic Products', 'Ecote', 'Ed Hardy', 'Eddie Bauer', 'Eddie Bauer Clothing', 'Edge', 'Eight Eight Eight', 'Eileen Fisher', 'Elan', 'Electric Family', 'Elegant Moments', 'Element', 'Elementz', 'Elemis Ltd', 'Elevenses', 'Elie Tahari', 'Eliza J', 'Elizabeth Arden', 'Elizabeth Hurley', 'Elizabeth and James', 'Ella Moss', 'Ellemenno', 'Ellen Tracy', 'Elliott Lucca', 'Ellison', 'Elmers', 'Elomi', 'Eloquii', 'Emanuel Ungaro', 'Emerald Sundae', 'Emilio Pucci', 'Emily Ray', 'Emma Fox', 'Emma James', 'Empire', 'Emu', 'En Focus Studio', 'Endless Rose', 'English Factory', 'Enyce', 'Enzo Angiolini', 'Equipment', 'Eric Javits', 'Erika', 'Escada', 'Escante', 'Esley', 'Esprit', 'Essentials', 'Essentials by Milano', 'Essie', 'Estee Lauder', 'Etcetera', 'Etienne Aigner', 'Etonic', 'Evan Picone', 'Ever-Pretty', 'Everlane', 'Everlast', 'Everly', 'Everly Grey', 'Evie', 'ExOfficio', 'Express', 'Express, Inc.', 'Expressions', 'Eyeshadow', 'FABRIZIO GIANNI', 'FELICITY & COCO', 'FIONI Clothing', 'FOREVER 21', 'FUBU', 'FUBU Apparel', 'FULL TILT', 'Fabletics', 'Faded Glory', 'Fairway', 'Faithfull the Brand', 'Falls Creek', 'Famous Catalog', 'Famous Stars & Straps', 'Fang', 'Fantasie', 'Fascinations', 'Fashion Bug', 'Fashion Forms', 'Fashion Junkee', 'Fashion Nova', 'Fashion to Figure', 'Fashionomics', 'Faviana', 'Feetures!', 'Fender', 'Fendi', 'Fenn Wright Manson', 'Fergalicious', 'Fergie', 'Ferragamo', 'Fever', 'Fiesta', 'Fifth Sun', 'Fila', 'Fila Sport', 'Finders Keepers', 'Finish Line', 'Fiore', 'Fiorentini + Baker', 'Fire Los Angeles', 'Fitbit', 'Fjallraven', 'Flamingo', 'Flax', 'Flexees', 'Flirtitude', 'Fluxus', 'Fly London', 'Flying Monkey', 'Flying Tomato', 'Flynn Skye', 'Foley + Corinna', 'Foot Locker', 'Foot Traffic', 'For Joseph', 'For Love and Lemons', 'Forecaster of Boston', 'Foreign Exchange', 'Forever Unique', 'Forplay', 'Fossil', 'Foster Grant', 'Fox', 'Fox Racing', 'Foxcroft', 'Frame Denim', "Francesca's Collections", 'Francesco Biasia', 'Franco Sarto', 'Frank & Oak', 'Frankie B', "Frankie's Bikinis", 'Freddy', "Frederick's of Hollywood", 'Free Country', 'Free People', 'Freestyle', 'French Connection', 'French Laundry', 'Fresh', 'Fresh Produce', 'Freshman', 'Freya', 'Fruit of the Loom', 'Frye', 'Fuda', 'Funimation Production', 'Funko', 'Funtasma', 'Furla', 'G by Guess', 'G-III', 'G-Shock', 'G-Unit', 'GAIAM', 'GBX', 'GEIGER', 'GH', 'GUESS', 'GX by Gwen Stefani', 'Galaxy', 'Gallery', 'Gap', 'Gap Inc.', 'Garage', 'Garfield & Marks', 'Garnet Hill', 'Gear', 'GenOne', 'Generic', 'Generra', 'Genetic Denim', 'Geneva', 'Geneva Platinum', 'Gentle Souls', 'Geoffrey Beene', 'George', 'George Simonton', 'Georgia Boot', 'Georgiou', 'Ghost', 'Giacca', 'Giani Bernini', 'Gianni Bini', 'Gibson', 'Gildan', "Gilligan & O'Malley", 'Gilly Hicks', 'Giorgio Armani', 'Gitano', 'Giuseppe Zanotti', 'Givenchy', 'Glamglow', 'Glamorise', 'Glo', 'Glo Clothing', 'Glo Jeans', 'Gloria Vanderbilt', 'Goddess', 'Goodie Two Sleeves', 'Goody', 'Gossard', 'Gossip Girl', 'Gotta Flurt', 'Gottex', 'Goyard', 'Grace', 'Grace Elements', 'Grace In LA', 'Grace Karin', 'Gracia', 'Graham & Spencer', 'Grane', 'Great Expectations', 'Green Apple', 'Greg Norman', 'Grreat Choice', 'Gucci', 'Guess by Marciano', 'Gunne Sax', 'Guy Harvey', 'Gymshark', 'Gypsy', 'Gypsy 05', 'H&M', 'HDE', 'HEAD', 'HERMES', 'HOBO INTERNATIONAL', 'HOT MILK', 'HUF', 'HYDRAULIC', 'Haband', 'Hailey Logan', 'Hale Bob', 'Hallmark', 'Halo', 'Halogen', 'Halston', 'Halston Heritage', 'Hamilton', 'Hammer', 'Hampshire Studio', 'Hanes', 'Hang Ten', 'Hanky Panky', 'Happy Socks', 'Harajuku Lovers', 'Hard Candy', 'Hard Candy Cosmetics', 'Hard Tail', 'Harley-Davidson', 'Harlowe and Graham', 'Harmont & Blaine', "Harold's", 'Harve Benard', "Harvey's Seatbelt Bag", 'Haute Hippie', 'Havaianas', 'Hazel', 'Heart Soul', 'HeartSoul', 'Heelys', 'Hello Kitty', 'Helly Hansen', 'Helmut Lang', 'Henri Bendel', 'Heritage', 'Heritage 1981', 'Hermès', 'Herschel Supply Company', 'Herve Leger', 'Hi-Tec', 'High Sierra', 'Highway Jeans', 'Hilfiger Denim', 'Hillard & Hanson', 'Hind', 'Hint', 'Hipanema', 'Hippie', 'Hippie Rose', 'HoMedics', 'Hobie', 'Hoka One', 'Holden', 'Hollister', 'Hollister Co.', 'Holloway', 'Home-it', 'Honey Punch', 'Honeydew Intimates', 'Honora', 'Horny Toad', 'Hot Chillys', 'Hot Kiss', 'Hot Sox', 'Hot Topic', 'Hourglass', 'House of Harlow 1960', 'Hublot', 'Hudson', 'Hudson Jeans', 'Hue', 'Hula Honey', 'Hunter', 'Hunter Boots', 'Hurley', 'Hush Puppies', 'Hype', 'I Heart Ronson', 'IKEA', 'IMAN', 'INC International Concepts', 'IRO', 'ISIS', 'IZOD', 'Ice', 'Ice Clothing', 'Icebreaker', 'Icon', 'Ideology', 'Illesteva', 'Imperial Motion', 'Impressions', 'In Bloom by Jonquil', 'Inc', 'Indah', 'Independent', 'Indigo Brands', 'Indigo Moon', 'Indigo Palms', 'Industrial Cotton', 'Infinity', 'Infinity Raine', 'Ingrid & Isabel', 'Inspire', 'Intrigue', 'Investments', 'Invicta', 'Invicta Watch Group', 'Iris', 'Iron Fist', 'Iron Man', 'Isaac Mizrahi', 'Isabel Marant', 'Isabella Oliver', 'Isabella Rodriguez', 'Island Escape', "Issa de' mar", 'Issey Miyake', 'It Figures', "It's Our Time", 'Ivanka Trump', 'Ivivva', 'Ivory Ella', 'Ivy & Blu', 'Iz Byer', 'J & Company', 'J Brand', 'J G Hook', 'J Kara', 'J Workshop', 'J. America', 'J. Crew', 'J. Jill', 'J. McLaughlin', 'J.Crew', 'J.Lo by Jennifer Lopez', 'JAG', 'JCPenney', 'JERZEES', 'JM Collection', 'JS Boutique', 'JS Collections', 'JTB', 'Jac Vanek', 'Jack Rogers', 'Jack by BB Dakota', 'Jaclyn Smith', 'Jacqueline Ferrar', 'Jade', 'Jag Jeans', 'Jagermeister', 'Jamaica Bay', 'Jamberry', 'Jambu', 'James Avery', 'James Jeans', 'James Perse', 'Jamie Sadock', 'Jams World', 'JanSport', 'Jane Ashley', 'Jantzen', 'Jason Maxwell', 'Jason Wu', 'Jean Paul Gaultier', 'Jeanne Pierre', 'Jeffery Campbell', 'Jeffrey Campbell', "Jen's Pirate Booty", 'Jenni by Jennifer Moore', 'Jennifer Lopez', 'Jennifer Moore', 'Jenny Yoo', 'Jeremy Scott x Adidas', 'Jessica Howard', 'Jessica McClintock', 'Jessica Simpson', 'Jezebel', 'Jil Sander', 'Jimmy Choo', 'Joan & David', 'Joan Rivers', 'Jockey', 'Jodi Kristopher', 'Joe & Elle', 'Joe Benbasset', 'Joe Fresh', "Joe's Jeans", 'John Hardy', 'John Meyer', 'John Paul Richard', 'John Roberts', 'Johnny Martin', 'Johnny Was', 'Joie', 'Jollychic.com', 'Jolt', 'Jolyn Clothing', 'Jonathan Martin', 'Jones Jeans', 'Jones New York', 'Jones Sport', 'Jordache', 'Jordan', 'Jordans', 'Josef Seibel', 'Joseph A', 'Joseph Ribkoff', 'Josephine Chaus', 'Josie', 'Josie Natori', 'Jostar', 'Jou Jou', 'Joujou', 'Joules', 'Journee Collection', 'Jovani', 'Joyce Leslie', 'Joyfolie', 'Judith March', 'Juicy Couture', 'Julie Brown', 'Jump Apparel', 'Junk Food', 'Junk Food Clothing', 'Just Cavalli', 'Just Love', 'Just My Size', 'Just USA', 'JustFab', 'Justice', 'Justin', 'Justin Boots', 'K&N Engineering', 'K-SWISS', 'K. Bell', 'KEEN', 'KIINI', 'KUT from the Kloth', 'Kae Argatherapie', 'Kaii', 'Kangol', 'Kardashian Kollection', 'Karen Kane', 'Karen Millen', 'Karen Neuburger', 'Karen Scott', 'Karl Lagerfeld', 'Karma', 'Kasper', 'Kat Von D Beauty', 'Kate Hill', 'Kate Landry', 'Kate Spade', 'Kathie Lee', 'Kathy Lee', 'Kathy Van Zeeland', 'Katia', 'Katie B.', 'Katydid', 'Kay Jewelers', 'Kay Unger', 'Kc Collections', 'Keds', 'Keepsake the Label', 'Kelly & Katie', 'Kelsi Dagger', 'Kenar', 'Kendall & Kylie', 'Kendra Scott', 'Kenneth Cole', 'Kenneth Cole New York', 'Kenneth Cole Reaction', 'Kenneth Jay Lane', 'Kensie', 'Kenzo', 'Kerusso', 'Kickee Pants', 'Kikit', 'Kim Rogers', 'Kimchi Blue', 'King Baby Studio', 'Kingston', 'Kipling', 'Kiplling', 'Kirra', 'Kische', 'Kiyonna', 'Koh Koh', 'Kooba', 'Koret', 'Kork-Ease', 'Krazy Kat', 'Krista Lee', 'Kristen Blake', 'Krush', 'Kylie Cosmetics', 'Kyodan', "L'eggs", 'L*SPACE', 'L.A. Blues', 'L.A. Gear', 'L.A.M.B.', 'L.L. Bean', 'LA Hearts', 'LA Idol', 'LA Splash', 'LAT', 'LAmade', 'LC Lauren Conrad', 'LF', 'LK Bennett', 'LOFT', 'LRG', 'La Blanca', 'La Femme', 'La Girl', 'La Perla', 'La Redoute', 'La Senza', 'La Sportiv', 'LaMarque', 'LaROK', 'Lacoste', 'Lady Hagen', 'Lady Noiz', 'Lafayette  New York', 'Lafayette 148 New York', 'Laguna Beach Jeans', 'Lamaze', 'Lancôme', 'Landau', "Lands' End", 'Lane Bryant', 'Lansinoh', 'Lanvin', 'Lapis', 'Laredo', 'Larry Levine', 'Last Kiss', 'Latique', 'Laundry by Design', 'Laundry by Shelli Segal', 'Laura Ashley', 'Laura Scott', 'Laurel Burch', 'Lauren Conrad', 'Lauren Moshi', 'Lauren Ralph Lauren', 'LawMan', 'Lazy Oaf', 'Le Mystere', 'Le Suit', 'LeSportsac', 'Leading Lady', 'Leather Gallery', 'Lee', 'Leith', 'Lela Rose', 'Lennie for Nina Leonard', 'Leota', 'Leslie Fay', 'Letarte', 'Level', 'Levi Strauss & Co.', "Levi's®", 'Lia Sophia', 'Liberty of London', 'Liebeskind', 'Life Is Good', 'Life Stride', 'LifeProof', 'Liliana', 'Lilli Ann', 'Lillie Rubin', 'Lilly Pulitzer', 'Lilly Pulitzer for Target', 'Lilu', 'Lily Rose', 'Lily White', 'Lilyette', 'Limited Too', 'Linea Donatella', 'Linea Pelle', 'Lip Service', 'LipSense', 'Lipstick Bandit', 'Lipstick Boutique', 'Lipsy', 'Lisa Maree', 'Little Mistress', 'Live a Little', 'Liverpool Jeans Company', 'Living Dead Souls', 'Livinglibations', 'Liz & Co.', 'Liz Baker', 'Liz Claiborne', 'Liz Lange', 'Liz Lange for Target', 'Lodis', 'Loeffler Randall', 'Loewe', 'Lojas Riachuelo', 'Lokai', 'Lola', 'Lole', 'Lolita', 'Lolli swim', 'Lolly Wolly Doodle', 'London Fog', 'London Jeans', 'London Times', 'Longchamp', 'Longchamp Paris', 'Longines', 'Longitude', 'Looney Tunes', 'Lord & Taylor', 'Lorna Jane', 'Lou & Grey', 'Louis Vuitton', 'Loungefly', 'Love By Design', 'Love Culture', 'Love Moschino', 'Love Riche', 'Love Stitch', 'Loveappella', 'Lovers + Friends', 'LuLaRoe', 'Luca Luca', 'Lucca', 'Lucca Cou

In [68]:
print(sorted(sub_dfs['Beauty']['brand_name'].unique()))

['% Pure', 'A Wish Come True', 'A. Byer', 'AERIN', 'Abercrombie & Fitch', 'Acure', 'Adidas', 'Air Wick', 'Alexandra de Markoff', 'Algenist', 'Almay', 'Amazon', 'Ambi', 'American Eagle', 'Anastasia Beverly Hills', 'Andis', 'Anthropologie', 'Apple', 'Arbonne', 'Ardell', 'Ariana Grande', 'Artist Couture', 'As Seen on TV', 'Aussie', 'Australian Gold', 'Aveda', 'Aveeno', 'Avon', 'Axe', 'Azzaro', 'BH Cosmetics', 'Baby Phat', 'Balmain', 'Banana Boat', 'Bare Escentuals', 'Bare Minerals', 'Bareminerals', 'Bass', 'Bath & Body Works', 'BeautiControl', 'Beautycounter', 'Bebe', 'Becca', 'Becca Cosmetics', 'BedHead', 'Befine', 'Belif', 'Ben Nye', 'Benefit', 'Benefit Cosmetics', 'Better Shea Butter', 'Bh', 'Bio Oil', 'Biore', 'Bite Beauty', 'Blinc', 'Blink', 'Bliss', 'Bobbi Brown', 'Bonne Bell', 'Borghese', 'Boscia', 'Bourjois', 'Braun', 'Briogeo', 'Brut', 'Bumble and bumble', 'Burberry', 'Burberry London', "Burt's Bees", 'Buxom', 'Bvlgari', 'By Terry', 'Bésame Cosmetics', 'C. O. Bigelow', 'CHI', 'CIOR', 'CLEAN', 'CND', 'Calgon', 'California Scents', 'Calvin Klein', "Candie's", 'Cargo', "Carol's Daughter", 'Carolina Herrera', 'Cartier', 'Caruso', 'Cato', 'Caudalie', 'CeraVe', 'Cetaphil', 'Chanel', 'Chapstick', 'Charlotte Tilbury', 'Charming Charlie', 'Chi', "Children's Place", 'China Glaze Co. Ltd.', 'Chloe', 'Christian Dior', 'Christian Siriano', 'Christophe Robin', 'Ciaté London', "Claire's", 'Clairol', 'Clarins', 'Clarisonic', 'Clean & Clear', 'Clearasil', 'Clinique', 'Coach', 'Color Oops', 'ColourPop', 'ColourPop Cosmetics', 'Colourpop', 'Comptoir Sud Pacifique', 'Conair', 'Converse', 'Coola', 'Coty', 'Coty, Inc.', 'Cover Fx', 'Cover Girl', 'CoverGirl', 'Crabtree & Evelyn', 'Creed', 'Crest', 'Curve', 'DDF', 'DIESEL', 'DKNY', 'DUO', 'Dell', 'Dermablend', 'Dermal', 'DevaCurl', 'Dial', 'Dior', 'Disney', 'Dolce & Gabana', 'Dolce & Gabbana', 'Donna Karen', 'Dove', 'Dr. Brandt', 'Dr. Dennis Gross Skincare', 'Dr. Hauschka', "Dr. Scholl's", "Dr. Teal's", 'Drunk Elephant', 'Drybar', 'DuWop', 'ELF', 'Ecotools', 'Ed Hardy', 'Elie Saab', 'Elizabeth Arden', 'Elizabeth and James', 'Elizavecca', 'Eminence', 'Emporio Armani', 'Escada', 'Essence of Beauty', 'Essie', 'Estee Lauder', 'Exuviance', 'Farmacy', 'Farsali', 'Fashion Fair', 'Fendi', 'Ferasali', 'Ferrari', 'Fila', 'First Aid Beauty', 'Foreo', 'Fresh', 'Gap', 'Garnier', 'Gelish', 'Georgio Armani', 'GiGi New York', 'Giorgio Armani', 'Givenchy', 'Glamglow', 'GloMinerals', 'Glossier', 'Goody', 'Got 2B', 'Gucci', 'Guerlain', 'H&M', 'HERMES', 'Harajuku Lovers', 'Hard Candy', 'Head & Shoulders', 'Hello Kitty', 'Herbal Essences', 'Hikari', 'HoMedics', 'Hollister', 'Hot Topic', 'Hourglass Cosmetics', 'Huda Beauty', 'I LOVE NEW YORK by Bond No. 9', 'IT Cosmetics', 'Illamasqua', 'Illuminations', 'Inglot', 'Inner Beauty', 'Instantly Ageless', 'Irish Spring', 'Issey Miyake', 'Jafra', 'Jamberry', 'Jane Iredale', 'Jeffree Star', 'Jeffree Star Cosmetics', 'Jergens', 'Jessica Simpson', 'Jimmy Choo', 'Jo Malone', 'John Frieda', 'John Varvatos', 'Joico', 'Jordan', 'Josie Maran', 'Juicy Couture', 'Julep', 'Juliette Has a Gun', 'KIKO MILANO', 'KMS California', 'KVD', 'Kailijumei Lipsticks', 'Kanebo', 'Kat Von D', 'Kat Von D Beauty', 'Kate Somerville', 'Kate Spade', 'Kenneth Cole', 'Kenra', 'Kenzo', 'Keranique', "Kiehl's", 'Kirkland Signature', 'Kiss Me', 'Kiss My Face', 'Klorane', 'Kopari', 'Korres', 'Kryolan', 'Kylie Cosmetics', "L'Oreal", 'LOreal', 'La Girl', 'La Prairie', 'La Roche-Posay', 'Lacoste', 'Lancome', 'Lancôme', 'Laura Geller', 'Laura Mercier', 'Lauren Ralph Lauren', 'Lilly Pulitzer', 'Lime Crime', 'Lime Crime Cosmetics', 'LipSense', 'Lipstick Queen', 'Lola', 'Lorac', 'Lord & Taylor', 'Loungefly', 'LuLaRoe', 'Lush', 'Lush Clothing', 'L’Occitane', 'M', 'MAC', 'MAC Cosmetics', 'MAKE UP FOR EVER', 'MARC JACOBS', 'MATRIX', 'MILK MAKEUP', 'MIU MIU', 'Mac Cosmetic', 'Madam C.J. Walker Beauty Culture', 'Maison Margiela', 'Makeup Eraser', 'Makeup Forever', 'Makeup Geek', 'Mally Beauty', 'Manic Panic', 'Mario Badescu Skin Care', 'Mary Kay', 'Max Factor', 'Maybelline', 'Maybelline New York', 'Mederma', 'Mehron', 'Melt Cosmetics', 'Meme', 'Merle Norman', 'Mermaid Maternity', 'Michael Kors', 'Milani', 'Milani Cosmetics', 'Moda International', 'Moroccanoil', 'Morphe', 'Morphe Cosmetics', 'Moschino', 'Murad', 'Mustela', 'NARS', 'NEXXUS', 'NUDESTIX', 'NYC', 'NYX', 'NYX Cosmetics', 'Nair', 'Narciso Rodriguez', 'Nars', 'Natasha Denona', 'Nest', 'Neutrogena', 'New York Color', 'Nike', 'Nina Ricci', 'Nivea', 'No7 Make-up', 'North Face', 'Nostalgia', "Not Your Mother's", 'Nubian Heritage', 'OGX', 'OPI', 'Obagi', 'Ofra', 'Olaplex', 'Olay', 'Old Spice', 'Ole Henricksen', 'Organic Wear', 'Origins', 'Orly', 'Oscar de la Renta', 'Ouai', 'Ouidad', 'PCA Skin', 'PINK', "POND'S", 'PUR', 'Pacific World Corp', 'Paco Rabanne', "Palmer's", 'Pantene', 'Paul Mitchell', 'Peripera', 'Perricone MD', 'Perry Ellis', 'Peter Thomas Roth', 'Philosophy', 'Physicians Formula', 'Pink Sugar', 'Pixi', 'Pokemon', 'Polo Ralph Lauren', 'Pop Beauty', 'Prada', 'Pravana', 'Prescriptives', 'Proactiv', 'Pur Minerals', 'Pur-lisse', 'Pureology', 'REN', 'Ralph Lauren', 'Ralph Lauren Collection', 'Real Techniques', 'Red Cherry', 'Redken', 'Remington', 'Revlon', 'Revolution', 'Rimmel', 'RoC', 'Rodan and Fields', 'Rue21', 'Rusk', 'SEPHORA COLLECTION', 'SK-II', 'Sally Hansen', 'Salvatore Ferragamo', 'Sante', 'Sassy', 'Scentsy', 'Schick', 'Schmidt', 'Schwarzkopf', 'Sebastian', 'Sebastian Professional', 'SeneGence', 'Sephora', 'Seraphine', 'Serious Skin Care', 'Shany', 'Sharper Image', 'Shea Moisture', 'Sheer Cover', 'Shiseido', 'Shu Uemura', 'Simple', 'Sinful', 'Skin Laundry', 'SkinCeuticals', 'Sky Organics', 'Slatkin & Co.', 'Sleek MakeUP', 'Slime®', 'Smashbox', 'Smashbox Cosmetics', 'Sol de Janeiro', 'Sonia Kashuk', 'Sophia', 'Sparks', 'Splat', 'St. Tropez Tanning Essentials', 'Stila', 'Stila Cosmetics', 'StriVectin', 'Styli-Style', 'Suave', 'Sue Devitt', 'Sugarpill', 'Sultra', 'Sunday Riley', 'Supreme', 'TIGI', 'TOCCA', 'TOMS', 'TRESemme', 'Tangle Teezer', 'Target', 'Tarte', 'Tatcha', 'The Balm', 'The Body Shop', 'The Wet Brush', 'Thierry Mugler', 'Thrive', 'Tom Ford', 'Tommy Bahama', 'Tommy Hilfiger', 'Tone', 'Tony & Tina', 'Tony Moly', 'Too Faced', 'Tory Burch', 'Tria', 'Trish McEvoy', 'Tweezerman', 'Tyra Beauty', 'UGG Australia', 'Ulta', 'Ultima II', 'Ultra', 'Under Armour', 'Unknown', 'Urban Decay', 'Urban Outfitters', 'Va Va Voom', 'Vanity', 'Vans', 'Vaseline', 'Vera Wang', 'Versace', 'Vichy', 'Victoria secret', "Victoria's Secret", 'Vidal Sassoon', 'Viktor & Rolf', 'Vince Camuto', 'Vincent Longo', 'Viseart', 'Viviscal', 'Wahl', 'Wella', 'Wet n Wild', 'Whish', 'White Diamond', 'Wish', 'XEN-TAN', 'YSL Yves Saint Laurent', 'Yankee Candle', 'Yankee Candle Company', 'Yes To', 'Yeti', 'Youngblood', 'Younique', 'Younique products', 'Youth To The People', 'Yves Saint Laurent', 'ZARA', 'Zara', 'Zen Group', 'Zoya', 'amika', 'bareMinerals', 'beautyblender®', 'butter LONDON', 'deborah lippmann', 'doTERRA', 'e.l.f', 'e.l.f.', 'eos', 'juicy couture', 'rue', 'theBalm']

In [69]:
print(sorted(sub_dfs['Kids']['brand_name'].unique()))

['A Bathing Ape', 'A Plus Child Supply', 'A Wish Come True', 'A+D', 'A-Shirt', 'A.D. Sutton & Sons', 'ABC Studios', 'AKA New York', 'ART', 'ASICS', 'ASUS', 'Abercrombie & Fitch', 'Accessory Innovations', 'Accessory Workshop', 'Activision', 'Adidas', 'Adora', 'Aero', 'Aeropostale', 'Affliction', 'Agetec', 'Air Hogs', 'Air Jordan', 'Air Zone', 'Akai', 'Alex Toys', 'All', 'Amazon', 'Ameda', 'American Boy & Girl', 'American Girl ®', 'American apparel', 'Angelcare', 'Angry Birds', 'Animal Adventure', 'Animal Alley', 'Animal Planet', 'Anita', 'Antique Rivet', 'Apple', 'Aquaphor', 'Aquarius', 'Aquatopia', 'Ariat', 'Arizona', 'Arizona Jean Company', 'Arm & Hammer', "Arm's Reach Concepts", 'Armani', 'As Seen on TV', 'Aspeed', 'Atari', 'Athletech', 'Athletic Works', 'Atlantis Toy and Hobby', 'Aurora World', 'Aveeno', 'Avent', 'Avon', 'B is for Bear', 'BOB Strollers', 'BOGS', 'BOOMco.', 'Babies R Us', 'Babies R Us Infant', 'Babies R Us Plush', 'Baby Aspen', 'Baby Boom', 'Baby Brezza', 'Baby Bullet', 'Baby Delight', 'Baby Einstein', 'Baby Essentials', 'Baby Gear', 'Baby Jogger', 'Baby Legs', 'Baby Magic', 'Baby Phat', 'Baby Trend', 'Baby connection', 'BabyBjorn', 'BabyGanics', 'Babyhome', 'Bacati', 'Bachmann Trains', 'Back Buddy', 'Badger Basket', 'Balboa Baby', 'Bambo Nature', 'Bamboobies', 'Bananafish', 'Bandai', 'Bandai Namco', 'Banzai', 'Barbie', 'Basic Fun', 'Bass', 'Bassett Furniture', 'Batman', 'Beaba', 'Bebe', 'Bebe Au Lait', 'BebeSounds', 'Beechnut', 'Begin Again', 'Belly Bandit®', 'Bepuzzled', 'Bethesda Softworks', 'Betsey Johnson', 'Big Time Toys', 'Billabong', 'Birkenstock', 'Blip Toys', 'Blizzard', 'Blooming Bath', 'Blowfish', 'Blue Bird', 'Blue Box', 'Bobbie Brooks', 'Bon Bebe', 'Bonnie Baby', 'Bonnie Jean', 'Boo!', 'Boogie Wipes', 'BooginHead', 'Boon', 'Boppy', 'BornFree', 'Borrelli', 'Boudreauxs Butt Paste', 'Brandy Melville', 'Braun', 'Bravado Designs', 'BreathableBaby', 'Breyer', 'Briarpatch', 'Brica', 'Bright Starts', 'Britax', 'Brooks', 'Brooks Brothers', 'Brother', 'Bruder Toys America', 'Buffalo Games', 'Bugaboo', 'Bumble Collection', 'Bumbleride', 'Bumbo', 'Bumkins', 'Burberry', "Burt's Bees", "Burt's Bees Baby", 'CW-X', 'Calico Critters', 'California Baby', 'California Costume Collection', 'Calvin Klein', 'Cambridge Classics', 'CamelBak', 'Capcom', 'Capezio', 'Cardinal Industries', 'Cards Against Humanity', 'Carhartt', "Carter's", 'Carters', 'Cartoon Network', 'Casio', 'Caterpillar', 'Ceaco', 'Cepia', 'CeraVe', 'Chaco', 'Champion', 'Chaps', 'Charlie Banana', 'Cherokee', 'Chicago', 'Chicco', 'Children Place', "Children's Place", 'Chloe', 'Chronicle Books', 'Circo', 'City Chic', 'Clarks', 'Classic Media', 'Cloud B', 'CoCaLo', 'Coach', 'Colgate', 'Colorbok', 'Columbia', 'Combi', 'Comfort & Harmony', 'Commonwealth Toys', 'Comotomo', 'Concept One', 'Contigo', 'Contours', 'Converse', 'Converse Shoes', 'Coogi Fashions', 'Copper Key', 'Corolle', 'Cosco', 'Costume Super Center', 'Cra-Z-Art', 'Crane', 'Crayola', 'Creative Designs', 'Creativity for Kids', 'Crest', 'Crocs', 'Cuddl Duds', 'Customized & Personalized', 'Cutie Pie Baby', 'Cynthia Rowley', 'DC Comics', 'DC Direct', 'DC Shoes', 'DJI', 'DKNY', 'Dakine', 'Danskin', 'Dark Horse', 'Daytrip', 'Delta', 'Desitin', 'Dex Baby', 'Diadora', 'Diamond', 'Diamond Select', 'Diaper Dude', 'Diaper Genie', 'Dickies', 'Diono', 'Dior', 'Discovery Kids', 'Disguise', 'Disney', 'Disney Baby', 'Disney Collection', 'Disney Interactive', 'Disney Jr.', 'Disney Pixar', 'Disney Pixar Cars', 'Disney Pixar Planes', 'Disney Press', 'Disney Princess', 'Disney Tsum Tsum', 'Diva', 'Dolce Vita', 'Dollhouse', 'Dollie & Me', 'Dora the Explorer', 'Dorel', 'Dots', 'Douglas', 'Dove', "Dr. Brown's", 'Dr. Martens', 'Dr. Seuss', 'Dream Lites', 'Dream On Me', 'Dreamworks', 'Dreamworks Animated', 'Duncan Toys', 'Earth Mama Angel Baby', "Earth's Best", 'Eddie Bauer', 'Edu Science', 'Educational Insights', 'Elf on the Shelf', 'Elmers', 'Emile et Rose', 'Enesco', 'Enfagrow', 'Enfamil', 'Epic Threads', 'Eric Carle', 'Especially For Kids', 'Especially for Baby', 'Estes', 'Etch A Sketch', 'Eucerin', 'Evenflo', 'Evriholder', 'ExerSaucer', 'Exergen', 'FAO Schwarz', 'Faber-Castell', 'Faded Glory', 'Falls Creek', 'Famosa America', 'Fashion Angels', 'Fast Lane', 'Ferrari', 'Fila', 'Fila Sport', 'First Impressions', 'First Wave', 'Fisher Price', 'Fisher-Price', 'Fisher-Price Baby', 'Flip', 'Floam', 'Floppy Products', 'Florsheim', 'Folkmanis', 'Fox Racing', 'Franklin Learning Systems', 'Free Country', 'French Toast', 'Freshly Picked', 'Fruit of the Loom', 'Fun World', 'Funimation Production', 'Funko', 'Funrise', 'G.I. JOE', 'GAME', 'GUESS', 'GUM', 'Gabriel', 'Galt', 'Ganz', 'Gap', 'Gateway', 'Gentle Giant', 'GeoTrax', 'George', 'Gerber', 'Gerber Childrenswear', 'Gerber Foods', 'Gerber Good Start', 'Gigatent', 'Gildan', 'Ginsey', 'Glide Bikes', 'Global Holdings', 'Gold Bug', 'Goldberger Co', 'GoldieBlox', 'Goliath Games', 'Graco', 'Green Toys', 'Greenleaf Dollhouses', 'Greenlight Collectibles', 'Groovy Toys', 'Gucci', 'Guidecraft', 'Gund', 'Guy Harvey', 'Gymboree', 'H&M', 'HP', 'Halo', 'Hanes', 'Hanna Anderson', 'Hanna Andersson', 'Hape', 'Happy Chic Baby by Jonathan Adler', 'Harley-Davidson', 'Hartstrings', 'Hasbro', 'Hasbro Games', 'Hauck', 'Hawke & Co', 'Hedstrom', 'Heelys', 'Helix', 'Hello Kitty', 'Hershey', 'High Sierra', 'HoMedics', 'Hollister', 'Home Depot', 'Horizon Organic', 'Hot Topic', 'Hot Wheels', 'Hoverboard', 'Hudson Baby', 'Huffy', 'Hugga Bebe', 'Huggies', 'Huggies Goodnites', 'Huggies Little Movers', 'Huggies Little Snugglers', 'Huggies Little Swimmers', 'Huggies One & Done', 'Huggies Pull-Ups', 'Huggies Snug & Dry', 'Hunter', 'Hunter Boots', 'Hurley', 'Hush Puppies', "Hyland's", 'I-Play', 'IKEA', 'IZOD', 'Illuminations', 'Imaginarium', 'Imagine', 'Imagine Baby', 'Imaginext', 'Imperial', 'InCharacter Costumes', 'Infantino', 'Ingenuity', 'Inglesina', 'Intex', 'Iris', 'Itzy Ritzy', 'Ivanka Trump', 'Ivivva', 'J&L', 'JC Toys', 'JCPenney', 'JJ Cole Collections', 'Jada Toys', 'Jakks Pacific', 'JanSport', 'Janie Jack', 'Janie and Jack', 'Jay at Play', 'Jazwares', 'Jeep', 'Jelly Belly', 'Jessica Simpson', 'Jinx', 'John Deere', 'Johnson & Johnson', 'Jonesport', 'Joovy', 'Jordache', 'Jordan', 'Jordans', 'Journey Girls', 'Joyfolie', 'JuJu', 'Juicy Couture', 'Jumping Beans', 'Jun Planning', 'Just Born', 'Just Like Home', 'Just Play', 'Justice', 'Justin Boots', "K'NEX", 'K-SWISS', 'KEEN', 'KRE-O', 'Kalencom', 'Kanga Care', 'Kate Aspen', 'Kawasaki', 'Keds', 'Keekaroo', 'Kelty', 'Kenneth Cole', 'Kensie', 'Kickee Pants', 'Kid Galaxy', 'KidCo', 'KidKraft', 'Kids Headquarters', 'Kids Only', 'Kids Preferred', 'Kidsline', 'Kiinde', 'KinderGlo', 'Klutz', 'Koala Baby', 'Koala Baby Boutique', 'Koala Kids', 'Kolcraft', 'Konami', 'Kurio', 'L.L. Bean', 'LEGO', 'LOL Surprise', 'Lalaloopsy', 'Lamaze', 'Lambs & Ivy', "Lands' End", 'Lansinoh', 'Laura Ashley', 'Leachco', 'Leap Frog', 'Learning Curve', 'Learning Resources', 'Lee', 'Levana', "Levi's®", 'Lil Critters', "Lil' Joey", 'Lilly Pulitzer for Target', 'Limited Too', 'Lincoln Logs', 'Lionel', 'Lite Brix', 'Little Lass', 'Little Me', 'Little Me Childrens Wear', 'Little Pim', 'Little Tikes', 'Littlest Pet Shop', 'London Fog', 'Loungefly', 'LuLaRoe', 'Lucky Brand', 'Lullaby Earth', 'LulyBoo', 'Luvable Friends', 'Luvs', 'Lyons / Hit Ent.', 'Lyons Hit Entertainment', 'Lysol', 'M&M', 'MAM Baby', 'MARC JACOBS', 'MATRIX', 'MGA Entertainment', 'MGM', 'MLB', 'Maclaren', 'Madame Alexander', 'Magformers', 'Maisto', 'Majestic', 'Mamas & Papas', 'Manhattan Toy', 'Martha Stewart', 'Marvel', 'Marvel Universe', 'Matchbox', 'Mattel', 'Mattel®', 'Max Studio', 'Maxi-Cosi', 'McFarlane Sports', 'McFarlane Toys', 'Medela', 'Mega Bloks', 'Mega Brands', 'Mega Hobby', 'Melissa & Doug', 'Melissa Doug', 'Mezco', 'Michael Kors', 'Microsoft', 'Middleton Doll Company', 'Minecraft', 'Mineral Fusion', 'Mini Boden', 'Mini Melissa', 'Minnetonka', 'Minnie Mouse', 'Miss Me', 'Mobi Technologies', 'Mobil™', "Mommy's Helper", 'Mongoose', 'Monopoly', 'Monteau', 'Moose Mountain', 'Moose Toys', 'Mossimo', 'Motorola', 'Mountain Buggy', 'Mud Pie', 'Mudd', 'Munchkin', 'Music Little People', 'Mustela', 'My Baby Sam', 'My Brest Friend', 'My Little Pony', 'My Michelle', 'NBA', 'NECA', 'NFL', 'NHL', 'NanoBlock', 'Native', 'Nautica', 'NeatNik', 'Nerf', 'New Arrivals', 'New Balance', 'New Bright', 'Nick & Nora', 'Nick Jr.', 'Nickelodeon', 'Nike', 'Nintendo', 'NoJo', 'Nordstrom Baby', 'North Face', 'North States', 'Nosefrida', 'Nostalgia Electrics', 'NuRoo', 'Nuby', 'Nuk', 'Nursery Fresh', 'Nutrabella', "O'Neill", 'OXO Tot', 'Oasis', 'Okie Dokie', 'Old Navy', 'Old Soles', 'On The Fly', 'Op', 'Orbit Baby', 'Osh Kosh', "Osh Kosh B'gosh", 'OshKosh', 'Oshkosh', 'Outset Media', 'Oxford', 'PBS', 'PEZ', 'PINK', 'PUMA', "Palmer's", 'Pampers', 'Pampers Baby Dry', 'Pampers Baby Fresh', 'Pampers Cruisers', 'Pampers Easy Ups', 'Pampers Sensitive', 'Pampers Splashers', 'Pampers Swaddlers', 'Paper Magic', 'Paradise Kids', 'Paris Blues', 'Paul Frank', 'Paw Patrol', 'Peanut Shell', 'Pearhead', 'Pediasure', 'Peg Perego', 'Peppa Pig', 'Perler', 'PetSmart', 'Petit Tresor', 'Petunia Pickle Bottom', 'Phil & Teds', 'Philadelphia Eagles', 'Philips', 'Piedmont', 'Pillow Pets', 'Pink Fizz', 'PlaSmart', 'Play Along', 'Play Doh', 'Play-Doh', 'PlayStation', 'Playhut', 'Playmates', 'Playmobil', 'Playskool', 'Playstar', 'Playtex', 'Pokemon', 'Pokemon USA', 'Polo Jeans Co.', 'Polo Ralph Lauren', 'PopCap', 'Popatu', 'Popular', 'Pottery Barn', 'Pottery Barn Kids', 'Power Wheels', 'Precious Moments', 'Pressman Toy', 'Primark', 'Prince LionHeart', 'Puj', 'Puma SE', 'Pura', 'Quantum Mechanix', 'Quicksilver', 'Quiksilver', 'Quinny', 'RCA', 'ROCKY', 'Radio Flyer', 'Rags to Raches', 'Rainbow Shops', 'Ralph Lauren', 'Ralph Lauren Collection', 'Rare Editions', 'Ravebsburger', 'Ravensburger', 'Razor', "Reader's Digest", 'Realtree', 'RedHead', 'Reebok', 'Regalo', 'Revell', 'Rio Grande Games', 'Road Rippers', 'Robeez', 'Roller Derby', 'RoseArt', 'Rothschild', 'Roxy', 'Rubbermaid', 'Rubies Costume Company', 'Rumparooz', 'Russ', 'SKECHERS', 'SO', 'Sadie & Scout', 'Safety 1st', 'Safety st', 'Salt Water Sandals by Hoy', 'Sam & Libby', 'Sam Edelman', 'Samsung', 'Sanrio', 'Sassy', 'Saucony', 'Savannah', 'Scentsy', 'Schleich', 'Scholastic', 'Scholastic Children', 'Schylling', 'Sea Wees', 'Sega', 'Sephora', 'Serta', 'Sesame Street', 'Seven7', 'Sharper Image', 'Shaun White', 'Silly Bandz', 'Silver Jeans', 'Silverlit', 'Similac', 'Singing Machine', 'Skechers Kids', 'Sketchers', 'Skip Hop', 'Slime®', 'Smart Games', 'Smartzone', 'Smithsonian', 'Sonoma', 'Sony', 'Sony Pictures', 'Sophia', 'Sovereign Code', 'Spectra', 'Speechless', 'Sperry', 'Sperry Top-Sider', 'Sperrys', 'Spider-Man', 'Spin Master', 'Spin Masters', 'Sprout', 'Square Enix', 'Star Wars', 'Starbucks', 'Stats', 'Steiff', 'Step', 'Steve Madden', 'Stokke', 'Storkcraft', 'Stride Rite', 'Stuart Weitzman', 'Sumersault', 'Summer Breeze', 'Summer Infant', 'Supra', 'Supreme', 'Swaddle Designs', 'Sweet Heart Rose', 'Sweet Jojo Designs', 'Swimways', 'TOMS', 'TOMY', 'Taggies', 'Tahari', 'Takara', 'Tara Toys', 'Target', 'Tea Collection', 'Tech  Kids', 'Techno Source', 'Teenage Mutant Ninja Turtles', 'Tek Nek', 'Tervis', 'Texas Instruments', 'Thames & Kosmos', 'The Bridge Direct', "The Children's Place", 'The First Years', 'The Honest Company', 'The Learning Journey', 'The Maya Group', 'The North Face', 'The Original Muck Boot Co.', 'The Peanut Shell', 'The Timberland Company', 'The Wish Factory', 'Thermos', 'ThinkFun', 'Thinkway', 'Thomas & Friends', 'Tickled Pink Tees', 'Tiffany & Co.', 'Tiger', 'Timberland', 'Tiny Love', 'Tolly Tots', 'Tommee Tippee', 'Tommy Hilfiger', 'Tonka', 'Tonner Doll Company', 'Tootsie', 'Topps', 'Tory Burch', 'Toy Monster', 'Toynami', 'Toys R Us', 'Toys R Us Plush', 'Toysmith', 'Trend Lab', 'True Religion', 'True Religion Brand Jeans', 'Truly Scrumptious', 'Tupperware', 'Twisted X', 'Tylenol', 'UGG', 'UGG Australia', 'UNIQLO', 'UPPAbaby', 'USAopoly', 'Ubbi', 'Ugg boots', 'Uglydoll', 'Ultra Pro', 'Umbro', 'Uncle Milton', 'Under Armour', 'Undercover Mama', 'Universal Baby', 'Universal Studios', 'Univsersal Studios', 'Unknown', 'Upspring', 'VANS', 'VIGOSS', 'VTech', 'Valco Baby', 'Vans', 'Vera Bradley', 'Versace Collection', 'Vibram', 'Vicks', 'Victoria secret', "Victoria's Secret", 'Vital Baby', 'Vitamins Baby', 'Vivid Imaginations', 'Viz Media', 'Volcom', 'WB Games', 'WWE', 'Warner Bros.', 'Warner Brothers', 'Weatherproof', 'Wendy Bellissimo', 'Western Chief', 'Wham-O', 'Wild Republic', 'Wildkin', 'Wilson', 'Wilton', 'Wish', 'Wizards of the Coast', 'Wonderworld', 'Workman', 'WowWee', 'Wrangler', 'WubbaNub', 'XOXO', 'Xersion', 'Xhilaration', 'YBike', 'Yada', 'Yamaha', 'Yeezy', 'Yeti', 'Youngland', 'Yvolution', 'Z-Man Games', 'ZARA', 'Zak Designs', 'Zara', 'ZeroXposur', 'Zobo', 'Zoli', 'abercrombie kids', 'aden & anais', 'adidas Originals', 'amy coe', 'bumGenius', 'doTERRA', 'dreambaby', 'gDiapers', 'iHome', 'jansport', 'lillebaby', 'mamaRoo', 'moms', 'monster high', 'patagonia', 'rue', 'timi & leslie', 'tm!', 'tokidoki', 'vineyard vines']

In [70]:
print(sorted(sub_dfs['Electronics']['brand_name'].unique()))

['1byone', '2K Games', '3M®', 'A Bathing Ape', 'A&A Optical', 'ACER', 'AMD', 'ASUS', 'AT&T', 'ATI Technologies', 'Accessory Collective', 'Acer', 'Activision', 'Adidas', 'Advent', 'Agfa', 'Aiptek', 'Air Hogs', 'Alienware', 'Alpine', 'Altec Lansing', 'Amazon', 'AmazonBasics', 'American Girl ®', 'American apparel', 'Anker', 'Apple', 'Astro', 'Atari', 'Audio Technica', 'Audio-Technica', 'AudioSource', 'Audiovox', 'Aurum', 'Avery', 'Avon', 'BLUE', 'Bandai', 'Bang & Olufsen', 'Barbie', 'Bass', 'Beats', 'Beats by Dr. Dre', 'Belkin', 'Black & Decker', 'Blizzard', 'Body Glove', 'Bose', 'Brother', 'Bushnell', 'Cannon', 'Canon', 'Capcom', 'Carhartt', 'Case Logic', 'Chloe', 'Chromo Inc', 'Coach', 'Coby Electronics', 'Coleman', 'Com', 'Compaq', 'Conair', 'Converse', 'Cooler Master', 'Corsair', 'Crayola', 'Creative Labs', 'Crosley Radio', 'Crucial', 'Curtis Computer Products', 'Custom Accessories', 'D-Link', 'DC Comics', 'DIRECTV', 'DJI', 'DVS', 'DYMO', 'Dazzle Multimedia', 'Dell', 'Denon', 'Dior', 'Disney', 'Disney Pixar', 'Dragon Ball Z', 'Dreamworks', 'Duracell', 'EA Sports', 'EVGA', 'EXP Computer', 'Electric Family', 'Electronic Arts', 'Element', 'Elmers', 'Elmo', 'Emachines', 'Emerson', 'Energizer®', 'Epson', 'Escort Radar', 'Fila', 'Fitbit', 'Franklin Electronics', 'Fuji', 'Fujifilm', 'Funimation Production', 'Funko', 'G by Guess', 'GAME', 'GBC', 'GE', 'GPX', 'Garmin', 'Gateway', 'General Electric', 'Generic', 'Genica', 'GeoDiscovery', 'Ghost', 'Gigabyte', 'Go Gear', 'GoPro', 'Good Technology', 'Google', 'Griffin', 'Gucci', 'H&M', 'HP', 'HTC', 'Halo', 'Hannspree', 'Harman Kardon', 'Hello Kitty', 'Herschel Supply Company', 'Hitachi', 'HoMedics', 'Hollister', 'Hot Topic', 'Hype', 'I-Jam', 'IBM', 'Impossible', 'Incase Designs', 'Incipio', 'Insignia', 'Intel', 'JBL', 'JVC', 'Jeep', 'Jensen', 'Joby', 'Jordan', 'Kate Spade', 'Kensington', 'Kenwood', 'Kingston', 'Klipsch', 'Kodak', 'Konami', 'Koss', 'Kylie Cosmetics', 'Kyocera', 'LEGO', 'LG', 'LaCie', 'Leap Frog', 'Lenovo', 'Lexar', 'LifeProof', 'Lifeproof', 'Linksys', 'Lions Gate', 'Logitech', 'LuLaRoe', 'LucasArts Entertainment', 'M', 'MARC JACOBS', 'MLB', 'MSI', 'Magellan®', 'Magnavox', 'Marvel', 'Marvel Universe', 'Maxell', 'Maxtor', 'Mediasonic', 'Mega Bloks', 'Memorex', 'Michael Kors', 'Micro Innovations', 'Microsoft', 'Midland', 'Minecraft', 'Mitsubishi', 'Moda International', 'Monster Cable', 'Mophie', 'Motherhood Maternity', 'Motorola', 'MyCharge', 'NEC Technologies', 'NEXXUS', 'NO-AD', 'NVIDIA', 'Nana', 'Neewer', 'Nest', 'Netgear', 'New Bright', 'Nick Jr.', 'Nike', 'Nikon', 'Nintendo', 'Nokia', 'Nook', 'North Face', 'Olympus', 'Onkyo', 'Oregon Scientific', 'OtterBox', 'PINK', 'PNY', 'Panasonic', 'Paramount', 'Patricia Nash', 'Peppa Pig', 'Philadelphia Eagles', 'Philips', 'Phillips', 'Pinnacle Systems', 'Pioneer', 'Plantronics', 'PlayStation', 'PoGo! Products', 'Pokemon', 'Polaroid', 'Polk Audio', 'Polycom', 'PopSockets', 'Power A', 'Precision', 'Pressman Toy', 'RCA', 'RIM', 'Ralph Lauren', 'Rand McNally', 'Razer', 'Reba', 'Ring', 'Roku', 'Rosewill', 'Saga', 'Samsonite', 'Samsung', 'Samsung Galaxy', 'SanDisk', 'Sangean', 'Sanyo', 'Schumacher Electric', 'Scosche', 'Seagate', 'Sega', 'Sennheiser', 'Sesame Street', 'Sharp', 'Sharper Image', 'Shure', 'Sirius Satellite Radio', 'Skullcandy', 'Smart Gear', 'Sonix', 'Sons of Anarchy', 'Sony', 'Sony Electronics', 'Sony Pictures', 'Speck', 'Spigen', 'Spin Master', 'SportBrain', 'Square', 'Square Enix', 'Stanley', 'Star Wars', 'Starbucks', 'Stella & Dot', 'Supreme', 'Sylvania', 'TDK', 'TOMS', 'TP Link', 'TP-Link', 'Taboo', 'Target', 'Targus', 'Technics', 'Texas Instruments', 'Tiger', 'Tile', 'TomTom', 'Toshiba', 'Tractr', 'Tumi', 'Turtle Beach', 'Ubisoft', 'Ultimate Ears', 'UltimateTV RCA', 'Uniden', 'Universal Studios', 'Univsersal Studios', 'Unknown', 'Unwired Technologies', 'VTech', 'Valve', 'Vans', 'Velocity', 'Vera Bradley', 'Victoria secret', "Victoria's Secret", 'ViewSonic', 'Volcom', 'WWE', 'Wacom', 'Walt Disney Studios Entertainment', 'Walt Disney Studios Home Entertainment', 'Warner Bros.', 'Warner Brothers', 'Warner Home Video', 'Warrior', 'Western Digital', 'XM', 'Xbox', 'Yeti', 'ZENA', 'Zara', 'Zoom', 'Zumba', 'Zune', 'ZyXEL', 'dreamGEAR', 'iHome', 'iXCC', 'jansport', 'kate spade new york', 'rue']

In [71]:
print(sorted(sub_dfs['Men']['brand_name'].unique()))

['10.Deep', '21men', '24/7 Comfort Apparel', '47', '47 Brand', '5.11 Tactical', '7 Diamonds', '7 For All Mankind®', '8732 Apparel', 'A Bathing Ape', 'A&A Optical', 'A&R Sports', 'A+D', 'A-Shirt', 'A.K.A', 'A.P.C.', 'A/X Armani Exchange', 'AC/DC', 'ADAM', 'AG Adriano Goldschmied', 'AKOO', 'ALDO', 'AND', 'AND1', 'ASICS', 'ASOLO', 'ASOS', 'Abercrombie & Fitch', 'Academy', 'Accutron', 'Acne Jeans', 'Acne Studios', 'Active', 'Activision', 'Addison', 'Adidas', 'Adolfo', 'Aeropostale', 'Affliction', 'Air Force', 'Air Jordan', 'Airwalk', 'Akademiks', 'Alan Flusser', 'Alexander Julian', 'Alexander McQueen', 'Alfani', 'Alien Workshop', 'Alife', 'All Saints', 'All Sport', 'AllSaints', 'Allen Edmonds', 'Allen Solly', 'Alpha Industries', 'Alpine Design', 'Alpinestars', 'Alstyle Apparel', 'Altamont', 'Alternative', 'American Apparel', 'American Classics', 'American Eagle', 'American Fighter', 'American Needle', 'American Rag', 'American Tourister', 'American Vintage', 'American apparel', 'Amphibious Outfitters', 'Anchor Blue', 'Andrew Christian', 'Andrew Marc', 'Angels', 'Angry Birds', 'Antigua', 'Antique Rivet', 'Anvil', 'Apple', 'Apt.', 'Apt. 9', "Arc'teryx", 'Archaic', 'Architect', 'Ariana Grande', 'Ariat', 'Arizona', 'Arizona Jean Company', 'Armani', 'Armani Collezioni', 'Armani Exchange', 'Armani Jeans', 'Army', 'Arrow', 'Ashworth', 'Ask', 'Atari', 'Athlete', 'Athletech', 'Athletic Works', 'Attention', 'Audemars Piguet', 'Audi', 'Augusta Sportswear', 'Austin Clothing Co.', 'Avery', 'Avirex', 'Avon', 'A|X Armani Exchange', 'Aéropostale', 'BAD BOY', 'BCBGMAXAZRIA', 'BDG', 'BKE', 'BMW', 'BOSS Black', 'BOSS HUGO BOSS', 'BVD', 'Badger', 'Balenciaga', 'Bally', 'Balmain', 'Bamboo', 'Banana Republic', 'Bape', 'Bar Lll', 'Barbour', 'Barneys New York', 'Basic Editions', 'Bass', 'Batman', 'Bauer', 'Bay Island', 'Bechamel', 'Bed Stu', 'Bella', 'Ben Davis', 'Ben Sherman', 'Bench', 'Benetton', 'Beretta', 'Berne Apparel', 'Betsey Johnson Label', 'Beverly Hills Polo Club', 'Big Bang Theory', 'Big Dogs', 'Big Star', 'Bike', 'Bikerwear', 'Bill Blass', 'Billabong', 'Billionaire Boys Club', 'Billionaire Boys Club and Ice Cream', 'Billy Reid', 'Bioworld', 'Birkenstock', 'Blac Label', 'Black Scale', 'Blackhawk', 'Blair', 'Blauer', 'Blind', 'Bob Mackie', 'Bobbie Brooks', 'Body Glove', 'Bongo', 'Bonobos', 'Boohoo', 'Boots', 'Born', 'Boston Proper', 'Bostonian', 'Bottega Veneta', 'Bowery Supply', 'Bravado', 'Brave Soul', 'Breitling', 'Briefly Stated', 'Brighton', 'Brioni', 'Brixton', 'Brockum', 'Brooklyn Express', 'Brooks', 'Brooks Brothers', 'Browning', 'Bruno Magli', 'Bucket Feet', 'Buckle', 'Buckley Supply Co.', 'Buffalo', 'Buffalo David Bitton', 'Buffalo Jeans', 'Bugle Boy', 'Bullhead', 'Bulova', 'Bulwark', 'Burberry', 'Burberry Brit', 'Burnside', 'Buxton', 'C by Champion', 'CAT', 'CB Sports', 'CCM', 'CERRUTI', 'COOGI', "Cabela's", 'Cactus', 'Cali', 'Call It Spring', 'Callaway', 'Calvin Klein', 'Cambridge Classics', 'Campia Moda', 'Canada Goose', 'Canali', 'Canterbury', 'Canvas', 'Capcom', 'Caravelli', 'Carbon', 'Cardinal of Canada', 'Carhartt', 'Caribbean Joe', 'Carlos Santana', 'Carnival', 'Carrera', 'Carrhart', 'Cartier', 'Cartoon Network', 'Casio', 'Castle', 'Casual', 'Casual Industrees', 'Caterpillar', 'Cezani', 'Chaco', 'Chalk Line', 'Champion', 'Champion Sports', 'Champs', 'Chanel', 'Chaps', 'Charles River Apparel', 'Charles Tyrwhitt', 'Chemistry', 'Cherokee', 'Chevrolet', 'Chip & Pepper', 'Chloe', 'Choppers', 'Christian Audigier', 'Christian Dior', 'Christian Louboutin', 'Chrome Hearts', 'Cinch', 'Cipo & Baxx', 'Citizen', 'Citizens of Humanity', 'City Streets', 'Claiborne', 'Clarks', 'Club Monaco', 'Club Room', 'Coach', 'Coast', 'Coca-Cola', 'Cole Haan', 'Coleman', 'College Edition', 'Colorado Clothing', 'Colosseum', 'Columbia', 'Comfort Colors', 'Comme des Garcons', 'Converse', 'Converse Shoes', 'Cooper', 'Corona', 'Cos', 'Costa Del Mar', 'Cotton Heritage', 'Cotton On', 'CoverGirl', 'Covington', 'Craftsman', 'Crazy Horse', 'Creative Recreation', 'Creature', 'Cremieux', 'Crocs', 'Croft & Barrow', 'Crooks & Castles', 'Croota', 'Cubavera', 'Cumberland Bay', 'Customized & Personalized', 'Cutter & Buck', 'Cygnus', 'Cypress Links', 'Céline', 'D&G', 'DC Comics', 'DC Shoes', 'DGK', 'DIESEL', 'DKNY', 'DKNY Jeans', 'DL1961', 'DP', 'DRI DUCK', 'DVS', 'Dainese', 'Dakine', 'Dale Of Norway', 'Dan Post', 'Daniel Cremieux', 'Daniel Wellington', 'Danner', 'Danner Inc', 'Danskin', 'Danskin Now', 'Dansko', 'David Carey', 'David Taylor', 'Dawgs', 'DeLONG', 'Decree', 'Delta', 'Denim & Co.', 'Denim & Supply Ralph Lauren', 'Descente', 'Devon & Jones', 'Dexter', 'Diadora', 'Diamond Supply Co.', 'Dickies', 'Dior', 'Disney', 'District', 'Divided', 'Dockers', 'Doctor Who', 'Dolce & Gabbana', 'Donald Trump', 'Donna Karen', 'Dooney & Bourke', 'Dope', 'Dr. Martens', "Dr. Scholl's", 'Dr. Seuss', 'Dragon Alliance', 'Dragon Ball Z', 'Dragonfly', 'Drake', 'Dscp', 'Dsquared', 'Duck Commander', 'Ducks Unlimited', 'Duluth Trading Company', 'Dunbrooke', 'Dunlop', 'Dynasty', 'ECKO', 'ENERGIE', 'ESPN', 'Eastern Mountain Sports', 'Easton', 'Ecco Bella', 'Ecko Unltd.', 'Ecote', 'Ed Hardy', 'Eddie Bauer', 'Eddie Bauer Clothing', 'Eighty Eight', 'Eileen Fisher', 'Electric Visual', 'Element', 'Elite', 'Elwood', 'Ely Cattleman', 'Emerica', 'Empire', 'Emporio Armani', 'Enjoi', 'Enyce', 'Enyce Clothing', 'Ergodyne', 'Ermenegildo Zegna', 'Esprit', 'Etro', 'Evan Picone', 'Everlast', 'Evolution', 'ExOfficio', 'Excell', 'Excelled', 'Express', 'Ezekiel', 'FOREVER 21', 'FORM Athletics', 'FUBU', 'Faded Glory', 'Falls Creek', 'Family Guy', 'Famous Stars & Straps', 'Fanatics', 'Fatal Clothing', 'Fender', 'Fendi', 'Ferragamo', 'Ferrari', 'Ferrecci', 'Field & Stream', 'Field Gear', 'Fifth Sun', 'Fila', 'Fila Sport', 'Filson', 'Filter', 'Filthy Dripped', 'Five Four', 'Fjallraven', 'Florsheim', 'Flow Society', 'Fly Society', 'Foot Locker', 'FootJoy', 'For Bare Feet', 'Ford', 'Foreign Exchange', 'Fossil', 'Foster Grant', 'Foundry', 'Fourstar Clothing', 'Fox', 'Fox Racing', 'Franco', 'Fred Perry', 'Free Country', 'Freeze', 'French Connection', 'Fruit of Loom', 'Fruit of the Loom', 'Frye', 'Frédérique Constant', 'Funko', 'G by Guess', 'G-III', 'G-Shock', 'G-Star Raw', 'G-Unit', 'G.H. Bass & Co.', 'GAME', 'GBX', 'GEAR FOR SPORTS', 'GM', 'GOLD TOE', 'GUESS', 'Galaxy', 'Game Gear', 'Gap', 'Garmin', 'Generra', 'Geneva', 'Geneva Platinum', 'Geoffrey Beene', 'George', 'George Foreman', 'Georgia Boot', 'Gerber', 'Ghast', 'Gianfranco Ferre', 'Giant', 'Gildan', 'Giordano', 'Giorgio Armani', 'Giorgio Brutini', 'Giovanni Navarre', 'Girbaud', 'Giuseppe Zanotti', 'Givenchy', 'Globe', "Gold's Gym", 'Goodie Two Sleeves', 'Goyard', 'Grace In LA', 'Grand Slam', 'Grant Thomas', 'Great Northwest', 'Greg Norman', 'Gucci', 'Guinness', 'Guy Harvey', 'Gymshark', 'H&M', 'HEAD', 'HERMES', 'HOBO INTERNATIONAL', 'HUF', 'Haggar', 'Hamilton', 'Hanes', 'Hang Ten', 'Harbor Bay', 'Hard Rock Cafe', 'Hardwood Classics', 'Harley-Davidson', 'Harrington', 'Harriton', 'Hart & Huntington', 'Harvard Square', 'Hasbro', 'Havaianas', 'Hawk', 'Hawke & Co', 'Hayabusa', 'Heelys', 'Heinz', 'Helix', 'Hello Kitty', 'Helly Hansen', 'Helmut Lang', 'Henry Grethel', 'Heritage', 'Hermès', 'Herschel Supply Company', 'Hickey Freeman', 'High Sierra', 'Highlander', 'Highway Jeans', 'Hind', 'Hobie', 'Hoka One', 'Hollister', 'Hollister Co.', 'Honda', 'Honolua', 'Hot Topic', 'Howe', 'Hublot', 'Hudson Jeans', 'Hugo Boss', 'Hunt Club', 'Hunter', 'Hunter Boots', 'Hurley', 'Hush Puppies', 'Hustler', 'Hybrid', 'INC International Concepts', 'INHABIT', 'IZOD', 'Icebreaker', 'Icon', 'Inc', 'Independent', 'Infinity', 'Ingear', 'Invicta', 'Invicta Watch Group', 'Iolani', 'Irish Setter', 'Iron Fist', 'Iron Maiden', 'Ironman', 'Island Shores', 'Issey Miyake', 'Ivy Crew', 'J. America', 'J. Crew', 'J. Ferrar', 'JACO', 'JCPenney', 'JERZEES', 'JF J. Ferrar', 'JNCO', 'JUMP', 'Jack Daniels', 'Jack Spade', 'Jagermeister', 'Jamaica Jaxx', 'James Perse', 'JanSport', 'Jeffrey Campbell', 'Jeremy Scott x Adidas', 'Jessica Simpson', 'Jinx', 'Jockey', 'Joe Rocket', "Joe's Jeans", 'John Ashford', 'John Blair', 'John Deere', 'John Henry', 'John Varvatos', 'John Varvatos Collection', 'John Varvatos Star USA', 'Johnson', 'Johnston & Murphy', 'Jones New York', 'Jordache', 'Jordan', 'Jordan Craig', 'Jordans', 'Jos. A. Bank', 'Joseph Abboud', 'Joyrich', 'Juicy Couture', 'Junk Food', 'Junk Food Clothing', 'Just Cavalli', 'Justin Boots', 'K & W', 'K-SWISS', 'KDLINKS', 'KEEN', 'KR3W', 'KRW', 'Kamik', 'Kangol', 'Kappa', 'Kate Spade', 'Kathy Van Zeeland', 'Kawasaki', 'Kay Jewelers', 'Kendall & Kylie', 'Kenneth Cole New York', 'Kenneth Cole Reaction', 'Kenzo', 'Key', 'Khombu', 'King Baby Studio', 'Kipling', 'Kirkland Signature', 'Kirra', 'Kiton', 'Knights Sportswear', 'Knightsbridge', 'Knocker', 'Koman', 'Krew', 'Kuhl', 'L.A.M.B.', 'L.L. Bean', 'LA Hearts', 'LRG', 'Lacoste', 'Laguna Beach', 'Lakai', "Lands' End", 'Lanvin', 'Laredo', 'Lauren Ralph Lauren', 'Lee', 'Levi', 'Levi Strauss & Co.', "Levi's®", 'Liberty Apparel', 'Life Is Good', 'Lilly Pulitzer', 'Lip Service', 'Liquid Blue', 'Liz Claiborne', 'Lokai', 'London Fog', 'Looney Tunes', 'Lord & Taylor', 'Lot', 'Louis Garneau', 'Louis Raphael', 'Louis Vuitton', 'Love Moschino', 'Lowa', 'LuLaRoe', 'Lucchese', 'Lucky Brand', 'Lucky Brand Jeans', 'Lugz', 'Lululemon', 'Lux', 'Lyle & Scott', 'M&O KNITS', 'MARC BY MARC JACOBS', 'MARC JACOBS', 'MCM', 'MCM Worldwide', 'MEK', 'MGM', 'MLB', 'MMA Elite', 'MV Sport', 'Machine', 'Mackintosh', "Macy's", 'Madden Girl', 'Magellan®', 'Magic Sports', 'Magnum', 'Maison Goyard', 'Maison Martin Margiela', 'Majestic', 'Mammut', 'Marc Ecko', 'Marc New York', 'Marcelo Burlon County of Milan', 'Margaritaville', 'Marmot', 'Martin Margiela', 'Marvel', "Mason's", 'Masters', 'Matix', 'Mattel®', 'Maui & Sons', 'Maui Jim', 'Maurices', 'Mavi Jeans', 'McDavid', 'MeDusa', 'Mecca', 'Members Only', 'Merona', 'Merrell', 'Metal Mulisha', 'Miami Ink', 'Michael Brandon', 'Michael Kors', 'Micros', 'Mighty Fine', 'Milano', 'Miller', 'Minnetonka', 'Misfits', 'Mishka', 'Miskeen', 'Miss Me', 'Mitchell & Ness', 'Mizuno', 'Modern Amusement', 'Modern Culture', 'Monarchy', 'Moncler', 'Monster', 'Moschino', 'Mossimo', 'Mossimo Supply Co.', 'Mossy Oak', 'Motorola', 'Motorola Consumer Radios', 'Mountain Hardwear', 'Movado', 'Mulberry', 'Murano', 'NASCAR', 'NBA', 'NBN Gear', 'NCAA', 'NFL', 'NHL', 'Naked & Famous', 'Native', 'Nautica', 'Neff', 'Neff Headwear', 'Neighborhood', 'Neil Allyn', 'Neiman Marcus', 'New Arrivals', 'New Balance', 'New Era', 'New York & Company', 'Next Level', 'Nickelodeon', 'Nicklaus', 'Nicole Miller', 'Nike', 'Nintendo', 'Nixon', 'No Boundaries', 'No Fear', 'Nor Cal', 'Nordstrom', 'North End', 'North Face', 'Northwest Territory', 'Nudie Jeans', 'Nunn Bush', "O'Neill", 'OGIO®', 'OLOOK', 'OULUOQI', 'Oakley', 'Obey', 'Obey Clothing', 'Ocean Current', 'Ocean Pacific', 'Off-White', 'Old Glory', 'Old Navy', 'Old Varsity Brand', 'OluKai', 'Omega', 'On the Byas', 'One Industries', 'Onitsuka Tiger', 'Op', 'Opening Ceremony', 'Optimum', 'Original Penguin', 'Oris', 'Orla Kiely', 'Orvis', 'Oscar de la Renta', 'Outdoor Life', 'Outdoor Research', 'Oxford Golf', 'PAIGE', 'PGA TOUR', 'PING', 'PINK', 'PONY', 'PROPPER', 'PRPS', 'PUMA', 'Pacific Sunwear', 'Pacific Trail', 'Paco', 'Paige Denim', 'Pal Zileri', 'Palladium Boots', 'Palm Beach', 'Panhandle Slim', 'Paper Denim & Cloth', 'Paradise Collection', 'Paradise Found', 'Paradox', 'Parish', 'Patagonia', 'Patagonia, Inc.', 'Patek Philippe', 'Paul Fredrick', 'Paul Jones', 'Peanuts', 'Pearl Izumi', 'Pebble Beach', 'Pendleton', 'Pendleton Woolen Mills', 'Penguin', 'Perry Ellis', 'Peter Millar', 'Phat Farm', 'Phat Farm/Baby Phat', 'Philadelphia Eagles', 'Pierre Cardin', 'Pineapple Connection', 'Pink Dolphin', 'Planet Earth', 'Planet Hollywood', 'Playboy', 'Plugg', 'Point Zero', 'Pokemon', 'Polo', 'Polo Jeans Co.', 'Polo Ralph Lauren', 'Porsche Design', 'Prada', 'Prestige', 'Primal Wear', 'Primark', 'Primitive', 'Prince', 'Pro', 'Pro Edge', 'Pro Player', 'ProClub', 'Proactiv', 'Profound Aesthetic', 'Pronto Uomo', 'Propet', 'Protege', 'Psycho Bunny', 'Publish', 'Pull&Bear', 'Pulsar', 'Puma', 'Puritan', 'Quicksilver', 'Quiksilver', 'Quiksilver Waterman Collection', 'RAW', 'REI', 'RLX Ralph Lauren', 'ROCKY', 'ROOK', 'RVCA', 'Rainbow Shops', 'Ralph Lauren', 'Ralph Lauren Collection', 'Ramones', 'Rasco FR', 'Raw State', 'Rawlings', 'Ray-Ban', 'Realtree', 'Rebel Spirit', 'Red Ape', 'Red Camel', 'Red Jacket', 'Red Kap', 'Red Wing', 'Red Wing Shoes', 'RedHead', 'Reebok', 'Reef', 'Relic', 'Replay', 'Request', 'Resistol', 'Retrofit', 'Reunion', 'Revo', 'Reyn Spooner', 'Rick Owens', 'Riff Stars', 'Ring', 'Ring of Fire', 'Rip Curl', 'Ripcurl', 'Ripple Junction', 'River Island', 'Roar', 'Robert Graham', 'Robert Talbott', "Robin's Jeans", 'Rocawear', 'Rocawear Clothing', 'Rock & Republic', 'Rock Revival', 'Rockies', 'Rockport', 'Rocksmith', 'Rockstar', 'Rodd & Gunn', 'Rogue', 'Rolex', 'Ron Jon', 'Roper', 'Rothco', 'Roundtree & Yorke', 'Route', 'Route 66', 'Rowdy Gentleman', 'Royal Robbins', 'Rue21', 'Ruff Hewn', 'Russell Athletic', 'Rustler', 'Rusty', 'SKECHERS', 'SO', 'SPANX', 'SUGOI', 'Saddlebred', 'Saga', 'Saint Laurent', 'Saks Fifth Avenue', 'Salomon', 'Salt Lake Clothing', 'Salvage', 'Salvatore Ferragamo', 'Samsonite', 'Samsung', 'Samsung Galaxy', 'Sansabelt', 'Santa Cruz', 'Sanuk', 'Saucony', 'Savane', 'Savile Row', 'Savvy', 'Saxx', 'Schmidt', 'Scotch & Soda', 'Screen Stars', 'Sean John', 'Sean John Fashion', 'Sears', 'Seiko', 'Sesame Street', 'Seven7', 'Shaka Wear', 'Shinola', 'Sideout', 'Signature', 'Silpada', 'Silver', 'Silver Jeans', 'Silver Jeans Co.', 'Silver Star', 'Simms', 'Sisley', 'Skagen', 'Skin Industries', 'Skullcandy', 'Slazenger', 'SmartWool', 'Smet', 'Smoky Mountain', 'Snap', 'Snap-on', 'Social Collision', 'Sock It to Me', 'Soffe', 'Sofft', 'Solo', 'Soma', 'Sonoma', 'Sons of Anarchy', 'South Pole', 'Southern Marsh', 'Southpole', 'Spalding', 'Speedo', "Spencer's", 'Sperry', 'Sperry Top-Sider', 'Sperrys', 'Spitfire', 'Sport-Tek', 'Spy Tec', 'Spyder', 'St. John', "St. John's Bay", 'Stacy Adams', 'Stafford', 'Stampd', 'Stance', 'Star Wars', 'Startee', 'Starter', 'Steadfast Brand', 'Stetson', "Steve & Barry's", 'Steve Madden', 'Stitches', 'Stormtech', 'Streetwise', 'Structure', 'Stuhrling Original', 'Stussy', 'Stüssy', 'Sullen Clothing', 'Sun River', 'Sundog', 'Superdry', 'Supra', 'Supreme', 'Swiss Legend', 'TIGLIO', 'TOMS', 'TRU-SPEC', 'Tag Heuer', 'TailorByrd', 'TapouT', 'Target', 'Targus', 'Tasso Elba', 'Team Apparel', 'Technomarine', 'Ted Baker London', 'TeeFury', 'Tek Gear', 'Tennessee River', 'Teva', "The Children's Place", 'The Hundreds', 'The Mountain', 'The North Face', 'The Timberland Company', 'TheLees', 'Thom Browne', 'Thor', 'Thrasher', 'Thrasher Magazine', 'Threadless', 'Tiffany & Co.', 'Tignanello', "Tilly's", 'Timber Creek', 'Timberland', 'Timex', 'Tissot', "Tod's", 'Tom Ford', 'Tom James', 'Tommy Bahama', 'Tommy Hilfiger', 'Tommy John', 'Tony Hawk', 'Tony Lama', 'Top of the World', 'Topman', 'Towncraft', 'Travis Mathew', 'Trench', 'Trevco', 'Tribal', 'Tricots St. Raphael', 'Triple 5 Soul', 'Triple Five Soul', 'Tripp NYC', 'True Grit', 'True Religion', 'True Religion Brand Jeans', 'True Rock', 'Trukfi', 'Tultex', 'Tumi', 'Turnbull & Asser', 'Turnbury', 'Twenty X', 'Twisted X', 'Two In The Shirt', 'U.S. Polo Assn.', 'UFC', 'UGG', 'UGG Australia', 'UNIONBAY', 'UNIQLO', 'US POLO ASSN', 'USA Leather', 'Umbro', 'Umo Lorenzo', 'Uncommon Threads', 'Undefeated', 'Under Armour', 'Uniqlo', 'Universal Studios', 'Unknown', 'Unlisted', 'Urban Outfitters', 'Urban Pipeline', 'Urban Up', 'VANS', 'VISSLA', 'Valentino', 'Van Heusen', 'Vantage', 'Vera Pelle', 'Versace', 'Versace Collection', 'Versace Jeans', 'Vibram', 'Victoria secret', "Victoria's Secret", 'Victorinox Swiss Army®', 'Victorious', 'Vilebrequin', 'Vince', 'Vince Camuto', 'Vintage', 'Vintage Red', 'Visvim', 'Volcom', 'Von Dutch', 'WWE', 'Walls', 'Warner Bros.', 'WearFirst', 'Weatherproof', 'Wembley', 'West Coast Choppers', 'Western Chief', 'Western Express', 'Wigwam', 'Wildfox', 'Wildfox Couture', 'William Rast', 'Wilson', 'Wilsons Leather', 'Winchester', "Winner's Circle", 'Wolverine', 'Woolrich', 'Woot', 'Wrangler', 'XOXO', 'Xersion', 'Xhilaration', 'Xtreme Couture', 'YSL Yves Saint Laurent', 'Yamaha', 'Yeezy', 'Yeti', 'Yohji Yamamoto', 'Young & Reckless', 'ZARA', 'Zanerobe', 'Zara', 'ZeroXposur', 'Zion Rootswear', 'Zoo York', 'a.n.a', 'a.testoni', 'adidas NEO', 'adidas Originals', 'aerie', 'ethika', 'etnies', 'frogg toggs', 'jansport', 'lululemon athletica', 'papi', 'patagonia', 'prAna', 'rag & bone', 'rue', 'vineyard vines']

In [72]:
print(sorted(sub_dfs['Home']['brand_name'].unique()))

['A Bathing Ape', 'A Pea In The Pod', 'A&A Optical', 'A. Byer', 'AMIA', 'Abbott', 'Adagio', 'Adidas', 'Advanced Graphics', 'AeroLatte', 'AeroPress', 'Agraria', 'Air Wick', 'Alessi', 'Alexander Kalifano', 'All', 'All American', 'All-Clad', 'Alpine', 'Amazon', 'American Girl ®', 'American Vintage', 'American Weigh', 'American apparel', 'Anchor Hocking', 'Anne Geddes', 'Anolon', 'Anthropologie', 'Apple', 'Aria', 'Arm & Hammer', 'Aroma', 'As Seen on TV', 'Aura Cacia', 'Avon', 'Avon Cosmetics, Inc', 'BUNN', 'Back to Basics', 'Ball', 'Baratza', 'Barbie', 'Bass', 'Bath & Body Works', 'Bella Cucina', 'Betsey Johnson', 'Betty Boop', 'Betty Crocker', 'Bialetti', 'Bissell', 'Black & Decker', 'Blendtec', 'Blizzard', 'Bloomfield', 'Blossom Bucket', 'Blunt Power', 'Bodum', 'Bosch', 'Boy + Girl', 'Braun', 'Brentwood', 'Breville', 'Breyer', 'Brighton', 'Brita', 'Brookstone', 'Bulova', 'CBK', 'CORKCICLE', 'Calphalon', 'Calvin Klein', 'Candle-Lite', 'Cannon', 'Capresso', 'Carhartt', 'Carson Home Accents', "Carter's", 'Cascade', 'Champion', 'Charmin', 'Cheetah', "Chef's Choice", "Chef's Secret", 'Chemex', 'Chic', 'Chloe', 'Circulon', "Claire's", 'Coach', 'Coca-Cola', 'Coleman', "Collector's Gallery", 'Colonial Candle', 'Conair', 'Converse', 'Cooks Essentials', 'Copco', 'Corelle', 'CorningWare', 'Corona', 'Crofton', 'Cuisinart', 'Custom Accessories', 'Customized & Personalized', 'Cynthia Rowley', 'DC Comics', 'Danielson Designs', 'Dansk', 'DeLonghi', 'Deco Mesh', 'DecoLav', 'Deltana', 'Demdaco', 'Dior', 'Disguise', 'Disney', 'Downy', 'Dreamgirl', 'Dyson', 'EO Essential Oils', 'Ed Hardy', 'Elements', 'Elite', 'Emerson', 'Emson', 'Euro Cuisine', 'Euro-Pro', 'Excalibur', 'Fabulous Frannie', 'Fagor', 'Farberware', 'Febreze', 'Fetco', 'Fiesta', 'Fila', 'Flavia', 'Floracraft', "Francesca's Collections", 'Frigidaire', 'Funko', 'GAIN', 'GE', 'Gaggia', 'Ganz', 'George Foreman', 'Gevalia', 'Giftcraft', 'Glade', 'Global', 'Godinger', 'Good Cook', 'Grasslands Road', 'Guard Master', 'Gucci', 'Guy Harvey', 'Gypsy', 'H&M', 'HERMES', 'Haier', 'Hallmark', 'Hamilton Beach', 'Hamilton Electronics', 'Harley-Davidson', 'Hasbro', 'Hearthside Collection', 'Hello Kitty', 'Henckels', 'Herbalife', 'HoMedics', 'Hollister', 'Home Interiors', 'Honeywell', 'Hoover', 'Hot Topic', 'Howard Miller', 'IKEA', 'Igloo', 'Illuminations', 'Imperial', 'Instant Pot', 'InterDesign', 'Invicta', 'JCPenney', 'Jack Daniels', 'Jack LaLanne', 'Jay at Play', 'Jim Shore', 'John Deere', 'Jonathan Adler', 'Jordan', 'Joy Mangano', 'Joyce Chen', 'Juiceman', 'Juicy Couture', 'Kalorik', 'Kate Spade', 'Keepsake the Label', 'Kendra Scott', 'Kenmore', 'Keurig', 'Kikkerland', 'Kirkland Signature', 'Kiss Me', 'KitchenAid', 'Koolatron', 'Krups', 'Kylie Cosmetics', 'Kyocera', 'LEGO', 'Lampe Berger', 'Lasko', 'Laura Ashley', 'Lavazza', 'Le Creuset', 'Lenox', 'Libbey', 'Lilly Pulitzer', 'Little Trees', 'Lladro', 'Lodge', 'Lolita', 'Longaberger', 'LuLaRoe', 'Lumisource', 'Lush', 'Lysol', 'M', 'MLB', "Macy's", 'Madison', 'Magic Bullet', 'Margaritaville', 'Marimekko', 'Martha Stewart', 'Marvel', 'Mattel®', 'McFarlane Toys', 'McKenzie', 'Medela', 'Melannco', 'Melissa & Doug', 'Melitta', 'Method', 'Metrokane', 'Michael Aram', 'Michael Kors', 'Mikasa', 'Mirro', 'Movado', 'Mr Coffee', 'Mr. Coffee', 'Mr. Tea', 'Mud Pie', 'NASCAR', 'NFL', 'NO-AD', 'Nambe', 'Nautica', 'Nespresso', 'Nest', 'Nickelodeon', 'Nicole Miller', 'Nike', 'Ninja', 'Nintendo', 'Norpro', 'Nostalgia', 'Nostalgia Electrics', 'OXO', 'Old Navy', 'Oleg Cassini', 'Olympus', 'Omega', 'Oneida', 'Oster', 'Oxford', "P'Kolino", 'PANDORA', 'PINK', 'PUR', 'Pampered Chef', 'Panasonic', 'Park Designs', 'PartyLite', 'Paula Deen', 'Peanuts', 'Pendleton', 'Pfaltzgraff', 'Philadelphia Eagles', 'Philips', 'Pier One', 'Pillsbury', 'Pokemon', 'Pottery Barn', 'Pottery Barn Kids', 'Pre-Seed', 'Precious Moments', 'Presto', 'Primo Emporio', 'Primula', 'Prince LionHeart', 'Prinz', 'Privilege', 'Proctor Silex', 'Progressive International', 'Punch Studio', 'Pyrex', 'Quartet', 'Rachael Ray', 'Rae Dunn', 'Ralph Lauren', 'Regal', 'Renuzit', 'Replogle', 'Restoration Hardware', 'Revere', 'Rival', 'Ronco', 'RoomMates', 'Roomba', 'Rubbermaid', 'Rubies Costume Company', 'Rue21', 'Russ', 'Salton', 'Samsung', 'Sanrio', 'Sanyo', 'Scentsy', 'Sears', 'Seiko', 'Sentry', 'Shabby Chic', 'Shark', 'Sharp', 'Sharper Image', 'Shout', 'Showtime', 'SimpleHuman', 'Skullcandy', 'Slatkin & Co.', 'Snuggie', 'Sonoma', 'Sons of Anarchy', 'Sony', 'Southern Enterprises', 'Southern Living', 'Stanley', 'Star Wars', 'Starbucks', 'Stella & Dot', 'Sterling Industries', 'Studio', 'Summer Infant', 'Sunbeam', 'Supreme', 'Swarovski', 'Swiffer', 'Syroco', 'T Tahari', 'T-fal', 'TOMS', 'Tag', 'Target', 'Tassimo', 'Taylor', 'Teleflora', 'The Body Shop', 'The Magic Bullet', 'The Northwest Company', 'Thermos', 'Tide', 'Tiffany & Co.', 'Tiger', 'Timex', 'Toastmaster', 'Tommy Hilfiger', 'Tools of the Trade', 'Top Fin', 'Tupperware', 'Ulta', 'Umbra', 'Unique Creations', 'Unknown', 'Update International', 'Urban Decay', 'Urban Outfitters', 'Urban Trends', 'Vans', 'Vera Bradley', 'Vera Wang', 'Versace', 'Vickerman', 'Victoria secret', "Victoria's Secret", 'Vintage', 'Vital Baby', 'Vitamix', 'Vollrath', 'WWE', 'Wall Pops', 'Walmart', 'Waring', 'Waterford', 'Waverly', 'Wedgwood', 'Weight Watchers', 'West Bend', 'West Elm', 'Weston', 'Whirlpool', 'White House Black Market', 'White Mountain', 'White Stag', 'Williams Sonoma', 'Willow Tree', 'Wilton', 'Wolfgang Puck', 'WoodWick', 'Wusthof', 'Yankee Candle', 'Yeti', 'Zales', 'Zara', 'Zojirushi', 'doTERRA', 'iRobot', 'kathy ireland', 'office supply brands']

In [73]:
print(sorted(sub_dfs['Vintage & Collectibles']['brand_name'].unique()))

['7 For All Mankind®', 'A Wish Come True', 'A. Byer', 'AC/DC', 'ADAM', 'ALDO', 'ALEX AND ANI', 'ASICS', 'ASOS', 'Abercrombie & Fitch', 'Acacia Swimwear', 'Accessory Power', 'Activision', 'Adidas', 'Adolfo', 'Adrianna Papell', 'Adrienne Vittadini', 'Aeropostale', 'Agent Provocateur', 'Air Force', 'Air Hogs', 'Air Jordan', 'Alexander McQueen', 'Alfred Angelo', 'Alfred Dunner', 'Alice + Olivia', 'AllSaints', 'Almost Famous', 'Alternative', 'Amazon', 'American Apparel', 'American Boy & Girl', 'American Eagle', 'American Girl ®', 'American Rag', 'American apparel', 'Anchor Hocking', 'Andrea by Sadek', 'Angels', 'Angry Birds', 'Ann Taylor LOFT', 'Anne Klein', 'Anthropologie', 'Antique Rivet', 'Antonio Melani', 'Anvil', 'Apple', 'Apple Bottoms', 'Apt.', 'Aquarius', 'Arizona', 'Army', 'Athleta', 'Atmosphere', 'Avanti', 'Avenue', 'Avery', 'Avon', 'A|X Armani Exchange', 'B. Darlin', 'BCBGMAXAZRIA', 'BCBGeneration', 'BDG', 'BOSS HUGO BOSS', 'Baby Phat', 'Bachrach', 'Back to Basics', 'Badgley Mischka', 'Balenciaga', 'Ball', 'Banana Republic', 'Bandai', 'Bape', 'Barbie', 'Basic Editions', 'Bass', 'Bath & Body Works', 'Bebe', 'Belleek', 'BenBat', 'Bench', 'Bethesda Softworks', 'Betsey Johnson', 'Bettie Page', 'Betty Boop', 'Big Bang Theory', 'Big Time Toys', 'Billabong', 'Bioworld Merchandising', 'Blip Toys', 'Blizzard', 'Blue Life', 'Bobbie Brooks', 'Boden', 'Bodum', 'Bongo', 'Bose', 'Boston Proper', 'Bottega Veneta', 'Braetan', 'Bravado', 'Breyer', 'Brighton', 'Brooks Brothers', 'Buck', 'Buckle', 'Budweiser', 'Buffalo Games', 'Buffalo Jeans', 'Bullhead', 'Burberry', 'Burberry London', 'Bvlgari', 'Byer Too', 'CAbi', 'COOGI', 'CORKCICLE', 'Cache', 'Cake', 'Calico Critters', 'Callaway', 'Calvin Klein', 'Canon', 'Canvas', 'Capcom', 'Cardinal Industries', 'Carnival', 'Carolina Colours', 'Carolina Herrera', "Carter's", 'Cartier', 'Cartoon Network', 'Case', 'Catalina', 'Caterpillar', 'Cato', 'Celebrity Pink', 'Celine', 'Chalk Line', 'Champion', 'Chanel', 'Changes', 'Chaps', 'Character', 'Charlotte Russe', 'Charter Club', 'Chaus', "Chico's", 'Chloe', 'Christian Dior', 'Christopher & Banks', 'Circa', 'Cleobella', 'Club Room', 'Coach', 'Coca Cola', 'Coca-Cola', 'Coldwater Creek', 'Cole Haan', 'Colebrook', 'Columbia', 'Comfort Colors', 'Converse', 'Corelle', 'CorningWare', 'Cotton On', 'Cra-Z-Art', 'Croft & Barrow', 'Current/Elliott', 'Customized & Personalized', 'DC Comics', 'DC Direct', 'DIESEL', 'DKNY', 'Dana Buchman', 'Dark Horse', 'David Yurman', "David's Bridal", 'Daytrip', 'Delta', 'Diamond Supply Co.', 'Diane von Furstenberg', 'Dior', 'Disney', 'Disney Jr.', 'Disney Pixar', 'Disney Pixar Cars', 'Disney Princess', 'Dockers', 'Doctor Who', 'Dolce & Gabbana', 'Dolce Vita', 'Dollhouse', 'Donald Trump', 'Dooney & Bourke', 'Dragon Ball Z', 'Drake', 'Dreamworks', 'ELLE', 'EO', 'ESPN', 'Eagle USA', 'Ecko Unltd.', 'Ed Hardy', 'Eddie Bauer', 'Eden', 'Emporio Armani', 'Enesco', 'Escada', 'Esprit', 'Etienne Aigner', 'Express', 'Eyeshadow', 'FOREVER 21', 'FULL TILT', 'Faded Glory', 'Family Guy', 'Fashion Bug', 'Fendi', 'Fiesta', 'Fila', 'Fiore', 'Fire King', 'Fisher-Price', 'Ford', 'Fossil', 'Fox Racing', "Frankie's Bikinis", 'Free People', 'Freeze', 'French Connection', 'Frye', 'Fuji', 'Funimation Production', 'Funko', 'GM', 'GUESS', 'Gallery', 'Ganz', 'Gap', 'GenOne', 'General Electric', 'Gentle Giant', 'Gerber', 'Giant', 'Gildan', 'Gillette', 'Gimmick', 'Giorgio Armani', 'Givenchy', 'Globe', 'Gloria Vanderbilt', 'Greenlight Collectibles', 'Gucci', 'Guess', 'H&M', 'HERMES', 'HUGO', 'HYDRAULIC', 'Hallmark', 'Hamilton Collection', 'Hanes', 'Hard Rock Cafe', 'Harley Davidson', 'Harley-Davidson', 'Hasbro', 'Hasbro Games', 'Heirloom Collectibles', 'Hello Kitty', 'Henri Bendel', 'High Sierra', 'Hollister', 'Holloway', 'Home Interiors', 'Hot Kiss', 'Hot Topic', 'Hot Wheels', 'Hurley', 'INC International Concepts', 'IZOD', 'Imaginext', 'Independent', 'Infinity', 'Iron Fist', 'Iron Maiden', 'Isaac Mizrahi', "It's Our Time", 'J G Hook', 'J Kara', 'J. Crew', 'JCPenney', 'JERZEES', 'Jack Daniels', 'Jaclyn Smith', 'Jada Toys', 'Jade', 'Jadeite', 'Jagermeister', 'Jakks Pacific', 'Jason Wu', 'Jeanne Pierre', 'Jennifer Lopez', 'Jessica McClintock', 'Jessica Simpson', 'Jim Shore', 'Joan Rivers', 'Joe Benbasset', 'John Deere', 'Joie', 'Jolt', 'Jones New York', 'Jordache', 'Jordan', 'Jos. A. Bank', 'Joujou', 'Jovani', 'Juicy Couture', 'Just USA', 'Justice', 'Justin', 'Kardashian Kollection', 'Karen Scott', 'Kate Spade', 'Kendra Scott', 'Kenneth Cole New York', 'Kenneth Cole Reaction', 'Kenneth Jay Lane', 'Kensie', 'Kenwood', 'Kenzo', 'Kiplling', 'Kodak', 'Konami', 'Kylie Cosmetics', 'L.A. Blues', 'L.A.M.B.', 'L.L. Bean', 'LC Lauren Conrad', 'LEGO', 'La Femme', 'Lacoste', 'Lane Bryant', 'Lapis', 'Laura Scott', 'Le Creuset', 'Lee', 'Lenox', 'Leslie Fay', 'Levi', "Levi's®", 'Lilly Pulitzer', 'Liquid Blue', 'Little Tikes', 'Littlest Pet Shop', 'Liz Claiborne', 'London Fog', 'Longaberger', 'Looney Tunes', 'Lord & Taylor', 'Loudmouth Golf', 'Louis Vuitton', 'LuLaRoe', 'Lucky Brand', 'Lululemon', 'Lux', 'M', 'M&M', 'M.I.A.', 'MANDALYNN', 'MARC JACOBS', 'MGA Entertainment', 'MICHI by Michelle Watson', 'MINKPINK', 'MLB', 'Machine', 'Maclaren', 'Madame Alexander', 'Madewell', 'Madison', 'Maison Martin Margiela', 'Maisto', 'Majestic', 'Mandalay', 'Mango', 'Mara Hoffman', 'Marc Ecko', 'Marimekko', 'Marvel', 'Marvel Universe', 'Matchbox', 'Mattel®', 'Maurices', 'Max Studio', 'McFarlane Sports', 'McFarlane Toys', 'Mega Bloks', 'Merona', 'Method', 'Mezco', 'Michael Kors', 'Michael Simon', 'Microsoft', 'Middleton Doll Company', 'Midway', 'Mimi', 'Misfits', 'Mishka', 'Missoni', 'Moda International', 'Monet', 'Monopoly', 'Monster', 'Moose Toys', 'Mopas', 'Moschino', 'Mossimo', 'Mossy Oak', 'Moulin', 'Mudd', 'Murano', 'My Little Pony', 'My Michelle', 'NASCAR', 'NBA', 'NCAA', 'NECA', 'NFL', 'NHL', 'Nambe', 'Nautica', 'Neiman Marcus', 'Nerf', 'Netgear', 'New Directions', 'New York & Company', 'Next', 'Nick Jr.', 'Nickelodeon', 'Nicole Miller', 'Nike', 'Nikon', 'Nine West', 'Nintendo', 'Nixon', 'No Boundaries', 'Nollie', 'Nordstrom', 'Not Rated', 'Notations', "O'Neill", 'Oakley', 'Obey', 'Old Navy', 'Olivia Moon', 'One Step Up', 'One Teaspoon', 'Oneida', 'Oscar de la Renta', "Osh Kosh B'gosh", 'PANDORA', 'PINK', 'PUMA', 'Pacific Sunwear', 'Panasonic', 'Panhandle Slim', 'Papaya', 'Paradise Collection', 'Paramount', 'Paris Blues', 'Parker', 'PartyLite', 'Peanuts', 'Penguin', 'Pepe Jeans', 'Pepsi', 'Perry Ellis', 'Pfaltzgraff', 'Philadelphia Eagles', 'Phillips', 'Pier One', 'Pierre Cardin', 'Play Along', 'Playmates', 'Playmobil', 'Playskool', 'Poetry', 'Pokemon', 'Pokemon USA', 'Polaroid', 'Polo', 'Polo Ralph Lauren', 'Pottery Barn', 'Prada', 'Precious Moments', 'Pressman Toy', 'Prestige', 'Primark', 'Pringle of Scotland', 'Pure Boxing', 'Pyrex', 'Quacker Factory', 'REPORT', 'RVCA', 'Rachael Ray', 'Rachel Zoe', 'Rae Dunn', 'Rafaella', 'Ralph Lauren', 'Ravensburger', 'Rawlings', 'Ray-Ban', 'Razer', 'Realtree', 'Reba', 'Rebecca Minkoff', 'Recoton', 'Reebok', 'Refuge', 'Requirements', 'Revell', 'Revere', 'Rewind', 'Ripple Junction', 'Riva Designs', "Roaman's", 'Rolex', 'Ronni Nicole', 'Roots', 'Roulette', 'Route', 'Roxy', 'Royal', 'Ruff Hewn', 'Russ', 'Russell Athletic', 'SO', 'Sag Harbor', 'Saga', 'Saint Laurent', 'Saks Fifth Avenue', 'Salvatore Ferragamo', 'Samsung', 'San Lorenzo', 'Sarah Spencer', 'Scarlett', 'Schleich', 'Scholastic', 'Screen Stars', 'Sean John', 'Sears', 'Sega', 'Seiko', 'Sesame Street', 'Shabby Chic', 'Sharper Image', 'Sherri Hill', 'Shirley Of Hollywood', 'Silver', 'Similac', 'Simplicity', 'Simply Vera Vera Wang', 'Skywalker Trampolines', 'Snap-on', 'Soft Surroundings', 'Sons of Anarchy', 'Sony', 'Southpole', 'Spalding', "Spencer's", 'Spin Master', 'Spyder', 'Square Enix', 'St. John', "St. John's Bay", 'Stamped', 'Stanley', 'Star Wars', 'Starbucks', 'Starter', 'Steiff', 'Stella McCartney', 'Steve Madden', 'Stone Fox Swim', 'Stussy', 'Style&co.', 'Sunbeam', 'Sundance', 'Supreme', 'Swarovski', 'TOMS', 'TOMY', 'Tag', 'Tahari', 'Talbots', 'Target', 'Texas Instruments', 'The Freshnes', 'The Limited', 'The North Face', 'Thermos', 'Thinkway', 'Thomas & Friends', 'Tianello', 'Tiara International', 'Tiffany & Co.', 'Timex', 'Tivoli', 'Tommy Hilfiger', 'Tonka', 'Tootsie', 'TopShop', 'Topps', 'Torrid', 'Tory Burch', 'Toys R Us', 'Tripp NYC', 'True Religion Brand Jeans', 'Tultex', 'Tumi', 'Tupperware', 'Twenty One', 'Tyler Rose', 'UGG Australia', 'UNIF', 'USAopoly', 'Undefeated', 'Under Armour', 'Uniden', 'Uniqlo', 'Universal Studios', 'Unknown', 'Urban Outfitters', 'VANS', 'Valentino', 'Valerie Stevens', 'Van Heusen', 'Vanilla Star', 'Vanity', 'Vans', 'Vaseline', 'Vera Bradley', 'Vera Wang', 'Versace', 'Victoria secret', "Victoria's Secret", 'Victorinox Swiss Army®', 'Vince', 'Vince Camuto', 'Vintage', 'Vittorio St. Angelo', 'Vivienne Westwood', 'Viz Media', 'Volcom', 'Von Dutch', 'WILLOW', 'WWE', 'Warner Bros.', 'Warner Brothers', 'Warrior', 'Waverly', 'Wedgwood', 'West Bend', 'West Elm', 'Wet Seal', 'White House Black Market', 'White Stag', 'Wildfox Couture', 'Willow Tree', 'Windsor', 'Winterland', 'Wizards of the Coast', 'Wrangler', 'XOXO', 'Xbox', 'Xhilaration', 'YMI', 'YSL Yves Saint Laurent', 'Yeti', 'ZARA', 'Zac Posen', 'Zana Di', 'Zara', 'Zippo', 'a.n.a', 'adidas Originals', 'dELiA*s', 'dressbarn', 'l.e.i.', 'patagonia', 'plenty by Tracy Reese', 'prAna', 'rag & bone', 'rue', 'tokidoki', 'vineyard vines']

In [74]:
print(sorted(sub_dfs['Other']['brand_name'].unique()))

['3M®', '7 For All Mankind®', 'A Bathing Ape', 'A Pea In The Pod', 'A+D', 'A. Byer', 'AA Aquarium', 'ACCEL', 'ACDelco', 'AG Adriano Goldschmied', 'API', 'ASICS', 'ASUS', 'AT-A-GLANCE', 'Abbott', 'Abercrombie & Fitch', 'Able provider', 'Act', 'Actron®', 'Adams', 'Adidas', 'Advanced Healthcare Distributors', 'Advantage', 'Advil', 'Aeropostale', 'Affliction', 'Air Jordan', 'Akai', 'Alcon', 'Alfred Dunner', 'All', 'All Four Paws', 'All Living Things', 'Almay', 'Almost Famous', "Altar'd State", 'Always', 'Amazon', 'Amazon Essentials', 'Ambiance Apparel', 'American Apparel', 'American Eagle', 'American Fighter', 'American Girl ®', 'American Rag', 'American apparel', 'Amsoil', 'Anastasia Beverly Hills', 'Andis', 'Andrew Christian', 'Angels', 'Ann Taylor', 'Ann Taylor LOFT', 'Anne Michelle', 'Anthropologie', 'Apple', 'Aqua Clear', 'Aquafresh', 'Aquaphor', 'Aqueon', 'Arbonne', 'Archie Comics', 'Ardell', 'Arden B', 'Arizona Jean Company', 'Arm & Hammer', 'Armani Jeans', 'Armor All®', 'Army', 'Aroma', 'Arrid', 'Artful Dodger', 'As Seen on TV', 'Ashley Stewart', 'Aspen Pet', 'Astroglide', 'Attends', 'Attention', 'Audio-Technica', 'Aura Cacia', 'Aussie', 'Auto Expressions', 'Auto Meter', 'Auto Ventshade®', 'Autolite®', 'Automotive Innovations', 'Aveda', 'Aveeno', 'Avent', 'Avery', 'Avon', 'Axe', 'Azo', 'A|X Armani Exchange', 'Aéropostale', 'B Darlin', 'B O X Packaging', 'BB', 'BDG', 'BKE', 'BMW', 'BOSS HUGO BOSS', 'Baby Brezza', 'Baby Essentials', 'BabyGanics', 'Bachmann Trains', 'Baker & Taylor', 'Balenciaga', 'Ban', 'Banana Republic', 'Band-Aid', 'Bape', 'Barbasol', 'Barbie', "Barron's", 'Bass', 'Bath & Body Works', 'Bausch & Lomb', 'Bayer Expert Care', 'Bebe', 'Bebe Au Lait', 'Belltech', 'Ben Nye', 'Benefit', 'Bergan', 'BernzOmatic', 'Best Friends by Sheri', 'Betsey Johnson', 'Beverly Hills Polo Club', 'Bic', 'Big Star', 'Billabong', 'Bio Oil', 'Bio Spot', 'Bioworld', 'Birkenstock', 'Bissell', 'Black Rivet', 'Blackhawk', 'Blink', 'Blip Toys', 'Blue Buffalo', 'Blue Microphones', 'Blush', 'Bobeau', 'Bongo', 'Boohoo', 'Boppy', 'Bosch', 'Bose', 'Boudreaux', 'Brake & Wheel Parts', 'Brandy Melville', 'Braun', 'Bravado', 'Bret Michaels', 'Breyer', 'Brooks', 'Brooks Brothers', 'Brother', 'Brut', 'Buckle', 'Budge', 'Bugaboo', 'Bugle Boy', 'Bullhead', 'Bully Dog', 'Bumbo', 'Burberry', 'Burberry London', "Burt's Bees", 'C&A', 'CAbi', 'CLEAN', 'Cacique', 'Calvin Klein', 'Canon', 'Carbon', 'Carefree', 'Caress Brand Shop', 'Carhartt', 'Carlos Santana', 'Carlson Pet Products', 'Carmex', "Carol's Daughter", "Carter's", 'Casio', 'Catit', 'Cato', 'Century', 'CeraVe', 'Cesar', 'Cetaphil', 'Chaco', 'Champion', 'Champs', 'Chanel', 'Chaps', 'Chapstick', 'Charlotte Russe', 'Charlotte Tilbury', 'Charmin', 'Charming Charlie', 'Chelsea & Violet', 'Cherokee', 'Chevrolet', 'Chevron®', "Chico's", "Children's Place", 'Chilton', 'Chloe', 'Christian Dior', 'Chroma™', 'Chuckit', 'Cinch', 'Cinema Secrets', "Claire's", 'Clarks', 'Classic Accessories', 'Clear Care', 'Cleobella', 'Clinique', 'Clio', 'Coach', 'Cobra Electronics', 'Coca-Cola', 'Colgate', 'ColourPop Cosmetics', 'Columbia', 'Comfort Colors', 'Comfort Zone', 'Comic Images', 'Comme des Garcons', 'Comotomo', 'Complete', 'ComplyRight', 'Conair', 'Converse', 'Converse Shoes', 'Cotton On', 'Cottonelle', 'Cover Girl', 'Craftsman', 'Crayola', 'Crest', 'CritterWare', 'Crocs', 'Croft & Barrow', 'Crosley Radio', 'Cruiser Accessories', 'Curel', 'Custom Accessories', 'Customized & Personalized', "D'Addario", 'DC Comics', 'DC Shoes', 'DGK', 'DJI', 'DYMO', "David's Bridal", 'Daytrip', 'DeWALT®', 'Deb', 'Degree', 'Dell', 'DenTek', 'Denso', 'Deux Lux', 'Dial', 'Diamond Supply Co.', 'Dickies', 'Dingo', 'Dior', 'Disney', 'Disney Collection', 'Disney Pixar Cars', 'Disney Princess', 'Disney Tsum Tsum', 'Diva', 'Divided', 'Dog MD', 'Dogswell', 'Dolce & Gabbana', 'Dooney & Bourke', 'Dorman®', 'Dove', 'Downy', "Dr. Brown's", 'Dr. Martens', "Dr. Miracle's", "Dr. Scholl's", 'Dr. Seuss', 'Dremel', 'Dress Barn', 'Drinkwell', 'Dubble Bubble', 'ECI', 'ELF', 'ENERGIE', 'EO', 'EO Essential Oils', 'East 5th', 'Ecotools', 'Ed Hardy', 'Edelbrock', 'Elixir', 'Elmers', 'Enfagrow', 'Enfamil', 'Epson', 'Eric Carle', 'Ernie Ball', 'Estee Lauder', 'Eucerin', 'Evenflo', 'Exo-Terra', 'Express', 'Eyeshadow', 'FOREVER 21', 'Fabletics', 'Faded Glory', 'Famous Stars & Straps', 'Fashion Nova', 'Fathead', 'Febreze', 'Fellowes', 'Fender', 'Fendi', 'Fifth Sun', 'Fila', 'First Act', 'Fisher-Price', 'Fitbit', 'Flexi', 'Floam', 'Fluval', 'For Love and Lemons', 'Ford Motorsport', 'Fossil', 'Fox', "Francesca's Collections", 'Franco Sarto', 'Free People', 'Friskies', 'Frontline', 'Fuji', 'Funimation Production', 'Funko', 'Furla', 'Furminator', 'G by Guess', 'G.M. Specialties', 'GAIN', 'GM Performance Parts', 'GUESS', 'GUM', 'Gap', 'Garmin', 'Garnier', 'Generic', 'George', 'Gerber', 'Gianni Bini', 'Gillette', "Gilligan & O'Malley", 'Givenchy', 'Glo-Brite', 'GloFish', 'Go Gear', 'GoGroove Pal', 'GoPro', 'Gold Bond', "Gold's Gym", 'Goodyear', 'Graco', "Grannick's", 'GreatNeck®', 'Greenies', 'Grreat Choice', 'Gucci', 'Guerlain', 'Gymboree', 'H&M', 'HERMES', 'HOBO INTERNATIONAL', 'HP', 'HTC', 'Halo', 'Hanes', 'Hanna Anderson', 'Harley-Davidson', 'HarperCollins Publishers', 'Hartz', 'Hasbro', 'Hasbro Games', 'Haynes', 'Head & Shoulders', 'Hein Werner', 'Hello Kitty', 'Herschel Supply Company', 'Hikari', "Hill's Ideal Balance", "Hill's Science Diet", 'Himalayan', 'HoMedics', 'Hohner Kids', 'Hollister', 'Hollister Co.', 'Honda', 'Hot Kiss', 'Hot Topic', 'Hot Wheels', 'Hourglass Cosmetics', 'Huggies', 'Hunter', 'Hurley', 'Hush Puppies', 'Hype', 'Hypertech®', 'IKEA', 'INC International Concepts', 'ION Audio', 'IT Cosmetics', 'IZOD', 'Ice', 'Incipio', 'Infantino', 'Ingersoll-Rand', 'Innovative Designs', 'Iris', 'Irish Spring', 'Isabella Rodriguez', 'Ivivva', 'Ivory Ella', 'J. Crew', 'JBL', 'JERZEES', 'JET Performance', 'James Avery', 'JanSport', 'Jeffree Star Cosmetics', 'Jelly Belly', 'Jennifer Lopez', 'Jessica Simpson', 'Jim Dunlop', 'Jimmy Choo', 'Joan Rivers', 'John Paul Pet', 'Johnson & Johnson', 'Jolyn Clothing', 'Jones New York', 'Joovy', 'Jordache', 'Jordan', 'Jordans', 'Joyce Leslie', 'Juicy Couture', 'Junk Food Clothing', 'Justice', 'K Advantix', 'KAPLAN MD', 'KONG', 'KY', 'Kala', 'Kangertech', 'Karen Scott', 'Kasper', 'Kat Von D', 'Kate Spade', 'Kay Jewelers', 'Kaytee', 'Kelly & Katie', 'Kendall & Kylie', 'Kendra Scott', 'Kenneth Cole New York', 'Keurig', "Kibbles 'n Bits", "Kiehl's", 'Kiinde', 'Kipling', 'Kleenex', 'Kodak', 'Konami', 'Kotex', 'Kurgo', 'Kyjen', 'Kylie Cosmetics', 'Kyodan', "L'Oreal", 'L.A.M.B.', 'LA Hearts', 'LC Lauren Conrad', 'LEGO', 'LF', 'LOFT', 'La Girl', 'Lacoste', 'Lancome', 'Lane Bryant', 'Laura Geller', 'Lauren Ralph Lauren', 'Leap Frog', 'Lenovo', 'Level', 'Levi Strauss & Co.', "Levi's®", 'Lexmark', 'Lia Sophia', 'Life Is Good', 'Lilly Pulitzer', 'Lily Rose', 'Listerine', 'Litter Genie', 'Little Gifts', 'Littlest Pet Shop', 'Lixit', 'Liz Claiborne', 'Logitech', 'Lole', 'Longchamp', 'Lorac', 'Louis Vuitton', 'Love Culture', 'LuLaRoe', 'Lucky Brand', 'Lucky Dog', "Lulu's", 'Lululemon', 'Lush', 'Lysol', 'M&M', 'MAC', 'MAC Cosmetics', 'MAM', 'MARC JACOBS', 'MCM', 'MGA Entertainment', 'MLB', 'Mac Cosmetic', "Macy's", 'Madden Girl', 'Madewell', 'Mag 1', 'Magic', 'Manga', 'Marineland', 'Marshall', 'Martha Stewart', 'Marvel', 'Mary Kay', 'Mattel®', 'Maurices', 'Max and Cleo', 'May Queen', 'Maybelline', 'Mechanix Wear®', 'Medela', 'Members Only', "Men's Warehouse", 'Meow Mix', 'Merona', 'Metaphor', 'Michael Kors', 'Microsoft', 'Midtronics', 'Midwest', 'Mighty Fine', "Miller's Forge", 'Miss Me', 'Missguided', 'Mitchum', 'Modern Amusement', 'Monistat', 'Monoprice', 'Moose Toys', 'Mopar', 'Morphe Cosmetics', 'Mossimo', 'Mossimo Supply Co.', 'Motherhood', 'Motherhood Maternity', 'Motor Trend', 'Motorcycle Stuff', 'Mountain Hardwear', 'Mudd', 'Multipet', 'Munchkin', "Musician's Gear", 'Mustela', 'My Little Pony', 'NASCAR', 'NBA', 'NECA', 'NEXXUS', 'NFL', 'NYX', 'Nair', 'Nars', 'Nasty Gal', 'National Geographic', 'Native', "Nature's Variety Instinct", 'Nautica', 'Neff', 'Neff Headwear', 'Neiman Marcus', 'Neosporin', 'Nerf', 'Neutrogena', 'New Balance', 'New Directions', 'New York & Company', 'Nickelodeon', 'Nicole Miller', 'Nike', 'Nikon', 'Nine West', 'Nintendo', 'Nivea', 'No Boundaries', 'Nokia', 'Nook', 'Nordstrom', 'Norelco', 'North Face', 'Nothing But Love', 'Noxzema', 'Nuk', 'Nutri-Vet', 'Nutro Max', 'Nyko', 'Nylabone', 'O.B.', 'Oakley', 'Obey', 'Obey Clothing', 'Ocean Pacific', 'Off-White', 'Office Depot', 'Oh Baby by Motherhood', 'Oki', 'Olay', 'Old Navy', 'Old Spice', 'Omega Paw', 'Omron', 'On the Byas', 'On-Stage Stands', 'One Teaspoon', 'Opti-Free', 'Optimum', 'Oral B', "Osh Kosh B'gosh", 'Oster', 'Outward Hound', 'Oxbow', 'Oxford', 'PANDORA', 'PINK', 'PUMA', 'Pampers Cruisers', 'Panasonic', 'Pantene', 'Papaya', 'Paper Magic', 'Paper Mate', 'Paris Blues', 'Parker', 'Patagonia, Inc.', 'Paul Frank', 'Peaches', 'Peanuts', 'Pearhead', 'Pedialyte', 'Pediasure', 'Pedigree', 'Perfect Equipment®', 'Performance Tool', 'Permatex®', 'Pet Gear', 'Pet Life', 'PetRageous Designs', 'PetSafe', 'PetSmart', 'Petmate', 'Pets First', 'Philadelphia Eagles', 'Philips', 'Phillips 66', 'Philosophy', 'Physicians Prefer', 'Pilot', 'Pioneer', 'Pioneer Inc.', 'Pioneer Pet', 'Plackers', 'PlastiColor®', 'Play-Doh', 'Playskool', 'Playtex', 'Plus White', 'Poise', 'Pokemon', 'Pokemon USA', 'Poligrip', 'Polo Ralph Lauren', 'PopSockets', 'Post-it', 'Pottery Barn Kids', 'Prada', 'Prairie Dog Antlers', 'Precision', 'Prevail', 'Prevue Pet Products', 'ProTec', 'Puffs', 'Puppia', 'Pur Minerals', 'Purina', 'Purina Beneful', 'Purina One', 'PylePro', 'Pyrex', 'Quantum Mechanix', 'Quartet', 'Que', 'Qupid', 'RCA', 'ROMWE', 'RVCA', 'Rae Dunn', 'Rain-X', 'Ralph Lauren', 'Rampage', 'Rave', 'Ray-Ban', 'Razer', 'Reach', 'Realtree', 'Reebok', 'Reef', 'Refuge', 'Regalo', 'Relic', 'Remington', 'Renew Life', 'Renu', 'Rep-Cal', 'RevitaLens', 'Revlon', 'Revolution', 'Richell', 'Riders by Lee', 'Right Guard', 'Ring of Fire', 'Riviera', "Roaman's", 'Rock & Roll Cowgirl', 'Rock Revival', 'Rocket Dog', 'Rocksmith', 'Rockstar', 'Rodan and Fields', 'Roku', 'Rolex', 'Roots', 'Roxy', 'Royal', 'Rubbermaid', 'Rue21', 'Rugged Ridge', 'Ryka', 'SEPHORA COLLECTION', 'SKECHERS', 'SPANX', 'Safety 1st', 'Safety st', 'Saint Laurent', 'Sally Hansen', 'Samsung', 'Sanrio', 'Scentsy', 'Schick', 'Schleich', 'Scholastic', 'Scholastic Children', 'Scope Brand Shop', 'Scotch', 'Scott Paper', 'Scott®', 'Sean John', 'Secret', 'Sega', 'SeneGence', 'Sennheiser', 'Sensodyne', 'Sentry', 'Sephora', 'Seresto', 'Sergeants', 'Sesame Street', 'Sharper Image', 'Sharpie', 'Shea Moisture', 'Sheba', 'Sheer Cover', 'Shell', 'Sherpa', 'Shift Management', 'Silver Jeans', 'Silver Jeans Co.', 'Similac', 'Simply Southern', 'Singing Machine', 'Skin Inc.', 'Skintimate', 'Slime®', 'Smead', 'Snap-on', 'Snark', 'Soffe', 'Softcup', 'Softsoap', 'Solvit', 'Sonoma', 'Sons of Anarchy', 'Sony', 'Southern Marsh', 'SpeeCo', 'Speed Stick', 'Speedo', 'Spell & The Gypsy Collective', "Spencer's", 'Sperry', 'Spider-Man', 'Spin Master', 'Sporn', 'Spyder', 'Square Enix', 'St. Ives', "St. John's Bay", 'Stamped', 'Stanley', 'Star Wars', 'Starbucks', 'Starmark', 'Starter', 'Stayfree', 'Sterling Publishing', 'Steve Madden', 'Stila Cosmetics', 'Streamlight®', 'Stussy', 'Stüssy', 'Suave', "Summer's Eve", 'Sunbeam', 'Superior', 'Supreme', 'Sure', 'Swarovski', 'Swell', 'Sylvania', 'TENA', 'TOMS', 'TRESemme', 'Talbots', 'Tampax', 'Target', 'Tarte', 'Telebrands', 'Tetra', 'Texas Instruments', 'The Body Shop', "The Children's Place", "The Doctor's", 'The Honest Company', 'The Instrument Store', 'The Noco Company', 'The North Face', 'The Original Muck Boot Co.', 'The Whistler Group', 'Thor', 'Thrasher', 'Thrive', 'Thule', 'Thundershirt', 'Tick Twister', 'Tide', 'Tidy Cats', 'Tieks', 'Tiffany & Co.', "Tilly's", 'Timberland', 'Tobi', 'Tom Ford', "Tom's of Maine", 'Tommee Tippee', 'Tommy Bahama', 'Tommy Hilfiger', 'Tone', 'Tony Hawk', 'Too Faced', 'Top Fin', 'Top Paw', 'TopShop', 'Topps', 'Torrid', 'Tory Burch', 'Toys R Us', 'True Religion', 'True Religion Brand Jeans', 'Tupperware', 'Twenty One', 'UGG', 'UGG Australia', 'UNIONBAY', 'UNIQLO', 'UPPAbaby', 'Ulta', 'Ultra Pro', 'Under Armour', 'Universal Studios', 'Unknown', 'Urban Decay', 'Urban Outfitters', 'Urban Pipeline', 'VANS', 'VIGOSS', 'Vanity', 'Vans', 'Vaseline', 'Veet', 'Vera Bradley', 'Vic Firth', 'Vicks', 'Victoria secret', "Victoria's Secret", 'Viktor & Rolf', 'Vince Camuto', 'Vintage', 'Viper', 'Virgin Only', 'Vitakraft', 'Viz Media', 'WD-40®', 'WWE', 'Wacom', 'Wagner Lighting', 'Wahl', 'Walter Hagen', 'Ware', 'Waterpik', 'Weaver Leather', 'Wet Seal', 'Wet n Wild', 'Whiskas', 'Whisker City', 'White House Black Market', 'Wild Diva', 'Wildfox', 'Windsor', 'Wizards of the Coast', "World's Best", 'WowWee', 'Wrangler', 'Xbox', 'Xerox', 'Xhilaration', 'YMI', 'YSL Yves Saint Laurent', 'Yamaha', 'Yankee Candle Company', 'Yeezy', 'Yeti', 'Yohji Yamamoto', 'Younique', 'Younique products', 'ZARA', 'Zales', 'Zara', 'Zilla', 'Zoo Med', "a'gaci", 'a.n.a', 'aden & anais', 'adidas NEO', 'aerie', 'bareMinerals', 'doTERRA', 'eos', 'etnies', 'goDog', 'iHome', 'jansport', 'kate spade new york', 'lululemon athletica', 'nununu', 'patagonia', 'pet brands', 'theBalm', 'tokidoki', 'vineyard vines']

In [75]:
print(sorted(sub_dfs['Handmade']['brand_name'].unique()))

['A Bathing Ape', 'Adidas', 'American Girl ®', 'American apparel', 'Apple', 'Audi', 'Avon', 'Bass', 'Betsey Johnson', 'Birkenstock', 'Blue Buffalo', 'Brandy Melville', 'Calvin Klein', 'Chloe', 'Coach', 'Colorbok', 'Converse', 'Custom Accessories', 'Customized & Personalized', 'DC Comics', "David's Bridal", 'Dior', 'Disney', 'Dooney & Bourke', 'EK Success', 'Elmers', 'Faber-Castell', 'Fila', 'Funimation Production', 'Gucci', 'Guy Harvey', 'H&M', 'Hallmark', 'Hello Kitty', 'Hollister', 'Hot Topic', 'Independent', 'JanSport', 'Jordan', 'Kate Spade', 'Kylie Cosmetics', 'LuLaRoe', 'MARC JACOBS', 'MLB', 'Martha Stewart', 'Medela', 'Michael Kors', 'Mighty Fine', 'Minnie Mouse', 'Nabisco Variety', 'Nike', 'North Face', 'PINK', 'Philadelphia Eagles', 'Pokemon', 'Rae Dunn', 'Ralph Lauren', 'Rowan', 'Samsung', 'Serenity', 'Sesame Street', 'Spiderman', 'Spin Master', 'Supreme', 'Swarovski', 'TOMS', 'Target', 'Tommy Hilfiger', 'Under Armour', 'Unknown', 'Vans', 'Vantage', 'Victoria secret', "Victoria's Secret", 'Vintage', 'Wilton', 'Yeti', 'Zara', 'jansport', 'vineyard vines']

In [76]:
print(sorted(sub_dfs['Sports & Outdoors']['brand_name'].unique()))

['5.11 Tactical', 'A Bathing Ape', 'AND1', 'ASICS', 'Abu Garcia', 'Adams Golf', 'Adidas', 'Airwalk', 'Alstyle Apparel', 'American apparel', 'Apple', 'Aqua Lung Sport', 'Arena', 'As Seen on TV', 'Asics', 'Avia', 'BLACKHAWK!', 'BLOCH', 'BOGS', 'Babolat', 'Barnett Crossbows', 'Barska', 'Bass', 'Bauer', 'Bear Archery', 'Bebe', 'Berkley', 'Betsey Johnson', 'Blitz®', 'Bowflex', 'Bridgestone Golf', 'Brine', 'Brooks', 'Browning', 'Brute', 'Burton', 'Bushnell', 'CCM', 'CORKCICLE', 'Callaway', 'CamelBak', 'Capezio', 'Carhartt', 'Cascade', 'Century', 'Champion', 'Champro', 'Cleveland', 'Cleveland Golf', 'Cliff Keen', 'Coach', 'Coast', 'Cobra', 'Coleman', 'Columbia', 'Comfort Zone', 'Contigo', 'Converse Shoes', 'Crocs', 'Crosman', 'Cutters', 'DBX', 'DC Shoes', 'DC Sports', 'Danskin Now', 'DeMarini', 'Diadora', 'Dior', 'Disney', 'Dragon', 'Dunlop', 'Easton', 'Eddie Bauer', 'Ektelon', 'Everlast', 'EvoShield', 'Faded Glory', 'Field & Stream', 'Fila', 'Fitbit', 'Fitness Gear', 'Flow Society', 'Focus', 'FootJoy', 'Fox', 'Franklin', 'Freestyle', 'Frost Cutlery', 'Fuji', 'GAIAM', 'Gamo', 'Garmin', 'Gatorade', 'Gearbox', 'Gerber', 'Giro', 'Glamorise', "Gold's Gym", 'GolfBuddy', 'Greg Norman', 'Gregory', 'Gucci', 'Gymshark', 'H&M', 'HEAD', 'Head', 'Helly Hansen', 'High Sierra', 'Hollister', 'Hoverboard', 'Huffy', 'Inov-', 'Ivivva', 'Jacques Moret', 'JanSport', 'Jockey', 'John Deere', 'Johnson', 'Jordan', 'Jordans', 'Justice', 'KEEN', 'Keen', 'Kelty', 'Keys', 'KidCo', 'Kryptonics', 'Kylie Cosmetics', 'Lane Bryant', 'Liz Claiborne', 'Lole', 'Louisville Slugger', 'LuLaRoe', 'Lululemon', 'MLB', 'Majestic', 'Manduka', 'Marmot', 'Marucci', 'Marvel', 'Maverik', 'Maxima', 'McDavid', 'McFarlane Sports', 'Merrell', 'Michael Kors', 'Mikasa', 'Mission', 'Mitchell & Ness', 'Mitre', 'Mizuno', 'Motorcycle Stuff', 'Mountain Hardwear', 'Mueller', 'Mylec', 'NBA', 'NFL', 'Nathan', 'Natural Fitness', 'Nerf', 'New Balance', 'New Era', 'Nick Jr.', 'Nike', 'Nike Golf', "O'Neill", 'OGIO®', 'Oakley', 'Odyssey', 'Omron', 'Op', 'Outdoor Life', 'PGA TOUR', 'PING', 'PINK', 'PROPPER', 'PUMA', 'Patagonia', 'Pearl Izumi', 'Pelican', 'Penn', 'Penn Fishing', 'Perception Sport', 'Philadelphia Eagles', 'Ping', 'Pinnacle Fishing', 'Pokemon', 'Polar', 'Powerbolt', 'Prince', 'Pro Line', 'Quantum', 'Quiksilver', 'RBK', 'REI', 'Rage Broadheads', 'Ralph Lauren', 'Ram', 'Raskullz', 'Rawlings', 'Razor', 'Redington', 'Reebok', 'Reusch', 'Riddell', 'Roller Derby', 'Rollerblade', 'Rossignol', 'Roxy', 'Russell Athletic', 'SKLZ', 'SO', 'SPY', 'STX', 'Salomon', 'Samsung', 'Sanrio', 'ScentBlocker', 'Schutt', 'Schwinn', 'Select', 'Sheffield Knives', 'Shimano Fishing', 'Shock Doctor', 'SkyCaddie', 'Slazenger', 'SmartWool', 'Smith Optics', 'Sof Sole', 'Soffe', 'Spalding', 'Speedo', 'Sperry Top-Sider', 'Spyder', 'Srixon', 'St. Croix', 'Stance', 'Streamlight®', 'Sun Mountain', 'Super Stroke', 'Supreme', 'Swell', 'Swimways', 'Swix', 'TETON Sports', 'TOMS', 'TYR', 'Tail', 'Target', 'TaylorMade', 'Team Apparel', 'Tervis', 'The North Face', 'Thrive', 'Thule', 'Timber Creek', 'Titleist', 'Top Flite', 'Topps', 'Trina Turk', 'UFC', 'UGG Australia', 'USA Hockey', 'Umbro', 'Under Armour', 'Unknown', 'Vans', 'Victoria secret', "Victoria's Secret", 'Victorinox Swiss Army®', 'Vintage', 'Volcom', 'Walter Hagen', 'Warrior', 'Weight Watchers', 'Wilson', 'Winchester', 'Worth', 'Xenith', 'Yakima', 'Yeti', 'Yonex', 'Zaggora', 'Zoo York', 'Zumba', 'abercrombie kids', 'anon', 'deBeer', 'elite HOCKEY', 'jansport', 'lululemon athletica', 'patagonia', 'prAna']

##### 2-3-4. 'brand_name' 결측치 처리 : 대분류(cat_1) 각각 속한 브랜드 자동출력

In [77]:
# ==============================================
# Step 1: 카테고리별 실제 브랜드 리스트 자동 추출
# ==============================================

# 현재 존재하는 모든 cat_1 카테고리 확인
all_categories = train['cat_1'].unique()
print("전체 카테고리 목록:")
print(sorted(all_categories))

# 카테고리별 브랜드 딕셔너리 자동 생성
AUTO_CATEGORY_BRANDS = {}

for cat in all_categories:
    # Unknown 제외하고 실제 브랜드명만 추출
    brands = sorted(
        sub_dfs[cat]['brand_name'].dropna().unique().tolist()
        if cat in sub_dfs
        else train[train['cat_1'] == cat]['brand_name'].dropna().unique().tolist()
    )
    # Unknown 제거
    brands = [b for b in brands if b not in ['Unknown', 'unknown', '', 'nan']]
    AUTO_CATEGORY_BRANDS[cat] = brands
    print(f"{cat}: {len(brands)}개 브랜드 추출")

print("\n추출 완료!")

전체 카테고리 목록:
['Beauty', 'Electronics', 'Handmade', 'Home', 'Kids', 'Men', 'Other', 'Sports & Outdoors', 'Vintage & Collectibles', 'Women']
Men: 1220개 브랜드 추출
Electronics: 343개 브랜드 추출
Women: 2541개 브랜드 추출
Home: 427개 브랜드 추출
Sports & Outdoors: 292개 브랜드 추출
Vintage & Collectibles: 694개 브랜드 추출
Beauty: 516개 브랜드 추출
Other: 1002개 브랜드 추출
Kids: 932개 브랜드 추출
Handmade: 79개 브랜드 추출

추출 완료!

In [100]:
# ==============================================
# Step 2: 카테고리별 브랜드 확인 (검증용)
# ==============================================

# 특정 카테고리 브랜드 출력해서 확인
for cat in all_categories:
    print(f"\n=== {cat} 브랜드 샘플 (상위 25개) ===")
    print(AUTO_CATEGORY_BRANDS[cat][:25])

=== Men 브랜드 샘플 (상위 25개) ===
['10.Deep', '21men', '24/7 Comfort Apparel', '47', '47 Brand', '5.11 Tactical', '7 Diamonds', '7 For All Mankind®', '8732 Apparel', 'A Bathing Ape', 'A&A Optical', 'A&R Sports', 'A+D', 'A-Shirt', 'A.K.A', 'A.P.C.', 'A/X Armani Exchange', 'AC/DC', 'ADAM', 'AG Adriano Goldschmied', 'AKOO', 'ALDO', 'AND', 'AND1', 'ASICS']

=== Electronics 브랜드 샘플 (상위 25개) ===
['1byone', '2K Games', '3M®', 'A Bathing Ape', 'A&A Optical', 'ACER', 'AMD', 'ASUS', 'AT&T', 'ATI Technologies', 'Accessory Collective', 'Acer', 'Activision', 'Adidas', 'Advent', 'Agfa', 'Aiptek', 'Air Hogs', 'Alienware', 'Alpine', 'Altec Lansing', 'Amazon', 'AmazonBasics', 'American Girl ®', 'American apparel']

=== Women 브랜드 샘플 (상위 25개) ===
['!iT Jeans', '191 Unlimited', '21men', '24/7 Comfort Apparel', '2XU', '3.1 Phillip Lim', '47 Brand', '5.11 Tactical', '525 America', '5th & Ocean', '7 For All Mankind®', '90 Degree By Reflex', 'A Bathing Ape', 'A Pea In The Pod', 'A Plus Child Supply', 'A Wish Come True', 'A&A Optical', 'A&E', 'A&R Sports', 'A+D', 'A. Byer', 'A.B.S. by Allen Schwartz', 'A.K.A', 'A.L.C.', 'A.P.C.']

=== Home 브랜드 샘플 (상위 25개) ===
['A Bathing Ape', 'A Pea In The Pod', 'A&A Optical', 'A. Byer', 'AMIA', 'Abbott', 'Adagio', 'Adidas', 'Advanced Graphics', 'AeroLatte', 'AeroPress', 'Agraria', 'Air Wick', 'Alessi', 'Alexander Kalifano', 'All', 'All American', 'All-Clad', 'Alpine', 'Amazon', 'American Girl ®', 'American Vintage', 'American Weigh', 'American apparel', 'Anchor Hocking']

=== Sports & Outdoors 브랜드 샘플 (상위 25개) ===
['5.11 Tactical', 'A Bathing Ape', 'AND1', 'ASICS', 'Abu Garcia', 'Adams Golf', 'Adidas', 'Airwalk', 'Alstyle Apparel', 'American apparel', 'Apple', 'Aqua Lung Sport', 'Arena', 'As Seen on TV', 'Asics', 'Avia', 'BLACKHAWK!', 'BLOCH', 'BOGS', 'Babolat', 'Barnett Crossbows', 'Barska', 'Bass', 'Bauer', 'Bear Archery']

=== Vintage & Collectibles 브랜드 샘플 (상위 25개) ===
['7 For All Mankind®', 'A Wish Come True', 'A. Byer', 'AC/DC', 'ADAM', 'ALDO', 'ALEX AND ANI', 'ASICS', 'ASOS', 'Abercrombie & Fitch', 'Acacia Swimwear', 'Accessory Power', 'Activision', 'Adidas', 'Adolfo', 'Adrianna Papell', 'Adrienne Vittadini', 'Aeropostale', 'Agent Provocateur', 'Air Force', 'Air Hogs', 'Air Jordan', 'Alexander McQueen', 'Alfred Angelo', 'Alfred Dunner']

=== Beauty 브랜드 샘플 (상위 25개) ===
['% Pure', 'A Wish Come True', 'A. Byer', 'AERIN', 'Abercrombie & Fitch', 'Acure', 'Adidas', 'Air Wick', 'Alexandra de Markoff', 'Algenist', 'Almay', 'Amazon', 'Ambi', 'American Eagle', 'Anastasia Beverly Hills', 'Andis', 'Anthropologie', 'Apple', 'Arbonne', 'Ardell', 'Ariana Grande', 'Artist Couture', 'As Seen on TV', 'Aussie', 'Australian Gold']

=== Other 브랜드 샘플 (상위 25개) ===
['3M®', '7 For All Mankind®', 'A Bathing Ape', 'A Pea In The Pod', 'A+D', 'A. Byer', 'AA Aquarium', 'ACCEL', 'ACDelco', 'AG Adriano Goldschmied', 'API', 'ASICS', 'ASUS', 'AT-A-GLANCE', 'Abbott', 'Abercrombie & Fitch', 'Able provider', 'Act', 'Actron®', 'Adams', 'Adidas', 'Advanced Healthcare Distributors', 'Advantage', 'Advil', 'Aeropostale']

=== Kids 브랜드 샘플 (상위 25개) ===
['A Bathing Ape', 'A Plus Child Supply', 'A Wish Come True', 'A+D', 'A-Shirt', 'A.D. Sutton & Sons', 'ABC Studios', 'AKA New York', 'ART', 'ASICS', 'ASUS', 'Abercrombie & Fitch', 'Accessory Innovations', 'Accessory Workshop', 'Activision', 'Adidas', 'Adora', 'Aero', 'Aeropostale', 'Affliction', 'Agetec', 'Air Hogs', 'Air Jordan', 'Air Zone', 'Akai']

=== Handmade 브랜드 샘플 (상위 25개) ===
['A Bathing Ape', 'Adidas', 'American Girl ®', 'American apparel', 'Apple', 'Audi', 'Avon', 'Bass', 'Betsey Johnson', 'Birkenstock', 'Blue Buffalo', 'Brandy Melville', 'Calvin Klein', 'Chloe', 'Coach', 'Colorbok', 'Converse', 'Custom Accessories', 'Customized & Personalized', 'DC Comics', "David's Bridal", 'Dior', 'Disney', 'Dooney & Bourke', 'EK Success']

In [101]:
# 모든 카테고리에 공통으로 적용할 브랜드
COMMON_BRANDS = [
    '3M®','7 For All Mankind®', "A.P.C.", 'ALDO','ASICS','A&A Optical','Amazon','AmazonBasics',
    '21men','A+D', 'A&E', 'A Bathing Ape', 'A Pea In The Pod','A. Byer','Abercrombie & Fitch',
    'PINK', 'Nike', 'Fila', 'Under Armour','Adidas', 'Apple', 'Samsung', 'MLB', 'Avon', 'Air Jordan',
    'Target', 'Converse', 'Disney','North Face', 'UNIQLO', 'Zara', 'Gucci', 'A Wish Come True',
    'Vans','Supreme', 'TOMS', 'Ralph Lauren','jansport','Chloe','Michael Kors','H&M','Carhartt',
    'CORKCICLE', 'Yeti', 'Tommy Hilfiger', 'Victoria secret','Dior',"LuLaRoe",'Birkenstock','Joyfolie',
    'Jordan','Dolce & Gabana','Guy Harvey', 'Sons of Anarchy','Hollister','Pokemon','Philadelphia Eagles',
    'Bass','doTERRA','American apparel','MARC JACOBS','Kylie Cosmetics'
    ]

In [102]:
# ==============================================
# Step 3: 브랜드 매칭 함수 정의
# ==============================================

def extract_brand_auto(row, brand_list, common_brands=COMMON_BRANDS):
    """
    데이터에서 추출한 실제 브랜드 리스트로 결측치 채우기
    우선순위: 기존 브랜드 유지 > 카테고리 브랜드 매칭 > 공통 브랜드 매칭 > Unknown
    """
    # 이미 브랜드가 있으면 유지
    if row['brand_name'] not in ['Unknown', 'unknown', '', 'nan'] and pd.notnull(row['brand_name']):
        return row['brand_name']
    
    # 텍스트 준비 (name + item_description)
    text = ' '.join([
        str(row['name']),
        str(row['item_description'])
    ]).lower()
    
    # 카테고리 특화 브랜드 먼저 탐색
    for brand in brand_list:
        if str(brand).lower() in text:
            return brand
    
    # 공통 브랜드 탐색
    for brand in common_brands:
        if str(brand).lower() in text:
            return brand
    
    return 'Unknown'

In [103]:
# ==============================================
# Step 4: 카테고리별 브랜드 결측치 채우기 적용
# ==============================================

print("브랜드 결측치 자동 채우기 시작...\n")

# train 처리
for cat in all_categories:
    brand_list = AUTO_CATEGORY_BRANDS.get(cat, [])
    mask = train['cat_1'] == cat
    
    train.loc[mask, 'brand_name'] = (
        train[mask].apply(
            lambda row: extract_brand_auto(row, brand_list), axis=1
        )
    )
    
    # 진행상황 출력
    filled_rate = (train.loc[mask, 'brand_name'] != 'Unknown').mean() * 100
    print(f"  {cat:30s}: {filled_rate:.1f}% 브랜드 확인")

# test 처리 (train에서 추출한 브랜드 리스트 동일 적용)
print("\ntest 데이터 처리 중...")
for cat in all_categories:
    brand_list = AUTO_CATEGORY_BRANDS.get(cat, [])
    mask = test['cat_1'] == cat
    
    if mask.sum() == 0:  # 해당 카테고리가 test에 없으면 스킵
        continue
        
    test.loc[mask, 'brand_name'] = (
        test[mask].apply(
            lambda row: extract_brand_auto(row, brand_list), axis=1
        )
    )

브랜드 결측치 자동 채우기 시작...

  Men                           : 95.2% 브랜드 확인
  Electronics                   : 94.0% 브랜드 확인
  Women                         : 96.2% 브랜드 확인
  Home                          : 92.5% 브랜드 확인
  Sports & Outdoors             : 76.4% 브랜드 확인
  Vintage & Collectibles        : 94.7% 브랜드 확인
  Beauty                        : 96.3% 브랜드 확인
  Other                         : 71.7% 브랜드 확인
  Kids                          : 85.8% 브랜드 확인
  Handmade                      : 28.8% 브랜드 확인

test 데이터 처리 중...

In [104]:
# ==============================================
# Step 5: 최종 결과 확인
# ==============================================

train_final_rate = (train['brand_name'] != 'Unknown').mean() * 100
test_final_rate  = (test['brand_name'] != 'Unknown').mean() * 100

print(f"\n{'='*40}")
print(f"train 최종 브랜드 확인율: {train_final_rate:.1f}%")
print(f"test  최종 브랜드 확인율: {test_final_rate:.1f}%")
print(f"{'='*40}")

# 카테고리별 최종 확인율 정리
print("\n=== 카테고리별 최종 브랜드 확인율 ===")
for cat in all_categories:
    mask = train['cat_1'] == cat
    rate = (train.loc[mask, 'brand_name'] != 'Unknown').mean() * 100
    bar  = '█' * int(rate // 5)  # 간단한 바 차트
    print(f"  {cat:30s}: {rate:5.1f}% {bar}")

========================================
train 최종 브랜드 확인율: 92.0%
test  최종 브랜드 확인율: 92.0%
========================================

=== 카테고리별 최종 브랜드 확인율 ===
  Men                           :  95.2% ███████████████████
  Electronics                   :  94.0% ██████████████████
  Women                         :  96.2% ███████████████████
  Home                          :  92.5% ██████████████████
  Sports & Outdoors             :  76.4% ███████████████
  Vintage & Collectibles        :  94.7% ██████████████████
  Beauty                        :  96.3% ███████████████████
  Other                         :  71.7% ██████████████
  Kids                          :  85.8% █████████████████
  Handmade                      :  28.8% █████

In [105]:
# Unknown 샘플 확인 - 왜 브랜드를 못 찾았는지 살펴보기
unknown_samples = train[train['brand_name'] == 'Unknown'][
    ['name', 'item_description', 'cat_1']
].sample(25, random_state=42)

print(unknown_samples.to_string())

                                    name                                                                                                                                          item_description        cat_1
359525                            Blouse                                                                                                                                                Super cute        Women
600354                             1 box                                                                                                                                      35$ shipping 600 box        Other
228112            Boys Sweatpants Bundle                                                                                                                                                       GUC         Kids
479825           [rm] Best Buy Gift Card                                                                         This is a brand new, never been used [rm] Best Buy gift card that doesn't expire.        Other
1294427               Beautiful cardigan                                                                                                                                           Great condition        Women
1010492           ON HOLD FOR STRAWBERRI                                                                      Toy locker with keys and lock Has a slot to put a picture in top right Has 3 shelves        Other
739334              Tools of Titans book                                                                                                                     Book by Tim Ferris. 4 hour work week.        Other
204253      Light up fidget spinner [rm]                                                                                                                                        No description yet         Kids
11487            World history text book                                                                                                           Good condition paper back! Willing to negotiate        Other
175285       Boys shirt and jogger pants                                                                                                          Size 5 summer muscle shirt and grey jogger pants         Kids
204132            Violet Voss Holy Grail                                                                                                                    New palette, never used only swatched.       Beauty
670862         Deal Tuscan Hills EYEBROW                                                                                                          Deal Tuscan Hills 6PC Perfect EYEBROW Design Kit       Beauty
400526                 Rap Snacks 5 Bags                                                                                               5 Bags, 1 of each Legit seller Get them before I sell out!!     Handmade
1100796         2 Bracelet free-shipping        Beautiful 2 bracelets. you will receive the ones on the picture if you have any questions please let me know thank you I also do combined shipping     Handmade
995389            Mini Ice Cream Squishy                                                                                                   •Squishy but fast rising •Has defect (shown in picture)         Kids
84112                    Boggs Toddler 6                                                                                                  Super cute toddler Boggs with lots of life left in them.         Kids
239664                       Sugar scrub                                                                                                                                        No description yet       Beauty
614707           Iz Winter Plaid Peacoat                                                                                      Very stylish peacoat. Plaid white/black. The coat is used condition.        Women
1370300                 iPod shuffle 1gb                                                                                                                       Never used brand new still in box!!  Electronics
690246     Holiday Santa & Penguin Totes  New, never been used. Super cute for the holidays, can be used as a stalking or a great way to hold things. Perfect size for kids. I have two of these!!        Women
596973            Uniform jumper 16 NWOT                                                          New no tag. Cat and Jack navy school uniform jumper. Pleated skirt zip closure in back, size 16.         Kids
188743    Tiffany bag, boxes and pouches                                                                                                          1 bag, 2 boxes, 2 pouches. AUTHENTIC. No refunds         Home
916813                Acrylic Tip Slicer                                                                                                    Never used for nails. I sold the kit and never used it       Beauty
1064759  35 sea glass light purple. #001                                                                                                                  Real sea glass in light color of purple.         Kids
133064            Elephant Wish Bracelet                                                                                                                           [rm] shipped! Pick any color :)     Handmade

In [107]:
# 팬덤/캐릭터 키워드 피처 추가
FANDOM_KEYWORDS = [
    'BTS', 'Kpop', 'K-pop', 'Anime', 'Disney', 'Marvel', 'DC',
    'Harry Potter', 'Star Wars', 'Pokemon', 'Panic At The Disco',
    'Taylor Swift', 'Ariana Grande', 'Kendall', 'Kylie', 'The Vamps', 'Ren and Stimpy',
    'hello kitty','Mickey Mouse', 'The Beatles'
]

def has_fandom(text):
    text = str(text)
    return int(any(kw.lower() in text.lower() for kw in FANDOM_KEYWORDS))

train['is_fandom'] = (
    train['name'] + ' ' + train['item_description']
).apply(has_fandom)

print(f"팬덤 상품 수: {train['is_fandom'].sum()}")

팬덤 상품 수: 50268

In [108]:
train['brand_name'].nunique()

4883

In [109]:
print(train['brand_name'].value_counts().head(25))  # 전체 상위 브랜드 확인

brand_name
Unknown              119076
M                     91460
PINK                  64480
Nike                  55786
LuLaRoe               50781
Victoria's Secret     48637
All                   37460
DL                    26125
Apple                 24023
GH                    16670
Op                    15956
FOREVER 21            15555
GE                    15463
Nintendo              15132
Michael Kors          14867
Lululemon             14613
American Eagle        14059
Disney                13714
Adidas                13073
Rae Dunn              12991
Ash                   12951
Coach                 12425
Sephora               12216
Com                   11660
SO                    10998
Name: count, dtype: int64

'brand_name' = 'M' 확인 필요

In [110]:
train[train['brand_name']=='M']

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description,cat_1,cat_2,cat_3,is_fandom
9,9,Porcelain clown doll checker pants VTG,3,Vintage & Collectibles/Collectibles/Doll,M,8.0,0,I realized his pants are on backwards after th...,Vintage & Collectibles,Collectibles,Doll,0
42,42,lots of Korean Nature Republic face mask,1,Beauty/Skin Care/Face,M,14.0,1,"totally 36 masks, will be expired on Feb..",Beauty,Skin Care,Face,0
43,43,Apricot beige stick foundation!!,1,Beauty/Makeup/Face,M,12.0,1,Great quality!!! Fast free shipping!! You can ...,Beauty,Makeup,Face,0
44,44,Glass Christmas Bowl✨,2,Vintage & Collectibles/Collectibles/Glass,M,12.0,1,Brand new! Never used smoking bowl. Just bough...,Vintage & Collectibles,Collectibles,Glass,0
49,49,Younique 3d fiber lash mascara,1,Beauty/Makeup/Eyes,M,9.0,1,Younique 3d fiber lash mascara will quickly be...,Beauty,Makeup,Eyes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1482407,1482407,Slim extreme fat burner serum,1,Beauty/Skin Care/Body,M,16.0,0,Firming Fighting cellulite Sliming Body contou...,Beauty,Skin Care,Body,0
1482466,1482466,For V,1,Home/Artwork/Paintings,M,31.0,0,"Painting With signature added 16x20 Canvas, ha...",Home,Artwork,Paintings,0
1482498,1482498,Cupquake beauty rush mist ON HOLD,3,Beauty/Fragrance/Women,M,27.0,0,No description yet,Beauty,Fragrance,Women,0
1482501,1482501,Jeffrey Star Velour Liquid Lipstick,2,Beauty/Makeup/Lips,M,38.0,0,Hey so I ordered these online and finally got ...,Beauty,Makeup,Lips,0
1482502,1482502,"MURANO, GLASS FISH PAPERWEIGHT",3,Home/Home Décor/Home Décor Accents,M,41.0,0,"Made In Italy, Solid Glass and Very Heavy, Pap...",Home,Home Décor,Home Décor Accents,0

### 3. 텍스트 핵심 키워드 추출 (자연어 정리) : TF-IDF 방식 사용

In [112]:
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack

# 불용어 설정 (영어 기본 + 커스텀 추가)
stop_words = set(stopwords.words('english'))
custom_stops = {'item', 'please', 'great', 'good', 'nice', 'make', 'used', 'new'}
stop_words.update(custom_stops)

def clean_text(text):
    """텍스트 정제: 소문자화, 특수문자 제거, 불용어 제거"""
    if pd.isnull(text):
        return 'unknown'
    
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)  # 특수문자 제거
    
    tokens = text.split()
    tokens = [t for t in tokens if t not in stop_words and len(t) > 1]
    
    return ' '.join(tokens)

# 텍스트 정제 적용
train['clean_desc'] = train['item_description'].apply(clean_text)
train['clean_name'] = train['name'].apply(clean_text)
test['clean_desc']  = test['item_description'].apply(clean_text)
test['clean_name']  = test['name'].apply(clean_text)

# name + description 합치기
train['text_combined'] = train['clean_name'] + ' ' + train['clean_desc']
test['text_combined']  = test['clean_name']  + ' ' + test['clean_desc']

# TF-IDF 벡터화 (상위 50,000 단어만 사용)
tfidf_desc = TfidfVectorizer(max_features=50000, ngram_range=(1, 2))

X_train_text = tfidf_desc.fit_transform(train['text_combined'])
X_test_text  = tfidf_desc.transform(test['text_combined'])

print(f"TF-IDF 행렬 크기: {X_train_text.shape}")

TF-IDF 행렬 크기: (1482535, 50000)

### 4. 제품 특징 feature 생성 : 색깔, 소재

In [41]:
# 색상 키워드
COLORS = ['red','blue','green','black','white','pink','purple',
          'yellow','orange','grey','gray','brown','gold','silver']

# 소재 키워드
MATERIALS = ['cotton','leather','silk','wool','polyester','nylon',
             'denim','linen','velvet','suede','rubber','metal']

def extract_features(text):
    """텍스트에서 색상, 소재 추출"""
    text = str(text).lower()
    colors    = [c for c in COLORS    if c in text]
    materials = [m for m in MATERIALS if m in text]
    return (
        colors[0]    if colors    else 'unknown',
        materials[0] if materials else 'unknown'
    )

train[['color', 'material']] = train['text_combined'].apply(
    lambda x: pd.Series(extract_features(x))
)
test[['color', 'material']] = test['text_combined'].apply(
    lambda x: pd.Series(extract_features(x))
)

# 묶음/개수 추출 (예: "set of 3", "bundle", "lot of")
def has_bundle(text):
    text = str(text).lower()
    return int(any(w in text for w in ['bundle', 'set of', 'lot of', 'pack of', 'set']))

train['is_bundle'] = train['text_combined'].apply(has_bundle)
test['is_bundle']  = test['text_combined'].apply(has_bundle)

### 5-6. 모델 학습 및 가격 예측

In [42]:
from sklearn.preprocessing import LabelEncoder
from scipy.sparse import hstack, csr_matrix
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_log_error

# 레이블 인코딩 (카테고리형 변수)
cat_cols = ['cat_1', 'cat_2', 'cat_3', 'brand_name',
            'color', 'material']

le = LabelEncoder()
for col in cat_cols:
    combined = pd.concat([train[col], test[col]], axis=0).astype(str)
    le.fit(combined)
    train[col + '_enc'] = le.transform(train[col].astype(str))
    test[col  + '_enc'] = le.transform(test[col].astype(str))

# 수치형 피처 선택
num_features = ['item_condition_id', 'shipping', 'is_bundle',
                'cat_1_enc', 'cat_2_enc', 'cat_3_enc',
                'brand_name_enc', 'color_enc', 'material_enc']

X_train_num = csr_matrix(train[num_features].values)
X_test_num  = csr_matrix(test[num_features].values)

# TF-IDF + 수치형 합치기
X_train_all = hstack([X_train_text, X_train_num])
X_test_all  = hstack([X_test_text,  X_test_num])

# 타겟: 가격 로그 변환 (왜도 줄이기)
y_train = np.log1p(train['price'])

# 학습/검증 분리
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_all, y_train, test_size=0.1, random_state=42
)

# LightGBM 모델 학습
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'learning_rate': 0.1,
    'num_leaves': 127,
    'n_estimators': 1000,
    'min_child_samples': 20,
    'random_state': 42
}

model = lgb.LGBMRegressor(**params)
model.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    callbacks=[lgb.early_stopping(50), lgb.log_evaluation(100)]
)

# 예측
pred_log = model.predict(X_test_all)
pred_price = np.expm1(pred_log)  # 로그 역변환
pred_price = np.clip(pred_price, 0, None)  # 음수 방지

# 제출 파일 생성
submission = pd.read_csv('sample_submission.csv')
submission['price'] = pred_price
submission.to_csv('my_submission.csv', index=False)
print("제출 파일 생성 완료!")
print(submission.head())

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 105.385548 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1123105
[LightGBM] [Info] Number of data points in the train set: 1334281, number of used features: 50006
[LightGBM] [Info] Start training from score 2.978544
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 0.507799
[200]	valid_0's rmse: 0.486044
[300]	valid_0's rmse: 0.476043
[400]	valid_0's rmse: 0.469779
[500]	valid_0's rmse: 0.465474
[600]	valid_0's rmse: 0.462057
[700]	valid_0's rmse: 0.459193
[800]	valid_0's rmse: 0.457182
[900]	valid_0's rmse: 0.455465
[1000]	valid_0's rmse: 0.453972
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 0.453972

c:\Users\berga\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

제출 파일 생성 완료!
   test_id      price
0        0   7.548861
1        1  11.036666
2        2  33.649194
3        3  13.766893
4        4   6.926652